# investalyze — ticker profile

Everything we hold for one ticker, table by table: a metadata summary plus a head/tail
preview of the rows. Set `TICKER` (and optionally `MIN_FILL`) and run all. Helpers live
in `helpers.py`.

Probes every table, so it works for both stocks (prices + dividends/splits +
income/balance/cashflow + companies) and non-equity tickers (market_data).

In [2]:
%load_ext autoreload
%autoreload 2
from helpers import connect_readonly, show_ticker_profile

con = connect_readonly()

In [3]:
TICKER = 'TWTR'    # the ticker to profile
MIN_FILL = 0.5     # fundamentals: keep stat columns filled in >= this fraction of rows

show_ticker_profile(con, TICKER, MIN_FILL)

# TWTR

## companies

                                                                               0
Ticker                                                                      TWTR
SrcId                                                                      30388
Src                                                                       simfin
Market                                                                        us
Industry                                                            Online Media
Sector                                                                Technology
Company Name                                                       TWITTER, INC.
IndustryId                                                                101002
ISIN                                                                US90184L1026
End of financial year (month)                                                 12
Number Employees                                                            5500
Business Summary               Twitter Inc is a social networking platform fo...
CIK                                                                      1418091
Main Currency                                                                USD

## company_profile

*no rows*

## company_officers

*no rows*

## prices

*no rows*

## dividends

*no rows*

## splits

*no rows*

## income

### income (as-reported)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
Revenue,45.0,242675000.0,5077482000.0,1141801866.666667,1015416742.208533
Cost of Revenue,45.0,-1797510000.0,-85503000.0,-400582866.666667,355168209.143064
Gross Profit,45.0,130024000.0,3279972000.0,741219000.0,663811433.398618
Operating Expenses,45.0,-3007010000.0,-265248000.0,-787669866.666667,617546870.764317
"Selling, General & Administrative",45.0,-1760306000.0,-144969000.0,-473148266.666667,378543999.134147
Selling & Marketing,45.0,-1175970000.0,-86551000.0,-333508622.222222,263280112.105157
General & Administrative,45.0,-584336000.0,-38734000.0,-139639644.444444,123156466.784987
Research & Development,45.0,-1246704000.0,-119004000.0,-314521600.0,247945262.316046
Operating Income (Loss),45.0,-635831000.0,453325000.0,-46450866.666667,224146681.706179
Non-Operating Income (Loss),45.0,-134158000.0,81626000.0,-15326244.444444,34389561.677502
"Interest Expense, Net",45.0,-105237000.0,19523000.0,-19285066.666667,26410786.600967
"Pretax Income (Loss), Adj.",45.0,-647146000.0,423544000.0,-61777111.111111,236156007.800431
Other Non-Operating Income (Loss),45.0,-48320000.0,97129000.0,3958822.222222,20300515.474074
Income (Loss) from Continuing Operations,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Income (Loss) Incl. Minority Interest,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Pretax Income (Loss),45.0,-727082000.0,828653000.0,-74242422.222222,286616802.487738
"Income Tax (Expense) Benefit, Net",45.0,-1088899000.0,1075520000.0,36641355.555556,363673189.295826
Net Income,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Net Income (Common),45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Interest Expense,37.0,-152878000.0,-10824000.0,-43114918.918919,36873857.30612
Interest Income,30.0,-33985000.0,157703000.0,24247466.666667,38456045.799501

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
82,TWTR,30388,simfin,us,A,False,USD,2012,FY,2012-12-31,2013-03-02,2015-03-02,117401000,117401000,316933000,<NA>,<NA>,<NA>,-128768000,<NA>,<NA>,<NA>,188165000,<NA>,-265248000,-146244000,-86551000,-59693000,-119004000,<NA>,<NA>,<NA>,-77083000,-2087000,-2486000,<NA>,-2486000,<NA>,<NA>,<NA>,399000,-79170000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-79170000,-229000,<NA>,<NA>,None,<NA>,-79399000,<NA>,<NA>,<NA>,-79399000,<NA>,-79399000,<NA>,<NA>,-79399000
24,TWTR,30388,simfin,us,A,False,USD,2013,FY,2013-12-31,2014-03-06,2014-03-06,189510000,189510000,664890000,<NA>,<NA>,<NA>,-266718000,<NA>,<NA>,<NA>,398172000,<NA>,-1034003000,-440011000,-316216000,-123795000,-593992000,<NA>,<NA>,<NA>,-635831000,-11315000,-6860000,<NA>,-6860000,<NA>,<NA>,<NA>,-4455000,-647146000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-647146000,1823000,<NA>,<NA>,None,<NA>,-645323000,<NA>,<NA>,<NA>,-645323000,<NA>,-645323000,<NA>,<NA>,-645323000
38,TWTR,30388,simfin,us,Q,False,USD,2013,Q4,2013-12-31,2014-02-06,2014-03-06,364661000,364661000,242675000,<NA>,<NA>,<NA>,-112651000,<NA>,<NA>,<NA>,130024000,<NA>,-639700000,-244852000,-177305000,-67547000,-394848000,<NA>,<NA>,<NA>,-509676000,-5112000,-2387000,<NA>,-2387000,<NA>,<NA>,<NA>,-2725000,-514788000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-514788000,3317000,<NA>,<NA>,None,<NA>,-511471000,<NA>,<NA>,<NA>,-511471000,<NA>,-511471000,<NA>,<NA>,-511471000
77,TWTR,30388,simfin,us,A,False,USD,2014,FY,2014-12-31,2015-03-02,2015-03-02,604990000,604990000,1403002000,<NA>,<NA>,<NA>,-446309000,<NA>,<NA>,<NA>,956693000,<NA>,-1495559000,-804016000,-614110000,-189906000,-691543000,<NA>,<NA>,<NA>,-538866000,-39485000,-33985000,<NA>,-33985000,<NA>,<NA>,<NA>,-5500000,-578351000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-578351000,531000,<NA>,<NA>,None,<NA>,-577820000,<NA>,<NA>,<NA>,-577820000,<NA>,-577820000,<NA>,<NA>,-577820000
13,TWTR,30388,simfin,us,Q,False,USD,2014,Q1,2014-03-31,2014-05-08,2014-05-08,570205000,570205000,250492000,<NA>,<NA>,<NA>,-85503000,<NA>,<NA>,<NA>,164989000,<NA>,-294360000,-144969000,-106235000,-38734000,-149391000,<NA>,<NA>,<NA>,-129371000,-1769000,-2567000,<NA>,-2567000,<NA>,<NA>,<NA>,798000,-131140000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-131140000,-1222000,<NA>,<NA>,None,<NA>,-132362000,<NA>,<NA>,<NA>,-132362000,<NA>,-132362000,<NA>,<NA>,-132362000
52,TWTR,30388,simfin,us,Q,False,USD,2021,Q2,2021-06-30,2021-07-27,2021-07-27,795633000,872187000,1190427000,<NA>,<NA>,<NA>,-416932000,<NA>,<NA>,<NA>,773495000,<NA>,-743243000,-443384000,-301902000,-141482000,-299859000,<NA>,<NA>,<NA>,30252000,51048000,-4691000,-13893000,9202000,<NA>,<NA>,<NA>,55739000,81300000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,81300000,-15651000,<NA>,<NA>,None,<NA>,65649000,<NA>,<NA>,<NA>,65649000,<NA>,65649000,<NA>,<NA>,65649000
61,TWTR,30388,simfin,us,Q,False,USD,2021,Q3,2021-09-30,2021-10-27,2021-10-27,799370000,865030000,1283817000,<NA>,<NA>,<NA>,-484479000,<NA>,<NA>,<NA>,799338000,<NA>,-776185000,-451933000,-301078000,-150855000,-324252000,<NA>,<NA>,<NA>,23153000,15466000,-5159000,-13284000,8125000,<NA>,<NA>,<NA>,20625000,38619000,-765701000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-727082000,190325000,<NA>,<NA>,None,<NA>,-536757000,<NA>,<NA>,<NA>,-536757000,<NA>,-536757000,<NA>,<NA>,-536757000
53,TWTR,30388,simfin,us,Q,False,USD,2021,Q4,2021-12-31,2022-02-16,2021-10-27,799370000,865030000,1567220000,<NA>,<NA>,<NA>,-515091000,<NA>,<NA>,<NA>,1052129000,<NA>,-884754000,-512870000,-338398000,-174472000,-371884000,<NA>,<NA>,<NA>,167375000,17290000,-3469000,-10824000,7355000,<NA>,<NA>,<NA>,20759000,184665000,0,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,184665000,-2971000,<NA>,<NA>,None,<NA>,181694000,<NA>,<NA>,<NA>,181694000,<NA>,181694000,<NA>,<NA>,181694000
83,TWTR,30388,simfin,us,Q,False,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,1200984000,<NA>,<NA>,<NA>,-507450000,<NA>,<NA>,<NA>,693534000,<NA>,-821367000,-449672000,-299809000,-149863000,-371695000,<NA>,<NA>,<NA>,-127833000,-13988000,-7482000,-15444000,7962000,<NA>,<NA>,<NA>,-6506000,-141821000,970474000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,828653000,-315367000,<NA>,<NA>,None,<NA>,513286000,<NA>,<NA>,<NA>,513286000,<NA>,513286000,<NA>,<NA>,513286000
19,TWTR,30388,simfin,us,Q,False,USD,2022,Q2,2022-06-30,2022-07-26,2022-07-26,766837000,766837000,1176660000,<NA>,<NA>,<NA>,-540676000,<NA>,<NA>,<NA>,635984000,<NA>,-979746000,-524887000,-308301000,-216586000,-454859000,<NA>,<NA>,<NA>,-343762000,7869000,-9747000,-23342000,13595000,<NA>,<NA>,<NA>,17616000,-335893000,-11000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-335904000,65897000,<NA>,<NA>,None,<NA>,-270007000,<NA>,<NA>,<NA>,-270007000,<NA>,-270007000,<NA>,<NA>,-270007000

### income (restated)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
Revenue,45.0,242675000.0,5077482000.0,1141801866.666667,1015416742.208533
Cost of Revenue,45.0,-1797510000.0,-85503000.0,-400582866.666667,355168209.143064
Gross Profit,45.0,130024000.0,3279972000.0,741219000.0,663811433.398618
Operating Expenses,45.0,-3007010000.0,-265248000.0,-787669866.666667,617546870.764317
"Selling, General & Administrative",45.0,-1760306000.0,-144969000.0,-473148266.666667,378543999.134147
Selling & Marketing,45.0,-1175970000.0,-86551000.0,-333508622.222222,263280112.105157
General & Administrative,45.0,-584336000.0,-38734000.0,-139639644.444444,123156466.784987
Research & Development,45.0,-1246704000.0,-119004000.0,-314521600.0,247945262.316046
Operating Income (Loss),45.0,-635831000.0,453325000.0,-46450866.666667,224146681.706179
Non-Operating Income (Loss),45.0,-134158000.0,81626000.0,-15326244.444444,34389561.677502
"Interest Expense, Net",45.0,-98178000.0,19523000.0,-16351244.444444,22089875.084172
"Pretax Income (Loss), Adj.",45.0,-647146000.0,423544000.0,-61777111.111111,236156007.800431
Other Non-Operating Income (Loss),45.0,-73304000.0,97129000.0,1025000.0,23332208.276232
Income (Loss) from Continuing Operations,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Income (Loss) Incl. Minority Interest,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Pretax Income (Loss),45.0,-727082000.0,828653000.0,-74242422.222222,286616802.487738
"Income Tax (Expense) Benefit, Net",45.0,-1088899000.0,1075520000.0,36641355.555556,363673189.295826
Net Income,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Net Income (Common),45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Interest Expense,44.0,-152878000.0,-2654000.0,-38232727.272727,35909955.777248
Interest Income,31.0,-2486000.0,157703000.0,30530129.032258,33416258.532579

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
79,TWTR,30388,simfin,us,A,True,USD,2012,FY,2012-12-31,2013-03-02,2015-03-02,117401000,117401000,316933000,<NA>,<NA>,<NA>,-128768000,<NA>,<NA>,<NA>,188165000,<NA>,-265248000,-146244000,-86551000,-59693000,-119004000,<NA>,<NA>,<NA>,-77083000,-2087000,-2486000,<NA>,-2486000,<NA>,<NA>,<NA>,399000,-79170000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-79170000,-229000,<NA>,<NA>,None,<NA>,-79399000,<NA>,<NA>,<NA>,-79399000,<NA>,-79399000,<NA>,<NA>,-79399000
34,TWTR,30388,simfin,us,A,True,USD,2013,FY,2013-12-31,2014-03-06,2016-02-29,189510000,189510000,664890000,<NA>,<NA>,<NA>,-266718000,<NA>,<NA>,<NA>,398172000,<NA>,-1034003000,-440011000,-316216000,-123795000,-593992000,<NA>,<NA>,<NA>,-635831000,-11315000,-7576000,-7576000,<NA>,<NA>,<NA>,<NA>,-3739000,-647146000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-647146000,1823000,<NA>,<NA>,None,<NA>,-645323000,<NA>,<NA>,<NA>,-645323000,<NA>,-645323000,<NA>,<NA>,-645323000
29,TWTR,30388,simfin,us,Q,True,USD,2013,Q4,2013-12-31,2014-02-06,2016-02-29,364661000,364661000,242675000,<NA>,<NA>,<NA>,-112651000,<NA>,<NA>,<NA>,130024000,<NA>,-639700000,-244852000,-177305000,-67547000,-394848000,<NA>,<NA>,<NA>,-509676000,-5112000,-3103000,-7576000,4473000,<NA>,<NA>,<NA>,-2009000,-514788000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-514788000,3317000,<NA>,<NA>,None,<NA>,-511471000,<NA>,<NA>,<NA>,-511471000,<NA>,-511471000,<NA>,<NA>,-511471000
35,TWTR,30388,simfin,us,A,True,USD,2014,FY,2014-12-31,2015-03-02,2017-02-27,604990000,604990000,1403002000,<NA>,<NA>,<NA>,-446309000,<NA>,<NA>,<NA>,956693000,<NA>,-1495559000,-804016000,-614110000,-189906000,-691543000,<NA>,<NA>,<NA>,-538866000,-39485000,-35918000,-35918000,<NA>,<NA>,<NA>,<NA>,-3567000,-578351000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-578351000,531000,<NA>,<NA>,None,<NA>,-577820000,<NA>,<NA>,<NA>,-577820000,<NA>,-577820000,<NA>,<NA>,-577820000
36,TWTR,30388,simfin,us,Q,True,USD,2014,Q1,2014-03-31,2014-05-08,2015-05-11,570205000,570205000,250492000,<NA>,<NA>,<NA>,-85503000,<NA>,<NA>,<NA>,164989000,<NA>,-294360000,-144969000,-106235000,-38734000,-149391000,<NA>,<NA>,<NA>,-129371000,-1769000,-3102000,-3102000,<NA>,<NA>,<NA>,<NA>,1333000,-131140000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-131140000,-1222000,<NA>,<NA>,None,<NA>,-132362000,<NA>,<NA>,<NA>,-132362000,<NA>,-132362000,<NA>,<NA>,-132362000
11,TWTR,30388,simfin,us,Q,True,USD,2021,Q2,2021-06-30,2021-07-27,2022-07-26,795633000,872187000,1190427000,<NA>,<NA>,<NA>,-416932000,<NA>,<NA>,<NA>,773495000,<NA>,-743243000,-443384000,-301902000,-141482000,-299859000,<NA>,<NA>,<NA>,30252000,51048000,-4691000,-13893000,9202000,<NA>,<NA>,<NA>,55739000,81300000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,81300000,-15651000,<NA>,<NA>,None,<NA>,65649000,<NA>,<NA>,<NA>,65649000,<NA>,65649000,<NA>,<NA>,65649000
72,TWTR,30388,simfin,us,Q,True,USD,2021,Q3,2021-09-30,2021-10-27,2021-10-27,799370000,865030000,1283817000,<NA>,<NA>,<NA>,-484479000,<NA>,<NA>,<NA>,799338000,<NA>,-776185000,-451933000,-301078000,-150855000,-324252000,<NA>,<NA>,<NA>,23153000,15466000,-5159000,-13284000,8125000,<NA>,<NA>,<NA>,20625000,38619000,-765701000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-727082000,190325000,<NA>,<NA>,None,<NA>,-536757000,<NA>,<NA>,<NA>,-536757000,<NA>,-536757000,<NA>,<NA>,-536757000
12,TWTR,30388,simfin,us,Q,True,USD,2021,Q4,2021-12-31,2022-02-16,2021-10-27,799370000,865030000,1567220000,<NA>,<NA>,<NA>,-515091000,<NA>,<NA>,<NA>,1052129000,<NA>,-884754000,-512870000,-338398000,-174472000,-371884000,<NA>,<NA>,<NA>,167375000,17290000,-3469000,-10824000,7355000,<NA>,<NA>,<NA>,20759000,184665000,0,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,184665000,-2971000,<NA>,<NA>,None,<NA>,181694000,<NA>,<NA>,<NA>,181694000,<NA>,181694000,<NA>,<NA>,181694000
76,TWTR,30388,simfin,us,Q,True,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,1200984000,<NA>,<NA>,<NA>,-507450000,<NA>,<NA>,<NA>,693534000,<NA>,-821367000,-449672000,-299809000,-149863000,-371695000,<NA>,<NA>,<NA>,-127833000,-13988000,-7482000,-15444000,7962000,<NA>,<NA>,<NA>,-6506000,-141821000,970474000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,828653000,-315367000,<NA>,<NA>,None,<NA>,513286000,<NA>,<NA>,<NA>,513286000,<NA>,513286000,<NA>,<NA>,513286000
85,TWTR,30388,simfin,us,Q,True,USD,2022,Q2,2022-06-30,2022-07-26,2022-07-26,766837000,766837000,1176660000,<NA>,<NA>,<NA>,-540676000,<NA>,<NA>,<NA>,635984000,<NA>,-979746000,-524887000,-308301000,-216586000,-454859000,<NA>,<NA>,<NA>,-343762000,7869000,-9747000,-23342000,13595000,<NA>,<NA>,<NA>,17616000,-335893000,-11000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-335904000,65897000,<NA>,<NA>,None,<NA>,-270007000,<NA>,<NA>,<NA>,-270007000,<NA>,-270007000,<NA>,<NA>,-270007000

## balance

### balance (as-reported)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
"Cash, Cash Equivalents & Short Term Investments",45.0,424856000.0,8806287000.0,5021883422.222222,1971335802.698982
Cash & Cash Equivalents,45.0,203328000.0,4248702000.0,1781421533.333333,890322498.268429
Short Term Investments,45.0,221528000.0,5483873000.0,3240461888.888889,1274105476.908928
Accounts & Notes Receivable,45.0,112155000.0,1217404000.0,652531755.555556,254617726.08695
"Accounts Receivable, Net",45.0,112155000.0,1217404000.0,652531755.555556,254617726.08695
Other Short Term Assets,45.0,17455000.0,307284000.0,187020955.555556,69009633.303802
Prepaid Expenses,45.0,17455000.0,268564000.0,184567622.222222,66004462.881236
Total Current Assets,45.0,554466000.0,9863742000.0,5861436133.333333,2185124565.914291
"Property, Plant & Equipment, Net",45.0,185574000.0,2175290000.0,988418533.333333,521377813.188792
Other Long Term Assets,45.0,91528000.0,4130416000.0,2144113755.555556,1314287733.024469
Intangible Assets,45.0,3753000.0,156352000.0,75621044.444444,34040379.112671
Goodwill,45.0,68813000.0,1325200000.0,1076835688.888889,322891978.343435
Misc. Long Term Assets,45.0,17795000.0,1776435000.0,475290933.333333,557778906.706705
Total Noncurrent Assets,45.0,277102000.0,6305706000.0,3132532288.888889,1775845372.234659
Total Assets,45.0,831568000.0,15323225000.0,8993968422.222221,3858440520.417999
Payables & Accruals,45.0,61043000.0,1896680000.0,558963933.333333,331600520.121275
Accounts Payable,45.0,8432000.0,325446000.0,130167911.111111,69976114.026282
Other Payables & Accruals,45.0,52611000.0,1688768000.0,428796022.222222,279102082.569629
Total Current Liabilities,45.0,109879000.0,2257919000.0,885851288.888889,610966495.65603
Misc. Long Term Liabilities,45.0,97325000.0,1382694000.0,428889133.333333,397185737.548431
Other Long Term Liabilities,45.0,97325000.0,1382694000.0,428889133.333333,397185737.548431
Total Noncurrent Liabilities,45.0,97325000.0,6629543000.0,2489958533.333333,1681029090.795759
Total Liabilities,45.0,207204000.0,7646806000.0,3375809822.222222,2136788985.099204
Common Stock,45.0,1000.0,4000.0,3622.222222,613.814041
Share Capital & Additional Paid-In Capital,45.0,101788000.0,9249960000.0,7144640555.555555,1857273154.6501
Other Equity,45.0,-200456000.0,199000.0,-59589488.888889,44899611.586507
Equity Before Minority Interest,45.0,624364000.0,8795627000.0,5618158600.0,1975686102.154048
Additional Paid in Capital,45.0,101787000.0,9249956000.0,7144636933.333333,1857272603.977113
Retained Earnings,45.0,-2762808000.0,11586000.0,-1485458377.777778,834196698.514349
Total Equity,45.0,624364000.0,8795627000.0,5618158600.0,1975686102.154048
Total Liabilities & Equity,45.0,831568000.0,15323225000.0,8993968422.222221,3858440520.417999
Short Term Debt,40.0,7248000.0,969241000.0,294818650.0,382915412.015436
Long Term Debt,40.0,1293604000.0,5246849000.0,2318703075.0,1171135500.68613

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
31,TWTR,30388,simfin,us,A,False,USD,2012,Q4,2012-12-31,2013-03-06,2014-03-06,117401000,117401000,424856000,203328000,221528000,112155000,112155000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,17455000,17455000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,554466000,185574000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,91528000,3753000,68813000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18962000,277102000,831568000,61043000,8432000,<NA>,<NA>,52611000,48836000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,109879000,<NA>,<NA>,<NA>,97325000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,97325000,97325000,207204000,872536000,101788000,1000,101787000,<NA>,<NA>,-349303000,-657000,624364000,<NA>,624364000,831568000
59,TWTR,30388,simfin,us,Q,False,USD,2013,Q4,2013-12-31,2014-03-06,2014-03-06,364661000,364661000,2234054000,841010000,1393044000,247328000,247328000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,93297000,93297000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2574679000,332662000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,458899000,77627000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17795000,791561000,3366240000,138304000,27994000,<NA>,<NA>,110310000,87126000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,225430000,<NA>,<NA>,<NA>,190804000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,190804000,190804000,416234000,<NA>,3944955000,3000,3944952000,<NA>,<NA>,-994626000,-323000,2950006000,<NA>,2950006000,3366240000
87,TWTR,30388,simfin,us,A,False,USD,2013,Q4,2013-12-31,2014-03-06,2014-03-06,189510000,189510000,2234054000,841010000,1393044000,247328000,247328000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,93297000,93297000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2574679000,332662000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,458899000,77627000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17795000,791561000,3366240000,138304000,27994000,<NA>,<NA>,110310000,87126000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,225430000,<NA>,<NA>,<NA>,190804000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,190804000,190804000,416234000,<NA>,3944955000,3000,3944952000,<NA>,<NA>,-994626000,-323000,2950006000,<NA>,2950006000,3366240000
47,TWTR,30388,simfin,us,Q,False,USD,2014,Q1,2014-03-31,2014-05-08,2014-05-08,570205000,570205000,2176595000,960755000,1215840000,237860000,237860000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,90925000,90925000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2505380000,383272000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,467557000,71451000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32629000,850829000,3356209000,170998000,19714000,<NA>,<NA>,151284000,90253000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,261251000,<NA>,<NA>,<NA>,158112000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,158112000,158112000,419363000,<NA>,4064130000,3000,4064127000,<NA>,<NA>,-1126988000,-296000,2936846000,<NA>,2936846000,3356209000
21,TWTR,30388,simfin,us,Q,False,USD,2014,Q2,2014-06-30,2014-08-11,2014-08-11,595607000,595607000,2097031000,844976000,1252055000,287082000,287082000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,79773000,79773000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2463886000,467634000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,653297000,105497000,514601000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33199000,1120931000,3584817000,270631000,23084000,<NA>,<NA>,247547000,99744000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,370375000,<NA>,<NA>,<NA>,167849000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,167849000,167849000,538224000,<NA>,4318024000,3000,4318021000,<NA>,<NA>,-1271630000,199000,3046593000,<NA>,3046593000,3584817000
16,TWTR,30388,simfin,us,Q,False,USD,2021,Q3,2021-09-30,2021-10-27,2021-10-27,799370000,865030000,7411312000,3473865000,3937447000,1014208000,1014208000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,223714000,194914000,<NA>,28800000,<NA>,<NA>,<NA>,<NA>,8649234000,2053480000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3886631000,46702000,1293826000,<NA>,<NA>,1133816000,<NA>,<NA>,<NA>,<NA>,1412287000,5940111000,14589345000,1896680000,207912000,<NA>,<NA>,1688768000,<NA>,<NA>,<NA>,<NA>,218301000,<NA>,<NA>,<NA>,<NA>,218301000,2114981000,4250678000,<NA>,<NA>,1051055000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1051055000,5301733000,7416714000,<NA>,8468712000,4000,8468708000,<NA>,-5291000,-1183996000,-106794000,7172631000,<NA>,7172631000,14589345000
7,TWTR,30388,simfin,us,A,False,USD,2021,Q4,2021-12-31,2022-02-16,2022-02-16,799370000,865030000,6393682000,2186549000,4207133000,1217404000,1217404000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,307284000,266484000,<NA>,40800000,<NA>,<NA>,<NA>,<NA>,7918370000,2082160000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4058986000,69324000,1301520000,<NA>,<NA>,1148573000,<NA>,<NA>,<NA>,<NA>,1539569000,6141146000,14059516000,1121521000,203171000,<NA>,<NA>,918350000,<NA>,<NA>,<NA>,<NA>,222346000,<NA>,<NA>,<NA>,<NA>,222346000,1343867000,4253019000,<NA>,<NA>,1155431000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1155431000,5408450000,6752317000,<NA>,8432116000,4000,8432112000,<NA>,-5295000,-1002302000,-117320000,7307199000,<NA>,7307199000,14059516000
83,TWTR,30388,simfin,us,Q,False,USD,2021,Q4,2021-12-31,2022-02-16,2022-02-16,799370000,865030000,6393682000,2186549000,4207133000,1217404000,1217404000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,307284000,266484000,<NA>,40800000,<NA>,<NA>,<NA>,<NA>,7918370000,2082160000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4058986000,69324000,1301520000,<NA>,<NA>,1148573000,<NA>,<NA>,<NA>,<NA>,1539569000,6141146000,14059516000,1121521000,203171000,<NA>,<NA>,918350000,<NA>,<NA>,<NA>,<NA>,222346000,<NA>,<NA>,<NA>,<NA>,222346000,1343867000,4253019000,<NA>,<NA>,1155431000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1155431000,5408450000,6752317000,<NA>,8432116000,4000,8432112000,<NA>,-5295000,-1002302000,-117320000,7307199000,<NA>,7307199000,14059516000
27,TWTR,30388,simfin,us,Q,False,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,6261953000,2283308000,3978645000,948142000,948142000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,265973000,265973000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7476068000,2150581000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3924308000,59725000,1298462000,<NA>,<NA>,941883000,<NA>,<NA>,<NA>,<NA>,1624238000,6074889000,13550957000,928302000,189524000,<NA>,<NA>,738778000,<NA>,<NA>,<NA>,<NA>,208405000,<NA>,<NA>,<NA>,<NA>,208405000,1136707000,5244181000,<NA>,<NA>,1265153000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1265153000,6509334000,7646041000,<NA>,6677298000,4000,6677294000,<NA>,<NA>,-616860000,-155522000,5904916000,<NA>,5904916000,13550957000
4,TWTR,30388,simfin,us,Q,False,USD,2022,Q2,2022-06-30,2022-07-26,2022-07-26,766837000,766837000,6120743000,2680596000,3440147000,972591000,972591000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,180247000,180247000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7273581000,2175290000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4130416000,52643000,1303438000,<NA>,<NA>,997900000,<NA>,<NA>,<NA>,<NA>,1776435000,6305706000,13579287000,829281000,153092000,<NA>,<NA>,676189000,<NA>,<NA>,<NA>,<NA>,187982000,<NA>,<NA>,<NA>,<NA>,187982000,1017263000,5246849000,<NA>,<NA>,1382694000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1382694000,6629543000,7646806000,<NA>,7096603000,4000,7096599000,<NA>,<NA>,-963666000,-200456000,5932481000,<NA>,5932481000,13579287000

### balance (restated)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
"Cash, Cash Equivalents & Short Term Investments",45.0,424856000.0,8806287000.0,5021883422.222222,1971335802.698982
Cash & Cash Equivalents,45.0,203328000.0,4248702000.0,1781421533.333333,890322498.268429
Short Term Investments,45.0,221528000.0,5483873000.0,3240461888.888889,1274105476.908928
Accounts & Notes Receivable,45.0,112155000.0,1217404000.0,652531755.555556,254617726.08695
"Accounts Receivable, Net",45.0,112155000.0,1217404000.0,652531755.555556,254617726.08695
Other Short Term Assets,45.0,17455000.0,307284000.0,187020955.555556,69009633.303802
Prepaid Expenses,45.0,17455000.0,268564000.0,184567622.222222,66004462.881236
Total Current Assets,45.0,554466000.0,9863742000.0,5861436133.333333,2185124565.914291
"Property, Plant & Equipment, Net",45.0,185574000.0,2175290000.0,988418533.333333,521377813.188792
Other Long Term Assets,45.0,91528000.0,4130416000.0,2144113755.555556,1314287733.024469
Intangible Assets,45.0,3753000.0,156352000.0,75621044.444444,34040379.112671
Goodwill,45.0,68813000.0,1325200000.0,1076835688.888889,322891978.343435
Misc. Long Term Assets,45.0,17795000.0,1776435000.0,474826266.666667,558121302.888433
Total Noncurrent Assets,45.0,277102000.0,6305706000.0,3132532288.888889,1775845372.234659
Total Assets,45.0,831568000.0,15323225000.0,8993968422.222221,3858440520.417999
Payables & Accruals,45.0,61043000.0,1896680000.0,558989133.333333,331623723.507642
Accounts Payable,45.0,8432000.0,325446000.0,130167911.111111,69976114.026282
Other Payables & Accruals,45.0,52611000.0,1688768000.0,428821222.222222,279123730.278828
Total Current Liabilities,45.0,109879000.0,2257919000.0,885851288.888889,610966495.65603
Misc. Long Term Liabilities,45.0,97325000.0,1382694000.0,428889133.333333,397185737.548431
Other Long Term Liabilities,45.0,97325000.0,1382694000.0,428889133.333333,397185737.548431
Total Noncurrent Liabilities,45.0,97325000.0,6629543000.0,2489958533.333333,1681029090.795759
Total Liabilities,45.0,207204000.0,7646806000.0,3375809822.222222,2136788985.099204
Common Stock,45.0,1000.0,4000.0,3622.222222,613.814041
Share Capital & Additional Paid-In Capital,45.0,101788000.0,9249960000.0,7144640555.555555,1857273154.6501
Other Equity,45.0,-200456000.0,199000.0,-59589488.888889,44899611.586507
Equity Before Minority Interest,45.0,624364000.0,8795627000.0,5618158600.0,1975686102.154048
Additional Paid in Capital,45.0,101787000.0,9249956000.0,7144636933.333333,1857272603.977113
Retained Earnings,45.0,-2762808000.0,11586000.0,-1485458377.777778,834196698.514349
Total Equity,45.0,624364000.0,8795627000.0,5618158600.0,1975686102.154048
Total Liabilities & Equity,45.0,831568000.0,15323225000.0,8993968422.222221,3858440520.417999
Short Term Debt,40.0,7248000.0,969241000.0,294790300.0,382868074.992244
Long Term Debt,40.0,1293604000.0,5246849000.0,2318703075.0,1171135500.68613

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
35,TWTR,30388,simfin,us,A,True,USD,2012,Q4,2012-12-31,2013-03-06,2014-03-06,117401000,117401000,424856000,203328000,221528000,112155000,112155000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,17455000,17455000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,554466000,185574000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,91528000,3753000,68813000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18962000,277102000,831568000,61043000,8432000,<NA>,<NA>,52611000,48836000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,109879000,<NA>,<NA>,<NA>,97325000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,97325000,97325000,207204000,872536000,101788000,1000,101787000,<NA>,<NA>,-349303000,-657000,624364000,<NA>,624364000,831568000
28,TWTR,30388,simfin,us,A,True,USD,2013,Q4,2013-12-31,2014-03-06,2015-03-02,189510000,189510000,2234054000,841010000,1393044000,247328000,247328000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,93297000,93297000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2574679000,332662000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,458899000,77627000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17795000,791561000,3366240000,138304000,27994000,<NA>,<NA>,110310000,87126000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,225430000,<NA>,<NA>,<NA>,190804000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,190804000,190804000,416234000,<NA>,3944955000,3000,3944952000,<NA>,<NA>,-994626000,-323000,2950006000,<NA>,2950006000,3366240000
32,TWTR,30388,simfin,us,Q,True,USD,2013,Q4,2013-12-31,2014-03-06,2015-03-02,364661000,364661000,2234054000,841010000,1393044000,247328000,247328000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,93297000,93297000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2574679000,332662000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,458899000,77627000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17795000,791561000,3366240000,138304000,27994000,<NA>,<NA>,110310000,87126000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,225430000,<NA>,<NA>,<NA>,190804000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,190804000,190804000,416234000,<NA>,3944955000,3000,3944952000,<NA>,<NA>,-994626000,-323000,2950006000,<NA>,2950006000,3366240000
72,TWTR,30388,simfin,us,Q,True,USD,2014,Q1,2014-03-31,2014-05-08,2014-05-08,570205000,570205000,2176595000,960755000,1215840000,237860000,237860000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,90925000,90925000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2505380000,383272000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,467557000,71451000,363477000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32629000,850829000,3356209000,170998000,19714000,<NA>,<NA>,151284000,90253000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,261251000,<NA>,<NA>,<NA>,158112000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,158112000,158112000,419363000,<NA>,4064130000,3000,4064127000,<NA>,<NA>,-1126988000,-296000,2936846000,<NA>,2936846000,3356209000
68,TWTR,30388,simfin,us,Q,True,USD,2014,Q2,2014-06-30,2014-08-11,2014-08-11,595607000,595607000,2097031000,844976000,1252055000,287082000,287082000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,79773000,79773000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2463886000,467634000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,653297000,105497000,514601000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33199000,1120931000,3584817000,270631000,23084000,<NA>,<NA>,247547000,99744000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,370375000,<NA>,<NA>,<NA>,167849000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,167849000,167849000,538224000,<NA>,4318024000,3000,4318021000,<NA>,<NA>,-1271630000,199000,3046593000,<NA>,3046593000,3584817000
34,TWTR,30388,simfin,us,Q,True,USD,2021,Q3,2021-09-30,2021-10-27,2021-10-27,799370000,865030000,7411312000,3473865000,3937447000,1014208000,1014208000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,223714000,194914000,<NA>,28800000,<NA>,<NA>,<NA>,<NA>,8649234000,2053480000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3886631000,46702000,1293826000,<NA>,<NA>,1133816000,<NA>,<NA>,<NA>,<NA>,1412287000,5940111000,14589345000,1896680000,207912000,<NA>,<NA>,1688768000,<NA>,<NA>,<NA>,<NA>,218301000,<NA>,<NA>,<NA>,<NA>,218301000,2114981000,4250678000,<NA>,<NA>,1051055000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1051055000,5301733000,7416714000,<NA>,8468712000,4000,8468708000,<NA>,-5291000,-1183996000,-106794000,7172631000,<NA>,7172631000,14589345000
57,TWTR,30388,simfin,us,Q,True,USD,2021,Q4,2021-12-31,2022-02-16,2022-07-26,799370000,865030000,6393682000,2186549000,4207133000,1217404000,1217404000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,307284000,266484000,<NA>,40800000,<NA>,<NA>,<NA>,<NA>,7918370000,2082160000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4058986000,69324000,1301520000,<NA>,<NA>,1148573000,<NA>,<NA>,<NA>,<NA>,1539569000,6141146000,14059516000,1121521000,203171000,<NA>,<NA>,918350000,<NA>,<NA>,<NA>,<NA>,222346000,<NA>,<NA>,<NA>,<NA>,222346000,1343867000,4253019000,<NA>,<NA>,1155431000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1155431000,5408450000,6752317000,<NA>,8432116000,4000,8432112000,<NA>,-5295000,-1002302000,-117320000,7307199000,<NA>,7307199000,14059516000
60,TWTR,30388,simfin,us,A,True,USD,2021,Q4,2021-12-31,2022-02-16,2022-07-26,799370000,865030000,6393682000,2186549000,4207133000,1217404000,1217404000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,307284000,266484000,<NA>,40800000,<NA>,<NA>,<NA>,<NA>,7918370000,2082160000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4058986000,69324000,1301520000,<NA>,<NA>,1148573000,<NA>,<NA>,<NA>,<NA>,1539569000,6141146000,14059516000,1121521000,203171000,<NA>,<NA>,918350000,<NA>,<NA>,<NA>,<NA>,222346000,<NA>,<NA>,<NA>,<NA>,222346000,1343867000,4253019000,<NA>,<NA>,1155431000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1155431000,5408450000,6752317000,<NA>,8432116000,4000,8432112000,<NA>,-5295000,-1002302000,-117320000,7307199000,<NA>,7307199000,14059516000
67,TWTR,30388,simfin,us,Q,True,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,6261953000,2283308000,3978645000,948142000,948142000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,265973000,265973000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7476068000,2150581000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3924308000,59725000,1298462000,<NA>,<NA>,941883000,<NA>,<NA>,<NA>,<NA>,1624238000,6074889000,13550957000,928302000,189524000,<NA>,<NA>,738778000,<NA>,<NA>,<NA>,<NA>,208405000,<NA>,<NA>,<NA>,<NA>,208405000,1136707000,5244181000,<NA>,<NA>,1265153000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1265153000,6509334000,7646041000,<NA>,6677298000,4000,6677294000,<NA>,<NA>,-616860000,-155522000,5904916000,<NA>,5904916000,13550957000
37,TWTR,30388,simfin,us,Q,True,USD,2022,Q2,2022-06-30,2022-07-26,2022-07-26,766837000,766837000,6120743000,2680596000,3440147000,972591000,972591000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,180247000,180247000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7273581000,2175290000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4130416000,52643000,1303438000,<NA>,<NA>,997900000,<NA>,<NA>,<NA>,<NA>,1776435000,6305706000,13579287000,829281000,153092000,<NA>,<NA>,676189000,<NA>,<NA>,<NA>,<NA>,187982000,<NA>,<NA>,<NA>,<NA>,187982000,1017263000,5246849000,<NA>,<NA>,1382694000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1382694000,6629543000,7646806000,<NA>,7096603000,4000,7096599000,<NA>,<NA>,-963666000,-200456000,5932481000,<NA>,5932481000,13579287000

## cashflow

### cashflow (as-reported)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
Net Income/Starting Line,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Depreciation & Amortization,45.0,33224000.0,544848000.0,156675400.0,127976550.321001
Non-Cash Items,45.0,-928236000.0,1657914000.0,184334955.555556,429081631.918945
Change in Working Capital,45.0,-1002147000.0,850569000.0,-19367022.222222,214472878.205814
Change in Accounts Receivable,45.0,-285851000.0,190737000.0,-44796155.555556,110027485.016029
Change in Accounts Payable,45.0,-52595000.0,85866000.0,4695688.888889,24889747.923065
Change in Other,45.0,-792539000.0,901825000.0,20733444.444444,200276449.059516
Net Cash from Operating Activities,45.0,-528442000.0,1339711000.0,284042266.666667,335458507.556882
Change in Fixed Assets & Intangibles,45.0,-1003084000.0,889308000.0,-153835800.0,258100031.414408
Acquisition of Fixed Assets & Intangibles,45.0,-1011546000.0,-29116000.0,-181084244.444444,205056212.694244
Effect of Foreign Exchange Rates,45.0,-18748000.0,10849000.0,-2229355.555556,6978554.344156
Net Change in Long Term Investment,45.0,-1542702000.0,1207974000.0,-162607844.444444,545955749.86265
Decrease in Long Term Investment,45.0,63154000.0,5646992000.0,1434673666.666667,1302007899.614179
Increase in Long Term Investment,45.0,-6284307000.0,-442070000.0,-1597281511.111111,1402688049.279208
Cash from (Repayment of) Debt,45.0,-954000000.0,1667968000.0,182354844.444444,561446237.772997
Net Cash from Investing Activities,45.0,-2055513000.0,1064901000.0,-354038333.333333,611046014.271467
Increase in Capital Stock,45.0,31000.0,2027258000.0,108910600.0,418115632.094727
Cash from (Repurchase of) Equity,45.0,-2077693000.0,2027258000.0,10479422.222222,554806913.509658
Net Change in Cash,45.0,-1285860000.0,2260202000.0,99326133.333333,634617759.492444
Net Cash Before FX,45.0,-1281171000.0,2268220000.0,101555488.888889,636132687.984327
Net Cash from Financing Activities,45.0,-1129621000.0,1985606000.0,171551555.555556,696130695.959346
Net Cash Before Disc. Operations and FX,45.0,-1281171000.0,2268220000.0,101555488.888889,636132687.984327
Other Financing Activities,44.0,-257785000.0,4776000.0,-21766409.090909,49746619.157448
Other Investing Activities,44.0,-119565000.0,11368000.0,-9894090.909091,20490823.05975
Net Cash from Acquisitions & Divestitures,39.0,-166584000.0,2627000.0,-32215923.076923,46548734.781486
Disposition of Fixed Assets & Intangibles,27.0,0.0,1052482000.0,45414074.074074,201496787.370634

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
43,TWTR,30388,simfin,us,A,False,USD,2012,FY,2012-12-31,2013-03-02,2015-03-02,117401000,117401000,-79399000,<NA>,<NA>,<NA>,72506000,32304000,<NA>,<NA>,<NA>,-53346000,-73898000,<NA>,2931000,17621000,<NA>,-27935000,-50599000,<NA>,<NA>,<NA>,-50599000,<NA>,<NA>,<NA>,104711000,647349000,-542638000,-1526000,<NA>,<NA>,<NA>,<NA>,-3143000,<NA>,49443000,<NA>,-39436000,<NA>,<NA>,<NA>,<NA>,2312000,2312000,<NA>,<NA>,<NA>,-37124000,-15616000,<NA>,-15616000,-52000,-15668000
37,TWTR,30388,simfin,us,A,False,USD,2013,FY,2013-12-31,2014-03-06,2014-03-06,189510000,189510000,-645323000,<NA>,<NA>,<NA>,110894000,597183000,<NA>,<NA>,<NA>,-61356000,-112060000,<NA>,7957000,42747000,<NA>,1398000,-75744000,<NA>,<NA>,<NA>,-75744000,<NA>,<NA>,<NA>,-1175403000,398086000,-1573489000,-44072000,<NA>,<NA>,<NA>,<NA>,-10847000,<NA>,-1306066000,<NA>,-70445000,<NA>,<NA>,<NA>,<NA>,2027258000,2027258000,<NA>,-14637000,<NA>,1942176000,637508000,<NA>,637508000,174000,637682000
1,TWTR,30388,simfin,us,Q,False,USD,2013,Q4,2013-12-31,2014-02-06,2014-03-06,364661000,364661000,-511471000,<NA>,<NA>,<NA>,33224000,515057000,<NA>,<NA>,<NA>,-39678000,-77798000,<NA>,16249000,21871000,<NA>,-2868000,-29116000,<NA>,<NA>,<NA>,-29116000,<NA>,<NA>,<NA>,-1228761000,63154000,-1291915000,-36000000,<NA>,<NA>,<NA>,<NA>,-3306000,<NA>,-1297183000,<NA>,-21203000,<NA>,<NA>,<NA>,<NA>,2020321000,2020321000,<NA>,-13512000,<NA>,1985606000,685555000,<NA>,685555000,-249000,685306000
54,TWTR,30388,simfin,us,A,False,USD,2014,FY,2014-12-31,2015-03-02,2015-03-02,604990000,604990000,-577820000,<NA>,<NA>,<NA>,208165000,653426000,<NA>,<NA>,<NA>,-201975000,-177583000,<NA>,18059000,-42451000,<NA>,81796000,-201630000,<NA>,<NA>,<NA>,-201630000,<NA>,<NA>,<NA>,-719423000,2217610000,-2937033000,-165177000,<NA>,<NA>,<NA>,<NA>,-11042000,<NA>,-1097272000,<NA>,1667968000,<NA>,<NA>,<NA>,<NA>,71060000,71060000,<NA>,-47306000,<NA>,1691722000,676246000,<NA>,676246000,-6532000,669714000
14,TWTR,30388,simfin,us,Q,False,USD,2014,Q1,2014-03-31,2014-05-08,2014-05-08,570205000,570205000,-132362000,<NA>,<NA>,<NA>,39951000,129412000,<NA>,<NA>,<NA>,5682000,8861000,<NA>,-303000,-2876000,<NA>,42683000,-49620000,<NA>,<NA>,<NA>,-49620000,<NA>,<NA>,<NA>,174721000,645471000,-470750000,<NA>,<NA>,<NA>,<NA>,<NA>,-12138000,<NA>,112963000,<NA>,-21521000,<NA>,<NA>,<NA>,<NA>,1350000,1350000,<NA>,-16302000,<NA>,-36473000,119173000,<NA>,119173000,572000,119745000
49,TWTR,30388,simfin,us,Q,False,USD,2021,Q2,2021-06-30,2021-07-27,2021-04-30,795633000,872187000,65649000,<NA>,<NA>,<NA>,134812000,125688000,<NA>,<NA>,<NA>,55818000,-100328000,<NA>,27626000,128520000,<NA>,381967000,-276193000,3002000,<NA>,<NA>,-279195000,<NA>,<NA>,<NA>,92771000,888267000,-795496000,-14559000,<NA>,<NA>,<NA>,<NA>,-11800000,<NA>,-209781000,<NA>,214034000,<NA>,<NA>,<NA>,<NA>,-294253000,39559000,-333812000,-218962000,<NA>,-299181000,-126995000,<NA>,-126995000,4019000,-122976000
85,TWTR,30388,simfin,us,Q,False,USD,2021,Q3,2021-09-30,2021-10-27,2021-07-27,799370000,865030000,-536757000,<NA>,<NA>,<NA>,133448000,-58280000,<NA>,<NA>,<NA>,850569000,-69139000,<NA>,17883000,901825000,<NA>,388980000,-409151000,2076000,<NA>,<NA>,-411227000,<NA>,<NA>,<NA>,531527000,1152537000,-621010000,0,<NA>,<NA>,<NA>,<NA>,-29300000,<NA>,93076000,<NA>,-954000000,<NA>,<NA>,<NA>,<NA>,-169406000,51000,-169457000,-6215000,<NA>,-1129621000,-647565000,<NA>,-647565000,-4392000,-651957000
50,TWTR,30388,simfin,us,Q,False,USD,2021,Q4,2021-12-31,2022-02-16,2021-10-27,799370000,865030000,181694000,<NA>,<NA>,<NA>,145536000,146475000,<NA>,<NA>,<NA>,-1002147000,-209776000,<NA>,168000,-792539000,<NA>,-528442000,-138394000,1549000,<NA>,<NA>,-139943000,<NA>,<NA>,<NA>,-303691000,654526000,-958217000,-9765000,<NA>,<NA>,<NA>,<NA>,-59180000,<NA>,-511030000,<NA>,0,<NA>,<NA>,<NA>,<NA>,-236429000,29280000,-265709000,-5270000,<NA>,-241699000,-1281171000,<NA>,-1281171000,-4689000,-1285860000
42,TWTR,30388,simfin,us,Q,False,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,513286000,<NA>,<NA>,<NA>,160283000,-597221000,<NA>,<NA>,<NA>,49743000,190737000,<NA>,-35610000,-105384000,<NA>,126091000,889308000,1052482000,<NA>,<NA>,-163174000,<NA>,<NA>,<NA>,182093000,1287944000,-1105851000,<NA>,<NA>,<NA>,<NA>,<NA>,-6500000,<NA>,1064901000,<NA>,1000000000,<NA>,<NA>,<NA>,<NA>,-2077693000,66000,-2077759000,-15460000,<NA>,-1093153000,97839000,<NA>,97839000,-814000,97025000
45,TWTR,30388,simfin,us,Q,False,USD,2022,Q2,2022-06-30,2022-07-26,2022-05-02,766837000,766837000,-270007000,<NA>,<NA>,<NA>,173288000,195392000,<NA>,<NA>,<NA>,-68977000,37842000,<NA>,-52595000,-54224000,<NA>,29696000,-153646000,850000,<NA>,<NA>,-154496000,<NA>,<NA>,<NA>,524329000,1068944000,-544615000,-9379000,<NA>,<NA>,<NA>,<NA>,-24000000,<NA>,337304000,<NA>,0,<NA>,<NA>,<NA>,<NA>,49658000,49658000,0,-8951000,<NA>,40707000,407707000,<NA>,407707000,-10838000,396869000

### cashflow (restated)

*Fiscal Year 2012 .. 2022  |  A=10 Q=35  |  USD  |  45 rows*

,count,min,max,mean,std
Shares (Basic),45.0,117401000.0,799370000.0,695622000.0,144142472.438178
Shares (Diluted),45.0,117401000.0,872187000.0,708545511.111111,154170410.631846
Net Income/Starting Line,45.0,-1378005000.0,1465659000.0,-37601066.666667,505587855.097653
Depreciation & Amortization,45.0,33224000.0,544848000.0,156675400.0,127976550.321001
Non-Cash Items,45.0,-894495000.0,1657914000.0,177673622.222222,430365163.254748
Change in Working Capital,45.0,-1002147000.0,850569000.0,-12705688.888889,212488818.147281
Change in Accounts Receivable,45.0,-285851000.0,190737000.0,-44796155.555556,110027485.016029
Change in Accounts Payable,45.0,-52595000.0,85866000.0,4695688.888889,24889747.923065
Change in Other,45.0,-792539000.0,901825000.0,27394777.777778,198452278.787838
Net Cash from Operating Activities,45.0,-528442000.0,1339711000.0,284042266.666667,335458507.556882
Change in Fixed Assets & Intangibles,45.0,-1003084000.0,889308000.0,-154359400.0,258477676.588363
Acquisition of Fixed Assets & Intangibles,45.0,-1011546000.0,-29116000.0,-181084244.444444,205055530.772781
Effect of Foreign Exchange Rates,45.0,-18748000.0,10849000.0,-2220733.333333,6972540.23881
Net Change in Long Term Investment,45.0,-1546077000.0,1207974000.0,-165031755.555556,548316856.383828
Decrease in Long Term Investment,45.0,63154000.0,5646992000.0,1434673666.666667,1302007899.614179
Increase in Long Term Investment,45.0,-6284307000.0,-442070000.0,-1599705422.222222,1406494578.716639
Cash from (Repayment of) Debt,45.0,-954000000.0,1667968000.0,189333866.666667,575937854.621865
Net Cash from Investing Activities,45.0,-2055513000.0,1064901000.0,-353986511.111111,610959610.85863
Increase in Capital Stock,45.0,31000.0,2027258000.0,108919933.333333,418113616.57511
Cash from (Repurchase of) Equity,45.0,-2077693000.0,2027258000.0,10488755.555556,554807088.078663
Net Change in Cash,45.0,-1285860000.0,2260202000.0,99386577.777778,634518132.2592
Net Cash Before FX,45.0,-1281171000.0,2268220000.0,101607311.111111,636037307.629678
Net Cash from Financing Activities,45.0,-1129621000.0,1985606000.0,171551555.555556,696130695.959346
Net Cash Before Disc. Operations and FX,45.0,-1281171000.0,2268220000.0,101607311.111111,636037307.629678
Other Financing Activities,44.0,-257785000.0,4776000.0,-28913590.909091,56392424.615912
Other Investing Activities,44.0,-119565000.0,11368000.0,-10541954.545455,21630465.344535
Net Cash from Acquisitions & Divestitures,38.0,-166584000.0,41801000.0,-28761710.526316,47434180.129265
Disposition of Fixed Assets & Intangibles,27.0,0.0,1052482000.0,44541407.407407,201654104.549056

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
89,TWTR,30388,simfin,us,A,True,USD,2012,FY,2012-12-31,2013-03-02,2015-03-02,117401000,117401000,-79399000,<NA>,<NA>,<NA>,72506000,32304000,<NA>,<NA>,<NA>,-53346000,-73898000,<NA>,2931000,17621000,<NA>,-27935000,-50599000,<NA>,<NA>,<NA>,-50599000,<NA>,<NA>,<NA>,104711000,647349000,-542638000,-1526000,<NA>,<NA>,<NA>,<NA>,-3143000,<NA>,49443000,<NA>,-39436000,<NA>,<NA>,<NA>,<NA>,2312000,2312000,<NA>,<NA>,<NA>,-37124000,-15616000,<NA>,-15616000,-52000,-15668000
29,TWTR,30388,simfin,us,A,True,USD,2013,FY,2013-12-31,2014-03-06,2016-02-29,189510000,189510000,-645323000,<NA>,<NA>,<NA>,110894000,597183000,<NA>,<NA>,<NA>,-61356000,-112060000,<NA>,7957000,42747000,<NA>,1398000,-75744000,<NA>,<NA>,<NA>,-75744000,<NA>,<NA>,<NA>,-1175403000,398086000,-1573489000,-8072000,<NA>,<NA>,<NA>,<NA>,-46847000,<NA>,-1306066000,<NA>,-70445000,<NA>,<NA>,<NA>,<NA>,2027258000,2027258000,<NA>,-14637000,<NA>,1942176000,637508000,<NA>,637508000,174000,637682000
72,TWTR,30388,simfin,us,Q,True,USD,2013,Q4,2013-12-31,2014-02-06,2016-02-29,364661000,364661000,-511471000,<NA>,<NA>,<NA>,33224000,515057000,<NA>,<NA>,<NA>,-39678000,-77798000,<NA>,16249000,21871000,<NA>,-2868000,-29116000,<NA>,<NA>,<NA>,-29116000,<NA>,<NA>,<NA>,-1228761000,63154000,-1291915000,0,<NA>,<NA>,<NA>,<NA>,-39306000,<NA>,-1297183000,<NA>,-21203000,<NA>,<NA>,<NA>,<NA>,2020321000,2020321000,<NA>,-13512000,<NA>,1985606000,685555000,<NA>,685555000,-249000,685306000
30,TWTR,30388,simfin,us,A,True,USD,2014,FY,2014-12-31,2015-03-02,2017-02-27,604990000,604990000,-577820000,<NA>,<NA>,<NA>,208165000,653426000,<NA>,<NA>,<NA>,-201975000,-177583000,<NA>,18059000,-42451000,<NA>,81796000,-201630000,<NA>,<NA>,<NA>,-201630000,<NA>,<NA>,<NA>,-719423000,2217610000,-2937033000,-163477000,<NA>,<NA>,<NA>,<NA>,-12742000,<NA>,-1097272000,<NA>,1667968000,<NA>,<NA>,<NA>,<NA>,71060000,71060000,<NA>,-47306000,<NA>,1691722000,676246000,<NA>,676246000,-6532000,669714000
0,TWTR,30388,simfin,us,Q,True,USD,2014,Q1,2014-03-31,2014-05-08,2015-05-11,570205000,570205000,-132362000,<NA>,<NA>,<NA>,39951000,129412000,<NA>,<NA>,<NA>,5682000,8861000,<NA>,-303000,-2876000,<NA>,42683000,-49620000,<NA>,<NA>,<NA>,-49620000,<NA>,<NA>,<NA>,174721000,645471000,-470750000,<NA>,<NA>,<NA>,<NA>,<NA>,-12138000,<NA>,112963000,<NA>,-21521000,<NA>,<NA>,<NA>,<NA>,1350000,1350000,<NA>,-16302000,<NA>,-36473000,119173000,<NA>,119173000,572000,119745000
12,TWTR,30388,simfin,us,Q,True,USD,2021,Q2,2021-06-30,2021-07-27,2022-05-02,795633000,872187000,65649000,<NA>,<NA>,<NA>,134812000,125688000,<NA>,<NA>,<NA>,55818000,-100328000,<NA>,27626000,128520000,<NA>,381967000,-276193000,3002000,<NA>,<NA>,-279195000,<NA>,<NA>,<NA>,92771000,888267000,-795496000,-14559000,<NA>,<NA>,<NA>,<NA>,-11800000,<NA>,-209781000,<NA>,0,<NA>,<NA>,<NA>,<NA>,-294253000,39559000,-333812000,-4928000,<NA>,-299181000,-126995000,<NA>,-126995000,4019000,-122976000
6,TWTR,30388,simfin,us,Q,True,USD,2021,Q3,2021-09-30,2021-10-27,2022-07-26,799370000,865030000,-536757000,<NA>,<NA>,<NA>,133448000,-58280000,<NA>,<NA>,<NA>,850569000,-69139000,<NA>,17883000,901825000,<NA>,388980000,-409151000,2076000,<NA>,<NA>,-411227000,<NA>,<NA>,<NA>,531527000,1152537000,-621010000,0,<NA>,<NA>,<NA>,<NA>,-29300000,<NA>,93076000,<NA>,-954000000,<NA>,<NA>,<NA>,<NA>,-169406000,51000,-169457000,-6215000,<NA>,-1129621000,-647565000,<NA>,-647565000,-4392000,-651957000
13,TWTR,30388,simfin,us,Q,True,USD,2021,Q4,2021-12-31,2022-02-16,2021-10-27,799370000,865030000,181694000,<NA>,<NA>,<NA>,145536000,146475000,<NA>,<NA>,<NA>,-1002147000,-209776000,<NA>,168000,-792539000,<NA>,-528442000,-138394000,1549000,<NA>,<NA>,-139943000,<NA>,<NA>,<NA>,-303691000,654526000,-958217000,-9765000,<NA>,<NA>,<NA>,<NA>,-59180000,<NA>,-511030000,<NA>,0,<NA>,<NA>,<NA>,<NA>,-236429000,29280000,-265709000,-5270000,<NA>,-241699000,-1281171000,<NA>,-1281171000,-4689000,-1285860000
53,TWTR,30388,simfin,us,Q,True,USD,2022,Q1,2022-03-31,2022-05-02,2022-05-02,799370000,865030000,513286000,<NA>,<NA>,<NA>,160283000,-597221000,<NA>,<NA>,<NA>,49743000,190737000,<NA>,-35610000,-105384000,<NA>,126091000,889308000,1052482000,<NA>,<NA>,-163174000,<NA>,<NA>,<NA>,182093000,1287944000,-1105851000,<NA>,<NA>,<NA>,<NA>,<NA>,-6500000,<NA>,1064901000,<NA>,1000000000,<NA>,<NA>,<NA>,<NA>,-2077693000,66000,-2077759000,-15460000,<NA>,-1093153000,97839000,<NA>,97839000,-814000,97025000
71,TWTR,30388,simfin,us,Q,True,USD,2022,Q2,2022-06-30,2022-07-26,2022-05-02,766837000,766837000,-270007000,<NA>,<NA>,<NA>,173288000,195392000,<NA>,<NA>,<NA>,-68977000,37842000,<NA>,-52595000,-54224000,<NA>,29696000,-153646000,850000,<NA>,<NA>,-154496000,<NA>,<NA>,<NA>,524329000,1068944000,-544615000,-9379000,<NA>,<NA>,<NA>,<NA>,-24000000,<NA>,337304000,<NA>,0,<NA>,<NA>,<NA>,<NA>,49658000,49658000,0,-8951000,<NA>,40707000,407707000,<NA>,407707000,-10838000,396869000

## market_data

*no rows*