# investalyze — ticker profile

Everything we hold for one ticker, table by table: a metadata summary plus a head/tail
preview of the rows. Set `TICKER` (and optionally `MIN_FILL`) and run all. Helpers live
in `helpers.py`.

Probes every table, so it works for both stocks (prices + dividends/splits +
income/balance/cashflow + companies) and non-equity tickers (market_data).

In [1]:
%load_ext autoreload
%autoreload 2
from helpers import connect_readonly, show_ticker_profile

con = connect_readonly()

In [3]:
TICKER = 'MSFT'    # the ticker to profile
MIN_FILL = 0.5     # fundamentals: keep stat columns filled in >= this fraction of rows

show_ticker_profile(con, TICKER, MIN_FILL)

# MSFT

## companies

                                                                       0
Ticker                                                              MSFT
SrcId                                                              59265
Src                                                               simfin
Market                                                                us
Industry                                            Application Software
Sector                                                        Technology
CompanyName                                               MICROSOFT CORP
IndustryId                                                        101003
ISIN                                                        US5949181045
FinancialYearEndMonth                                                  6
NumberEmployees                                                   166475
BusinessSummary        Microsoft Corp is a technology company. It dev...
CIK                                                               789019
MainCurrency                                                         USD

## company_profile

                                                                       0
Ticker                                                              MSFT
Src                                                                yahoo
Address1                                               One Microsoft Way
City                                                             Redmond
State                                                                 WA
Zip                                                           98052-6399
Country                                                    United States
Website                                        https://www.microsoft.com
Industry                                       Software - Infrastructure
Sector                                                        Technology
BusinessSummary        Microsoft Corporation develops and supports so...
FullTimeEmployees                                                 228000
AuditRisk                                                              9
BoardRisk                                                              8
CompensationRisk                                                       5
ShareholderRightsRisk                                                  2
OverallRisk                                                            5
IRWebsite                 http://www.microsoft.com/investor/default.aspx
FetchedOn                                            2026-06-23 00:00:00

## company_officers

,Ticker,Src,Name,Title,Age,YearBorn,FiscalYear,TotalPay,ExercisedValue,UnexercisedValue
0,MSFT,yahoo,Mr. Judson B. Althoff,Executive VP & CEO of Commercial Business,51.0,1974.0,2025.0,4490115.0,0,0
1,MSFT,yahoo,Mr. Takeshi Numoto,Executive VP & Chief Marketing Officer,53.0,1972.0,2025.0,2871250.0,0,0
2,MSFT,yahoo,Ms. Carolina Dybeck Happe,Executive VP & COO,53.0,1972.0,2025.0,NaN,0,0
3,MSFT,yahoo,Ms. Alice L. Jolla,Corporate VP & Chief Accounting Officer,59.0,1966.0,2025.0,NaN,0,0
4,MSFT,yahoo,Mr. Jonathan M. Palmer,Corporate Vice President & Chief Legal Officer,NaN,NaN,2025.0,NaN,0,0
5,MSFT,yahoo,Mr. Matthew Kerner,CTO & Corporate VP of Worldwide Sales and Solu...,NaN,NaN,2025.0,NaN,0,0
6,MSFT,yahoo,Mr. Satya Nadella,Chairman & CEO,58.0,1967.0,2025.0,12251294.0,0,0
7,MSFT,yahoo,Mr. Bradford L. Smith LCA,President & Vice Chairman,66.0,1959.0,2025.0,4532750.0,0,0
8,MSFT,yahoo,Jonathan Neilson,Vice President of Investor Relations,NaN,NaN,2025.0,NaN,0,0
9,MSFT,yahoo,Ms. Amy E. Hood,Executive VP & CFO,53.0,1972.0,2025.0,4444191.0,0,0

## prices

*1986-03-13 00:00:00 .. 2026-06-22 00:00:00  |  10146 rows*

      count           min           max          mean           std
O   10146.0  8.854200e-02  5.552300e+02  7.635344e+01  1.200827e+02
H   10146.0  9.201400e-02  5.554500e+02  7.710870e+01  1.211443e+02
L   10146.0  8.854200e-02  5.407700e+02  7.556345e+01  1.189217e+02
C   10146.0  9.027800e-02  5.420700e+02  7.636173e+01  1.200742e+02
V   10146.0  2.304000e+06  1.031789e+09  5.530419e+07  3.791522e+07
AC  10146.0  5.490236e-02  5.386585e+02  7.007999e+01  1.195629e+02

,Ticker,Date,O,H,L,C,V,AC
5154,MSFT,1986-03-13,0.088542,0.101563,0.088542,0.097222,1031788800,0.059125
3220,MSFT,1986-03-14,0.097222,0.102431,0.097222,0.100694,308160000,0.061237
4465,MSFT,1986-03-17,0.100694,0.103299,0.100694,0.102431,133171200,0.062293
625,MSFT,1986-03-18,0.102431,0.103299,0.098958,0.099826,67766400,0.060709
8899,MSFT,1986-03-19,0.099826,0.100694,0.097222,0.098090,47894400,0.059653
4464,MSFT,2026-06-15,396.799988,401.750000,392.850006,399.760010,32266400,399.760010
7621,MSFT,2026-06-16,395.790009,396.839996,390.690002,393.829987,31506800,393.829987
1915,MSFT,2026-06-17,390.250000,390.369995,377.320007,378.910004,41987800,378.910004
624,MSFT,2026-06-18,377.915009,381.369995,373.279999,379.399994,59714157,379.399994
10145,MSFT,2026-06-22,375.559998,381.630005,367.070007,367.339996,44081827,367.339996

## dividends

*2003-02-19 00:00:00 .. 2026-05-21 00:00:00  |  90 rows*

          count   min   max   mean       std
Dividend   90.0  0.08  3.08  0.396  0.377864

   Ticker       Date  Dividend
80   MSFT 2003-02-19      0.08
62   MSFT 2003-10-15      0.16
63   MSFT 2004-08-23      0.08
26   MSFT 2004-11-15      3.08
81   MSFT 2005-02-15      0.08
23   MSFT 2025-05-15      0.83
74   MSFT 2025-08-21      0.83
45   MSFT 2025-11-20      0.91
10   MSFT 2026-02-19      0.91
52   MSFT 2026-05-21      0.91

## splits

*1987-09-21 00:00:00 .. 2003-02-18 00:00:00  |  9 rows*

       count  min  max      mean       std
Ratio    9.0  1.5  2.0  1.888889  0.220479

  Ticker       Date  Ratio
6   MSFT 1987-09-21    2.0
2   MSFT 1990-04-16    2.0
0   MSFT 1991-06-27    1.5
8   MSFT 1992-06-15    1.5
5   MSFT 1994-05-23    2.0
3   MSFT 1996-12-09    2.0
7   MSFT 1998-02-23    2.0
1   MSFT 1999-03-29    2.0
4   MSFT 2003-02-18    2.0

## income

### income (as-reported)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
Revenue,122.0,7245000000.0,281724000000.0,42657139344.262299,46300023846.327614
Cost of Revenue,122.0,-87831000000.0,-1199000000.0,-12583967213.114754,14936947299.465689
Gross Profit,122.0,5850000000.0,193893000000.0,30073172131.147541,31610173294.327236
Operating Expenses,122.0,-65365000000.0,-2497000000.0,-13614319672.131147,12221716707.44869
"Selling, General & Administrative",122.0,-32877000000.0,-1403000000.0,-8049163934.426229,6762814376.201153
Research & Development,122.0,-32488000000.0,-1066000000.0,-5565155737.704918,5632345557.55216
Non-Operating Income (Loss),122.0,-4901000000.0,9971000000.0,260540983.606557,1238086180.711361
Operating Income (Loss),122.0,1278000000.0,128528000000.0,16458852459.016394,20017717621.02042
Pretax Income (Loss),122.0,-1756000000.0,123627000000.0,16418295081.967213,19842767694.552483
"Pretax Income (Loss), Adj.",122.0,2257000000.0,123627000000.0,16719393442.622952,19797442434.184086
Net Income,122.0,-6302000000.0,101832000000.0,13071122950.819672,16602416518.114359
Income (Loss) Incl. Minority Interest,122.0,-6302000000.0,101832000000.0,13071122950.819672,16602416518.114359
"Income Tax (Expense) Benefit, Net",122.0,-21795000000.0,968000000.0,-3344098360.655738,3912732507.621194
Income (Loss) from Continuing Operations,122.0,-6302000000.0,101832000000.0,13074196721.311476,16601382490.793018
Net Income (Common),122.0,-6302000000.0,101832000000.0,13071122950.819672,16602416518.114359
Selling & Marketing,106.0,-21825000000.0,-1220000000.0,-5651858490.566038,4651126920.156384
General & Administrative,106.0,-5900000000.0,-183000000.0,-1755990566.037736,1410633606.341039
Other Non-Operating Income (Loss),88.0,-4901000000.0,9971000000.0,101875000.0,1359537309.837093

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
105,MSFT,59265,simfin,us,A,False,USD,2001,FY,2001-06-30,2001-09-06,2002-09-06,10810000000,10899000000,25296000000,<NA>,<NA>,<NA>,-3455000000,<NA>,<NA>,<NA>,21841000000,<NA>,-10121000000,-5742000000,-4885000000,-857000000,-4379000000,<NA>,<NA>,<NA>,11720000000,-36000000,<NA>,<NA>,<NA>,-36000000,<NA>,<NA>,<NA>,11684000000,-159000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,11525000000,-3804000000,<NA>,<NA>,None,<NA>,7721000000,-375000000,<NA>,-375000000,7346000000,<NA>,7346000000,<NA>,<NA>,7346000000
210,MSFT,59265,simfin,us,A,False,USD,2002,FY,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,28365000000,<NA>,<NA>,<NA>,-5191000000,<NA>,<NA>,<NA>,23174000000,<NA>,-11264000000,-6957000000,-5407000000,-1550000000,-4307000000,<NA>,<NA>,<NA>,11910000000,-305000000,<NA>,<NA>,<NA>,-305000000,<NA>,<NA>,<NA>,11605000000,-92000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,11513000000,-3684000000,<NA>,<NA>,None,<NA>,7829000000,<NA>,<NA>,<NA>,7829000000,<NA>,7829000000,<NA>,<NA>,7829000000
195,MSFT,59265,simfin,us,Q,False,USD,2002,Q3,2002-03-31,2002-04-30,2002-04-30,10810000000,10899000000,7245000000,<NA>,<NA>,<NA>,-1395000000,<NA>,<NA>,<NA>,5850000000,<NA>,-2552000000,-1486000000,-1240000000,-246000000,-1066000000,<NA>,<NA>,<NA>,3298000000,739000000,<NA>,<NA>,<NA>,739000000,<NA>,<NA>,<NA>,4037000000,-11000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,4026000000,-1288000000,<NA>,<NA>,None,<NA>,2738000000,<NA>,<NA>,<NA>,2738000000,<NA>,2738000000,<NA>,<NA>,2738000000
50,MSFT,59265,simfin,us,Q,False,USD,2002,Q4,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,7253000000,<NA>,<NA>,<NA>,-1368000000,<NA>,<NA>,<NA>,5885000000,<NA>,-3011000000,-1827000000,-1543000000,-284000000,-1184000000,<NA>,<NA>,<NA>,2874000000,-617000000,<NA>,<NA>,<NA>,-617000000,<NA>,<NA>,<NA>,2257000000,-14000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,2243000000,-718000000,<NA>,<NA>,None,<NA>,1525000000,<NA>,<NA>,<NA>,1525000000,<NA>,1525000000,<NA>,<NA>,1525000000
155,MSFT,59265,simfin,us,A,False,USD,2003,FY,2003-06-30,2003-09-05,2003-09-05,10810000000,10899000000,32187000000,<NA>,<NA>,<NA>,-5686000000,<NA>,<NA>,<NA>,26501000000,<NA>,-13284000000,-8625000000,-6521000000,-2104000000,-4659000000,<NA>,<NA>,<NA>,13217000000,1577000000,<NA>,<NA>,<NA>,1577000000,<NA>,<NA>,<NA>,14794000000,-68000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,14726000000,-4733000000,<NA>,<NA>,None,<NA>,9993000000,<NA>,<NA>,<NA>,9993000000,<NA>,9993000000,<NA>,<NA>,9993000000
173,MSFT,59265,simfin,us,Q,False,USD,2025,Q3,2025-03-31,2025-04-30,2025-04-30,7434000000,7461000000,70066000000,<NA>,<NA>,<NA>,-21919000000,<NA>,<NA>,<NA>,48147000000,<NA>,-16147000000,-7949000000,<NA>,<NA>,-8198000000,<NA>,<NA>,<NA>,32000000000,-623000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-623000000,31377000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,31377000000,-5553000000,<NA>,<NA>,None,<NA>,25824000000,<NA>,<NA>,<NA>,25824000000,<NA>,25824000000,<NA>,<NA>,25824000000
153,MSFT,59265,simfin,us,Q,False,USD,2025,Q4,2025-06-30,2025-07-30,2025-04-30,7430000000,7461000000,76441000000,<NA>,<NA>,<NA>,-24014000000,<NA>,<NA>,<NA>,52427000000,<NA>,-18104000000,-9275000000,<NA>,<NA>,-8829000000,<NA>,<NA>,<NA>,34323000000,-1707000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1707000000,32616000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,32616000000,-5383000000,<NA>,<NA>,None,<NA>,27233000000,<NA>,<NA>,<NA>,27233000000,<NA>,27233000000,<NA>,<NA>,27233000000
129,MSFT,59265,simfin,us,Q,False,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,77673000000,<NA>,<NA>,<NA>,-24043000000,<NA>,<NA>,<NA>,53630000000,<NA>,-15669000000,-7523000000,<NA>,<NA>,-8146000000,<NA>,<NA>,<NA>,37961000000,-3660000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3660000000,34301000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,34301000000,-6554000000,<NA>,<NA>,None,<NA>,27747000000,<NA>,<NA>,<NA>,27747000000,<NA>,27747000000,<NA>,<NA>,27747000000
174,MSFT,59265,simfin,us,Q,False,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,81273000000,<NA>,<NA>,<NA>,-25978000000,<NA>,<NA>,<NA>,55295000000,<NA>,-17020000000,-8516000000,<NA>,<NA>,-8504000000,<NA>,<NA>,<NA>,38275000000,9971000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9971000000,48246000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,48246000000,-9788000000,<NA>,<NA>,None,<NA>,38458000000,<NA>,<NA>,<NA>,38458000000,<NA>,38458000000,<NA>,<NA>,38458000000
154,MSFT,59265,simfin,us,Q,False,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,82886000000,<NA>,<NA>,<NA>,-26828000000,<NA>,<NA>,<NA>,56058000000,<NA>,-17660000000,-8745000000,<NA>,<NA>,-8915000000,<NA>,<NA>,<NA>,38398000000,942000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,39340000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,39340000000,-7562000000,<NA>,<NA>,None,<NA>,31778000000,<NA>,<NA>,<NA>,31778000000,<NA>,31778000000,<NA>,<NA>,31778000000

### income (restated)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
Revenue,122.0,7245000000.0,281724000000.0,42861319672.131149,46364303513.072823
Cost of Revenue,122.0,-87831000000.0,-1253000000.0,-12598262295.081966,14931701779.982586
Gross Profit,122.0,5377000000.0,193893000000.0,30263057377.049179,31654380952.081348
Operating Expenses,122.0,-65365000000.0,-2552000000.0,-13728975409.836065,12179150638.370378
"Selling, General & Administrative",122.0,-32877000000.0,-1486000000.0,-8101573770.491803,6746437879.708141
Research & Development,122.0,-32488000000.0,-1066000000.0,-5627401639.344262,5610197456.285268
Non-Operating Income (Loss),122.0,-4901000000.0,9971000000.0,264786885.245902,1239794092.671552
Operating Income (Loss),122.0,-764000000.0,128528000000.0,16534081967.213116,20075670622.307354
Pretax Income (Loss),122.0,-1756000000.0,123627000000.0,16505672131.147541,19893969253.317554
"Pretax Income (Loss), Adj.",122.0,-1381000000.0,123627000000.0,16798868852.459017,19855821674.330769
Net Income,122.0,-6302000000.0,101832000000.0,13124254098.360655,16645690723.492765
Income (Loss) Incl. Minority Interest,122.0,-6302000000.0,101832000000.0,13124254098.360655,16645690723.492765
"Income Tax (Expense) Benefit, Net",122.0,-21795000000.0,591000000.0,-3378344262.295082,3905360416.104709
Income (Loss) from Continuing Operations,122.0,-6302000000.0,101832000000.0,13127327868.852459,16644649491.699455
Net Income (Common),122.0,-6302000000.0,101832000000.0,13124254098.360655,16645690723.492765
Selling & Marketing,99.0,-19598000000.0,-1240000000.0,-5377747474.747475,4262002445.300045
General & Administrative,99.0,-5275000000.0,-246000000.0,-1713353535.353535,1356229672.569429
Other Non-Operating Income (Loss),95.0,-4901000000.0,9971000000.0,162810526.315789,1336375204.469935

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
157,MSFT,59265,simfin,us,A,True,USD,2001,FY,2001-06-30,2001-09-06,2003-09-05,10810000000,10899000000,25296000000,<NA>,<NA>,<NA>,-3455000000,<NA>,<NA>,<NA>,21841000000,<NA>,-10121000000,-5742000000,-4885000000,-857000000,-4379000000,<NA>,<NA>,<NA>,11720000000,-36000000,<NA>,<NA>,<NA>,-36000000,<NA>,<NA>,<NA>,11684000000,-159000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,11525000000,-3804000000,<NA>,<NA>,None,<NA>,7721000000,-375000000,<NA>,-375000000,7346000000,<NA>,7346000000,<NA>,<NA>,7346000000
101,MSFT,59265,simfin,us,A,True,USD,2002,FY,2002-06-30,2002-09-06,2004-09-01,10810000000,10899000000,28365000000,<NA>,<NA>,<NA>,-5699000000,<NA>,<NA>,<NA>,22666000000,<NA>,-14394000000,-8095000000,-6252000000,-1843000000,-6299000000,<NA>,<NA>,<NA>,8272000000,-305000000,<NA>,<NA>,<NA>,-305000000,<NA>,<NA>,<NA>,7967000000,-92000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,7875000000,-2520000000,<NA>,<NA>,None,<NA>,5355000000,<NA>,<NA>,<NA>,5355000000,<NA>,5355000000,<NA>,<NA>,5355000000
191,MSFT,59265,simfin,us,Q,True,USD,2002,Q3,2002-03-31,2002-04-30,2003-05-12,10810000000,10899000000,7245000000,<NA>,<NA>,<NA>,-1395000000,<NA>,<NA>,<NA>,5850000000,<NA>,-2552000000,-1486000000,-1240000000,-246000000,-1066000000,<NA>,<NA>,<NA>,3298000000,739000000,<NA>,<NA>,<NA>,739000000,<NA>,<NA>,<NA>,4037000000,-11000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,4026000000,-1288000000,<NA>,<NA>,None,<NA>,2738000000,<NA>,<NA>,<NA>,2738000000,<NA>,2738000000,<NA>,<NA>,2738000000
45,MSFT,59265,simfin,us,Q,True,USD,2002,Q4,2002-06-30,2002-09-06,2004-09-01,10810000000,10899000000,7253000000,<NA>,<NA>,<NA>,-1876000000,<NA>,<NA>,<NA>,5377000000,<NA>,-6141000000,-2965000000,-2388000000,-577000000,-3176000000,<NA>,<NA>,<NA>,-764000000,-617000000,<NA>,<NA>,<NA>,-617000000,<NA>,<NA>,<NA>,-1381000000,-14000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-1395000000,446000000,<NA>,<NA>,None,<NA>,-949000000,<NA>,<NA>,<NA>,-949000000,<NA>,-949000000,<NA>,<NA>,-949000000
124,MSFT,59265,simfin,us,A,True,USD,2003,FY,2003-06-30,2003-09-05,2005-08-26,10810000000,10899000000,32187000000,<NA>,<NA>,<NA>,-6059000000,<NA>,<NA>,<NA>,26128000000,<NA>,-16583000000,-9988000000,-7562000000,-2426000000,-6595000000,<NA>,<NA>,<NA>,9545000000,1509000000,<NA>,<NA>,<NA>,1509000000,<NA>,<NA>,<NA>,11054000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,11054000000,-3523000000,<NA>,<NA>,None,<NA>,7531000000,<NA>,<NA>,<NA>,7531000000,<NA>,7531000000,<NA>,<NA>,7531000000
12,MSFT,59265,simfin,us,Q,True,USD,2025,Q3,2025-03-31,2025-04-30,2026-04-29,7434000000,7461000000,70066000000,<NA>,<NA>,<NA>,-21919000000,<NA>,<NA>,<NA>,48147000000,<NA>,-16147000000,-7949000000,<NA>,<NA>,-8198000000,<NA>,<NA>,<NA>,32000000000,-623000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-623000000,31377000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,31377000000,-5553000000,<NA>,<NA>,None,<NA>,25824000000,<NA>,<NA>,<NA>,25824000000,<NA>,25824000000,<NA>,<NA>,25824000000
108,MSFT,59265,simfin,us,Q,True,USD,2025,Q4,2025-06-30,2025-07-30,2026-04-29,7430000000,7461000000,76441000000,<NA>,<NA>,<NA>,-24014000000,<NA>,<NA>,<NA>,52427000000,<NA>,-18104000000,-9275000000,<NA>,<NA>,-8829000000,<NA>,<NA>,<NA>,34323000000,-1707000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1707000000,32616000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,32616000000,-5383000000,<NA>,<NA>,None,<NA>,27233000000,<NA>,<NA>,<NA>,27233000000,<NA>,27233000000,<NA>,<NA>,27233000000
64,MSFT,59265,simfin,us,Q,True,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,77673000000,<NA>,<NA>,<NA>,-24043000000,<NA>,<NA>,<NA>,53630000000,<NA>,-15669000000,-7523000000,<NA>,<NA>,-8146000000,<NA>,<NA>,<NA>,37961000000,-3660000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3660000000,34301000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,34301000000,-6554000000,<NA>,<NA>,None,<NA>,27747000000,<NA>,<NA>,<NA>,27747000000,<NA>,27747000000,<NA>,<NA>,27747000000
194,MSFT,59265,simfin,us,Q,True,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,81273000000,<NA>,<NA>,<NA>,-25978000000,<NA>,<NA>,<NA>,55295000000,<NA>,-17020000000,-8516000000,<NA>,<NA>,-8504000000,<NA>,<NA>,<NA>,38275000000,9971000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9971000000,48246000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,48246000000,-9788000000,<NA>,<NA>,None,<NA>,38458000000,<NA>,<NA>,<NA>,38458000000,<NA>,38458000000,<NA>,<NA>,38458000000
49,MSFT,59265,simfin,us,Q,True,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,82886000000,<NA>,<NA>,<NA>,-26828000000,<NA>,<NA>,<NA>,56058000000,<NA>,-17660000000,-8745000000,<NA>,<NA>,-8915000000,<NA>,<NA>,<NA>,38398000000,942000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,39340000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,39340000000,-7562000000,<NA>,<NA>,None,<NA>,31778000000,<NA>,<NA>,<NA>,31778000000,<NA>,31778000000,<NA>,<NA>,31778000000

## balance

### balance (as-reported)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
"Cash, Cash Equivalents & Short Term Investments",122.0,20715000000.0,143951000000.0,78056204918.032791,39316501477.060211
Cash & Cash Equivalents,122.0,2974000000.0,80452000000.0,11387762295.081966,9441363658.731604
Short Term Investments,122.0,11718000000.0,131587000000.0,66668442622.950821,36670998097.343338
Accounts & Notes Receivable,122.0,3671000000.0,69905000000.0,19975680327.868851,15440792765.513811
Other Short Term Assets,122.0,2767000000.0,35797000000.0,9000729508.196722,7464775755.171072
"Property, Plant & Equipment, Net",122.0,2178000000.0,283228000000.0,36931754098.360657,56300223402.711571
Total Current Assets,122.0,35853000000.0,207586000000.0,108715770491.803284,54042034188.241737
Misc. Short Term Assets,122.0,1245000000.0,35797000000.0,7846459016.393442,8137175049.583404
Total Equity,122.0,31097000000.0,414367000000.0,102986401639.344269,83325163575.320282
Equity Before Minority Interest,122.0,31097000000.0,414367000000.0,102986401639.344269,83325163575.320282
Total Liabilities & Equity,122.0,58830000000.0,694228000000.0,207705827868.852448,158019560809.648682
Long Term Investments & Receivables,122.0,1862000000.0,33683000000.0,9672000000.0,4598433443.275155
Other Long Term Assets,122.0,2611000000.0,207501000000.0,52386303278.688522,59835705440.41317
Intangible Assets,122.0,243000000.0,29896000000.0,6169360655.737705,7098017999.536562
Goodwill,122.0,1426000000.0,119661000000.0,31872819672.131149,34514091801.412132
Misc. Long Term Assets,122.0,895000000.0,65388000000.0,13904459016.393442,19207790090.682686
Total Noncurrent Assets,122.0,19070000000.0,518899000000.0,98990057377.049179,115980258457.945709
Total Assets,122.0,58830000000.0,694228000000.0,207705827868.852448,158019560809.648682
Payables & Accruals,122.0,1930000000.0,52346000000.0,13747163934.426229,12416853955.600895
Deferred Revenue (Short Term),122.0,4395000000.0,64555000000.0,22913959016.393444,15114757526.916534
Other Short Term Liabilities,122.0,7324000000.0,89575000000.0,32249073770.491802,20028111633.966198
Deferred Revenue (Long Term),122.0,1089000000.0,10377000000.0,2561409836.065574,1703715399.127673
Total Current Liabilities,122.0,9254000000.0,141218000000.0,50103196721.311478,35093101534.344666
Misc. Short Term Liabilities,122.0,1378000000.0,25020000000.0,8034655737.704918,5868942485.408502
Retained Earnings,122.0,-29460000000.0,302526000000.0,33785836065.573769,70020952342.71788
Share Capital & Additional Paid-In Capital,122.0,28390000000.0,115069000000.0,69943573770.491806,17805262140.711987
Total Liabilities,122.0,11541000000.0,279861000000.0,104719426229.508194,81303874407.383194
Other Long Term Liabilities,122.0,2237000000.0,111777000000.0,28298655737.704918,27239297618.634315
Misc. Long Term Liabilities,122.0,501000000.0,106125000000.0,24695680327.868851,26403377666.555283
Total Noncurrent Liabilities,122.0,2237000000.0,144422000000.0,54616229508.196724,48603736988.555481
"Accounts Receivable, Net",121.0,3671000000.0,69905000000.0,19844628099.173553,15436713570.863148
Accounts Payable,121.0,1136000000.0,37513000000.0,8178421487.603306,7761335218.839674
Other Payables & Accruals,121.0,742000000.0,15161000000.0,4812520661.157024,3620935767.862532
Inventories,120.0,304000000.0,4268000000.0,1711208333.333333,922574010.566084
Additional Paid in Capital,103.0,28390000000.0,86939000000.0,64607902912.621361,12652006986.81451
Deferred Tax Liabilities (Short Term),95.0,493000000.0,5665000000.0,1670063157.894737,1165195845.199756
Deferred Tax Liabilities (Long Term),91.0,59000000.0,5513000000.0,1396384615.384615,1123638413.263219
Short Term Debt,85.0,0.0,29556000000.0,5894694117.647058,5854793853.927634
Long Term Debt,85.0,3746000000.0,76255000000.0,37773458823.529411,22573955858.125397
Deferred Tax Assets (Short Term),72.0,1258000000.0,2607000000.0,1955847222.222222,339136503.313193

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
66,MSFT,59265,simfin,us,A,False,USD,2001,Q4,2001-06-30,2001-07-30,2002-04-30,10810000000,10899000000,31600000000,3922000000,27678000000,3671000000,3671000000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,3939000000,<NA>,<NA>,<NA>,1522000000,<NA>,<NA>,2417000000,39210000000,2309000000,<NA>,<NA>,14361000000,<NA>,<NA>,<NA>,2950000000,401000000,1511000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1038000000,19620000000,58830000000,1930000000,1188000000,<NA>,<NA>,742000000,<NA>,<NA>,<NA>,<NA>,7324000000,4395000000,<NA>,1468000000,<NA>,1461000000,9254000000,<NA>,<NA>,<NA>,2287000000,<NA>,<NA>,<NA>,<NA>,<NA>,1219000000,409000000,<NA>,<NA>,659000000,2287000000,11541000000,<NA>,28390000000,<NA>,28390000000,<NA>,<NA>,18899000000,<NA>,47289000000,<NA>,47289000000,58830000000
24,MSFT,59265,simfin,us,Q,False,USD,2002,Q3,2002-03-31,2002-04-30,2002-04-30,10810000000,10899000000,38693000000,5116000000,33577000000,4230000000,4230000000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,4904000000,<NA>,<NA>,<NA>,2086000000,<NA>,<NA>,2818000000,47827000000,2182000000,<NA>,<NA>,15694000000,<NA>,<NA>,<NA>,2676000000,277000000,1433000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,966000000,20552000000,68379000000,1958000000,1136000000,<NA>,<NA>,822000000,<NA>,<NA>,<NA>,<NA>,9884000000,5568000000,<NA>,2477000000,<NA>,1839000000,11842000000,<NA>,<NA>,<NA>,2237000000,<NA>,<NA>,<NA>,<NA>,<NA>,1346000000,59000000,<NA>,<NA>,832000000,2237000000,14079000000,<NA>,30904000000,<NA>,30904000000,<NA>,<NA>,23396000000,<NA>,54300000000,<NA>,54300000000,68379000000
130,MSFT,59265,simfin,us,A,False,USD,2002,Q4,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,38652000000,3016000000,35636000000,5129000000,5129000000,<NA>,None,673000000,<NA>,<NA>,<NA>,<NA>,4122000000,<NA>,<NA>,<NA>,2112000000,<NA>,<NA>,2010000000,48576000000,2268000000,<NA>,<NA>,14191000000,<NA>,<NA>,<NA>,2611000000,243000000,1426000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,19070000000,67646000000,2353000000,1208000000,<NA>,<NA>,1145000000,<NA>,<NA>,<NA>,<NA>,10391000000,5920000000,<NA>,2022000000,<NA>,2449000000,12744000000,<NA>,<NA>,<NA>,2722000000,<NA>,<NA>,<NA>,<NA>,<NA>,1823000000,398000000,<NA>,<NA>,501000000,2722000000,15466000000,<NA>,31647000000,<NA>,31647000000,<NA>,<NA>,20533000000,<NA>,52180000000,<NA>,52180000000,67646000000
131,MSFT,59265,simfin,us,Q,False,USD,2002,Q4,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,38652000000,3016000000,35636000000,5129000000,5129000000,<NA>,None,673000000,<NA>,<NA>,<NA>,<NA>,4122000000,<NA>,<NA>,<NA>,2112000000,<NA>,<NA>,2010000000,48576000000,2268000000,<NA>,<NA>,14191000000,<NA>,<NA>,<NA>,2611000000,243000000,1426000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,19070000000,67646000000,2353000000,1208000000,<NA>,<NA>,1145000000,<NA>,<NA>,<NA>,<NA>,10391000000,5920000000,<NA>,2022000000,<NA>,2449000000,12744000000,<NA>,<NA>,<NA>,2722000000,<NA>,<NA>,<NA>,<NA>,<NA>,1823000000,398000000,<NA>,<NA>,501000000,2722000000,15466000000,<NA>,31647000000,<NA>,31647000000,<NA>,<NA>,20533000000,<NA>,52180000000,<NA>,52180000000,67646000000
225,MSFT,59265,simfin,us,Q,False,USD,2003,Q1,2002-09-30,2002-11-14,2002-11-14,10810000000,10899000000,40475000000,5338000000,35137000000,4450000000,4450000000,<NA>,None,959000000,<NA>,<NA>,<NA>,<NA>,4159000000,<NA>,<NA>,<NA>,2401000000,<NA>,<NA>,1758000000,50043000000,2189000000,<NA>,<NA>,13580000000,<NA>,<NA>,<NA>,4423000000,642000000,2855000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,926000000,20192000000,70235000000,2040000000,1189000000,<NA>,<NA>,851000000,<NA>,<NA>,<NA>,<NA>,11717000000,6841000000,<NA>,3307000000,<NA>,1569000000,13757000000,<NA>,<NA>,<NA>,2962000000,<NA>,<NA>,<NA>,<NA>,<NA>,2290000000,152000000,<NA>,<NA>,520000000,2962000000,16719000000,<NA>,33013000000,<NA>,33013000000,<NA>,<NA>,20503000000,<NA>,53516000000,<NA>,53516000000,70235000000
7,MSFT,59265,simfin,us,A,False,USD,2025,Q4,2025-06-30,2025-07-30,2025-07-30,7433000000,7465000000,94565000000,30242000000,64323000000,69905000000,69905000000,<NA>,None,938000000,<NA>,<NA>,<NA>,<NA>,25723000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25723000000,191131000000,204966000000,204966000000,<NA>,15405000000,<NA>,<NA>,<NA>,207501000000,22604000000,119509000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,65388000000,427872000000,619003000000,48644000000,27724000000,7211000000,<NA>,13709000000,2999000000,<NA>,<NA>,<NA>,89575000000,64555000000,<NA>,<NA>,<NA>,25020000000,141218000000,40152000000,<NA>,<NA>,94154000000,<NA>,<NA>,<NA>,<NA>,<NA>,2710000000,2835000000,<NA>,<NA>,88609000000,134306000000,275524000000,<NA>,109095000000,<NA>,<NA>,<NA>,<NA>,237731000000,-3347000000,343479000000,<NA>,343479000000,619003000000
119,MSFT,59265,simfin,us,Q,False,USD,2025,Q4,2025-06-30,2025-07-30,2025-07-30,7430000000,7461000000,94565000000,30242000000,64323000000,69905000000,69905000000,<NA>,None,938000000,<NA>,<NA>,<NA>,<NA>,25723000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25723000000,191131000000,204966000000,204966000000,<NA>,15405000000,<NA>,<NA>,<NA>,207501000000,22604000000,119509000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,65388000000,427872000000,619003000000,48644000000,27724000000,7211000000,<NA>,13709000000,2999000000,<NA>,<NA>,<NA>,89575000000,64555000000,<NA>,<NA>,<NA>,25020000000,141218000000,40152000000,<NA>,<NA>,94154000000,<NA>,<NA>,<NA>,<NA>,<NA>,2710000000,2835000000,<NA>,<NA>,88609000000,134306000000,275524000000,<NA>,109095000000,<NA>,<NA>,<NA>,<NA>,237731000000,-3347000000,343479000000,<NA>,343479000000,619003000000
210,MSFT,59265,simfin,us,Q,False,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,102012000000,28849000000,73163000000,52894000000,52894000000,<NA>,None,1130000000,<NA>,<NA>,<NA>,<NA>,33030000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33030000000,189066000000,230861000000,230861000000,<NA>,11465000000,<NA>,<NA>,<NA>,204959000000,21236000000,119497000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,64226000000,447285000000,636351000000,45436000000,32580000000,3655000000,<NA>,9201000000,7832000000,<NA>,<NA>,<NA>,81728000000,58987000000,<NA>,<NA>,<NA>,22741000000,134996000000,35376000000,<NA>,<NA>,102903000000,<NA>,<NA>,<NA>,<NA>,<NA>,2546000000,2852000000,<NA>,<NA>,97505000000,138279000000,273275000000,<NA>,110964000000,<NA>,<NA>,<NA>,<NA>,254873000000,-2761000000,363076000000,<NA>,363076000000,636351000000
60,MSFT,59265,simfin,us,Q,False,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,89462000000,24296000000,65166000000,56535000000,56535000000,<NA>,None,1059000000,<NA>,<NA>,<NA>,<NA>,33134000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33134000000,180190000000,261126000000,261126000000,<NA>,21202000000,<NA>,<NA>,<NA>,202784000000,20289000000,119622000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62873000000,485112000000,665302000000,49481000000,37328000000,2050000000,<NA>,10103000000,4837000000,<NA>,<NA>,<NA>,75687000000,51376000000,<NA>,<NA>,<NA>,24311000000,130005000000,35425000000,<NA>,<NA>,108997000000,<NA>,<NA>,<NA>,<NA>,<NA>,2668000000,2876000000,<NA>,<NA>,103453000000,144422000000,274427000000,<NA>,112788000000,<NA>,<NA>,<NA>,<NA>,280789000000,-2702000000,390875000000,<NA>,390875000000,665302000000
226,MSFT,59265,simfin,us,Q,False,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,78272000000,32105000000,46167000000,60041000000,60041000000,<NA>,None,1219000000,<NA>,<NA>,<NA>,<NA>,35797000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,35797000000,175329000000,283228000000,283228000000,<NA>,33683000000,<NA>,<NA>,<NA>,201988000000,19325000000,119661000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,63002000000,518899000000,694228000000,52346000000,37513000000,3563000000,<NA>,11270000000,8839000000,<NA>,<NA>,<NA>,75476000000,50924000000,<NA>,<NA>,<NA>,24552000000,136661000000,31423000000,<NA>,<NA>,111777000000,<NA>,<NA>,<NA>,<NA>,<NA>,2753000000,2899000000,<NA>,<NA>,106125000000,143200000000,279861000000,<NA>,115069000000,<NA>,<NA>,<NA>,<NA>,302526000000,-3228000000,414367000000,<NA>,414367000000,694228000000

### balance (restated)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
"Cash, Cash Equivalents & Short Term Investments",122.0,20715000000.0,143951000000.0,78079729508.196716,39298124193.880226
Cash & Cash Equivalents,122.0,2974000000.0,80452000000.0,11377778688.52459,9419036260.392216
Short Term Investments,122.0,11718000000.0,131587000000.0,66701950819.672134,36650898877.469391
Accounts & Notes Receivable,122.0,3671000000.0,69905000000.0,20028131147.540985,15434706309.976233
Other Short Term Assets,122.0,2767000000.0,35797000000.0,8974278688.52459,7472786152.458033
"Property, Plant & Equipment, Net",122.0,2178000000.0,283228000000.0,36931877049.180328,56300146961.124908
Total Current Assets,122.0,35853000000.0,207586000000.0,108766270491.803284,54044803101.362778
Misc. Short Term Assets,122.0,1245000000.0,35797000000.0,7849360655.737705,8136285232.802106
Total Equity,122.0,31097000000.0,414367000000.0,103355647540.983612,83196442823.365494
Equity Before Minority Interest,122.0,31097000000.0,414367000000.0,103355647540.983612,83196442823.365494
Total Liabilities & Equity,122.0,58830000000.0,694228000000.0,207919516393.442627,157984476393.440796
Long Term Investments & Receivables,122.0,1862000000.0,33683000000.0,9677245901.639345,4602684312.570374
Other Long Term Assets,122.0,2611000000.0,207501000000.0,52544122950.819672,59797333240.046097
Intangible Assets,122.0,243000000.0,29896000000.0,6167795081.967213,7099283068.143466
Goodwill,122.0,1426000000.0,119661000000.0,31875655737.704918,34511695749.656631
Misc. Long Term Assets,122.0,895000000.0,65388000000.0,14007868852.459017,19183586594.463669
Total Noncurrent Assets,122.0,19070000000.0,518899000000.0,99153245901.639343,115927090559.078354
Total Assets,122.0,58830000000.0,694228000000.0,207919516393.442627,157984476393.440796
Payables & Accruals,122.0,1930000000.0,52346000000.0,13804065573.770493,12435771226.412319
Deferred Revenue (Short Term),122.0,4395000000.0,64555000000.0,22752065573.770493,15042215061.705729
Other Short Term Liabilities,122.0,7324000000.0,89575000000.0,32052131147.540985,19984734956.25885
Deferred Revenue (Long Term),122.0,1089000000.0,9215000000.0,2435081967.213115,1369774371.178186
Total Current Liabilities,122.0,9254000000.0,141218000000.0,49962434426.229507,35044323544.06279
Misc. Short Term Liabilities,122.0,1451000000.0,25020000000.0,8055393442.622951,5862880208.548641
Retained Earnings,122.0,-29460000000.0,302526000000.0,33881918032.786884,70035305786.237122
Share Capital & Additional Paid-In Capital,122.0,28390000000.0,115069000000.0,70293426229.508194,17241501029.034054
Total Liabilities,122.0,11541000000.0,279861000000.0,104563868852.459015,81255924629.963211
Other Long Term Liabilities,122.0,2237000000.0,111777000000.0,28287565573.770493,27278338065.571949
Misc. Long Term Liabilities,122.0,501000000.0,106125000000.0,24782270491.80328,26386318227.832474
Total Noncurrent Liabilities,122.0,2237000000.0,144422000000.0,54601434426.229507,48686085434.397133
"Accounts Receivable, Net",121.0,3671000000.0,69905000000.0,19897512396.694214,15431026897.19412
Inventories,121.0,83000000.0,4268000000.0,1698049586.77686,930222561.641744
Other Payables & Accruals,121.0,742000000.0,14728000000.0,4813487603.305785,3608027760.230655
Accounts Payable,121.0,1136000000.0,37513000000.0,8180595041.322314,7759432288.703549
Additional Paid in Capital,100.0,28390000000.0,85767000000.0,64741840000.0,11534601607.197697
Deferred Tax Liabilities (Short Term),92.0,493000000.0,5665000000.0,1650543478.26087,1178547461.482985
Deferred Tax Liabilities (Long Term),90.0,0.0,5734000000.0,1450733333.333333,1289536732.423572
Short Term Debt,85.0,0.0,29556000000.0,5893658823.529411,5816447656.989496
Long Term Debt,85.0,3746000000.0,76255000000.0,37768141176.470589,22573264765.432316
Deferred Tax Assets (Short Term),70.0,1258000000.0,2607000000.0,1960571428.571429,348350962.930693

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
111,MSFT,59265,simfin,us,A,True,USD,2001,Q4,2001-06-30,2001-07-30,2002-09-06,10810000000,10899000000,31600000000,3922000000,27678000000,3671000000,3671000000,<NA>,None,83000000,<NA>,<NA>,<NA>,<NA>,3856000000,<NA>,<NA>,<NA>,1522000000,<NA>,<NA>,2334000000,39210000000,2309000000,<NA>,<NA>,14361000000,<NA>,<NA>,<NA>,2950000000,401000000,1511000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1038000000,19620000000,58830000000,1930000000,1188000000,<NA>,<NA>,742000000,<NA>,<NA>,<NA>,<NA>,7324000000,4395000000,<NA>,1468000000,<NA>,1461000000,9254000000,<NA>,<NA>,<NA>,2287000000,<NA>,<NA>,<NA>,<NA>,<NA>,1219000000,409000000,<NA>,<NA>,659000000,2287000000,11541000000,<NA>,28390000000,<NA>,28390000000,<NA>,<NA>,18899000000,<NA>,47289000000,<NA>,47289000000,58830000000
50,MSFT,59265,simfin,us,Q,True,USD,2002,Q3,2002-03-31,2002-04-30,2002-04-30,10810000000,10899000000,38693000000,5116000000,33577000000,4230000000,4230000000,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>,4904000000,<NA>,<NA>,<NA>,2086000000,<NA>,<NA>,2818000000,47827000000,2182000000,<NA>,<NA>,15694000000,<NA>,<NA>,<NA>,2676000000,277000000,1433000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,966000000,20552000000,68379000000,1958000000,1136000000,<NA>,<NA>,822000000,<NA>,<NA>,<NA>,<NA>,9884000000,5568000000,<NA>,2477000000,<NA>,1839000000,11842000000,<NA>,<NA>,<NA>,2237000000,<NA>,<NA>,<NA>,<NA>,<NA>,1346000000,59000000,<NA>,<NA>,832000000,2237000000,14079000000,<NA>,30904000000,<NA>,30904000000,<NA>,<NA>,23396000000,<NA>,54300000000,<NA>,54300000000,68379000000
141,MSFT,59265,simfin,us,Q,True,USD,2002,Q4,2002-06-30,2002-09-06,2003-05-12,10810000000,10899000000,38652000000,3016000000,35636000000,5129000000,5129000000,<NA>,None,673000000,<NA>,<NA>,<NA>,<NA>,4122000000,<NA>,<NA>,<NA>,2112000000,<NA>,<NA>,2010000000,48576000000,2268000000,<NA>,<NA>,14191000000,<NA>,<NA>,<NA>,2611000000,243000000,1426000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,19070000000,67646000000,2353000000,1208000000,<NA>,<NA>,1145000000,<NA>,<NA>,<NA>,<NA>,10391000000,5920000000,<NA>,2022000000,<NA>,2449000000,12744000000,<NA>,<NA>,<NA>,2722000000,<NA>,<NA>,<NA>,<NA>,<NA>,1823000000,398000000,<NA>,<NA>,501000000,2722000000,15466000000,<NA>,31647000000,<NA>,31647000000,<NA>,<NA>,20533000000,<NA>,52180000000,<NA>,52180000000,67646000000
224,MSFT,59265,simfin,us,A,True,USD,2002,Q4,2002-06-30,2002-09-06,2003-05-12,10810000000,10899000000,38652000000,3016000000,35636000000,5129000000,5129000000,<NA>,None,673000000,<NA>,<NA>,<NA>,<NA>,4122000000,<NA>,<NA>,<NA>,2112000000,<NA>,<NA>,2010000000,48576000000,2268000000,<NA>,<NA>,14191000000,<NA>,<NA>,<NA>,2611000000,243000000,1426000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942000000,19070000000,67646000000,2353000000,1208000000,<NA>,<NA>,1145000000,<NA>,<NA>,<NA>,<NA>,10391000000,5920000000,<NA>,2022000000,<NA>,2449000000,12744000000,<NA>,<NA>,<NA>,2722000000,<NA>,<NA>,<NA>,<NA>,<NA>,1823000000,398000000,<NA>,<NA>,501000000,2722000000,15466000000,<NA>,31647000000,<NA>,31647000000,<NA>,<NA>,20533000000,<NA>,52180000000,<NA>,52180000000,67646000000
163,MSFT,59265,simfin,us,Q,True,USD,2003,Q1,2002-09-30,2002-11-14,2002-11-14,10810000000,10899000000,40475000000,5338000000,35137000000,4450000000,4450000000,<NA>,None,959000000,<NA>,<NA>,<NA>,<NA>,4159000000,<NA>,<NA>,<NA>,2401000000,<NA>,<NA>,1758000000,50043000000,2189000000,<NA>,<NA>,13580000000,<NA>,<NA>,<NA>,4423000000,642000000,2855000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,926000000,20192000000,70235000000,2040000000,1189000000,<NA>,<NA>,851000000,<NA>,<NA>,<NA>,<NA>,11717000000,6841000000,<NA>,3307000000,<NA>,1569000000,13757000000,<NA>,<NA>,<NA>,2962000000,<NA>,<NA>,<NA>,<NA>,<NA>,2290000000,152000000,<NA>,<NA>,520000000,2962000000,16719000000,<NA>,33013000000,<NA>,33013000000,<NA>,<NA>,20503000000,<NA>,53516000000,<NA>,53516000000,70235000000
79,MSFT,59265,simfin,us,Q,True,USD,2025,Q4,2025-06-30,2025-07-30,2026-04-29,7430000000,7461000000,94565000000,30242000000,64323000000,69905000000,69905000000,<NA>,None,938000000,<NA>,<NA>,<NA>,<NA>,25723000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25723000000,191131000000,204966000000,204966000000,<NA>,15405000000,<NA>,<NA>,<NA>,207501000000,22604000000,119509000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,65388000000,427872000000,619003000000,48644000000,27724000000,7211000000,<NA>,13709000000,2999000000,<NA>,<NA>,<NA>,89575000000,64555000000,<NA>,<NA>,<NA>,25020000000,141218000000,40152000000,<NA>,<NA>,94154000000,<NA>,<NA>,<NA>,<NA>,<NA>,2710000000,2835000000,<NA>,<NA>,88609000000,134306000000,275524000000,<NA>,109095000000,<NA>,<NA>,<NA>,<NA>,237731000000,-3347000000,343479000000,<NA>,343479000000,619003000000
194,MSFT,59265,simfin,us,A,True,USD,2025,Q4,2025-06-30,2025-07-30,2026-04-29,7433000000,7465000000,94565000000,30242000000,64323000000,69905000000,69905000000,<NA>,None,938000000,<NA>,<NA>,<NA>,<NA>,25723000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25723000000,191131000000,204966000000,204966000000,<NA>,15405000000,<NA>,<NA>,<NA>,207501000000,22604000000,119509000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,65388000000,427872000000,619003000000,48644000000,27724000000,7211000000,<NA>,13709000000,2999000000,<NA>,<NA>,<NA>,89575000000,64555000000,<NA>,<NA>,<NA>,25020000000,141218000000,40152000000,<NA>,<NA>,94154000000,<NA>,<NA>,<NA>,<NA>,<NA>,2710000000,2835000000,<NA>,<NA>,88609000000,134306000000,275524000000,<NA>,109095000000,<NA>,<NA>,<NA>,<NA>,237731000000,-3347000000,343479000000,<NA>,343479000000,619003000000
129,MSFT,59265,simfin,us,Q,True,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,102012000000,28849000000,73163000000,52894000000,52894000000,<NA>,None,1130000000,<NA>,<NA>,<NA>,<NA>,33030000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33030000000,189066000000,230861000000,230861000000,<NA>,11465000000,<NA>,<NA>,<NA>,204959000000,21236000000,119497000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,64226000000,447285000000,636351000000,45436000000,32580000000,3655000000,<NA>,9201000000,7832000000,<NA>,<NA>,<NA>,81728000000,58987000000,<NA>,<NA>,<NA>,22741000000,134996000000,35376000000,<NA>,<NA>,102903000000,<NA>,<NA>,<NA>,<NA>,<NA>,2546000000,2852000000,<NA>,<NA>,97505000000,138279000000,273275000000,<NA>,110964000000,<NA>,<NA>,<NA>,<NA>,254873000000,-2761000000,363076000000,<NA>,363076000000,636351000000
71,MSFT,59265,simfin,us,Q,True,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,89462000000,24296000000,65166000000,56535000000,56535000000,<NA>,None,1059000000,<NA>,<NA>,<NA>,<NA>,33134000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33134000000,180190000000,261126000000,261126000000,<NA>,21202000000,<NA>,<NA>,<NA>,202784000000,20289000000,119622000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62873000000,485112000000,665302000000,49481000000,37328000000,2050000000,<NA>,10103000000,4837000000,<NA>,<NA>,<NA>,75687000000,51376000000,<NA>,<NA>,<NA>,24311000000,130005000000,35425000000,<NA>,<NA>,108997000000,<NA>,<NA>,<NA>,<NA>,<NA>,2668000000,2876000000,<NA>,<NA>,103453000000,144422000000,274427000000,<NA>,112788000000,<NA>,<NA>,<NA>,<NA>,280789000000,-2702000000,390875000000,<NA>,390875000000,665302000000
48,MSFT,59265,simfin,us,Q,True,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,78272000000,32105000000,46167000000,60041000000,60041000000,<NA>,None,1219000000,<NA>,<NA>,<NA>,<NA>,35797000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,35797000000,175329000000,283228000000,283228000000,<NA>,33683000000,<NA>,<NA>,<NA>,201988000000,19325000000,119661000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,63002000000,518899000000,694228000000,52346000000,37513000000,3563000000,<NA>,11270000000,8839000000,<NA>,<NA>,<NA>,75476000000,50924000000,<NA>,<NA>,<NA>,24552000000,136661000000,31423000000,<NA>,<NA>,111777000000,<NA>,<NA>,<NA>,<NA>,<NA>,2753000000,2899000000,<NA>,<NA>,106125000000,143200000000,279861000000,<NA>,115069000000,<NA>,<NA>,<NA>,<NA>,302526000000,-3228000000,414367000000,<NA>,414367000000,694228000000

## cashflow

### cashflow (as-reported)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
Net Income/Starting Line,122.0,-6302000000.0,101832000000.0,13060147540.983606,16609567431.922253
Depreciation & Amortization,122.0,108000000.0,34153000000.0,3247991803.278688,4679495034.380501
Non-Cash Items,122.0,-4632000000.0,65608000000.0,9422942622.950819,12352308083.782587
Change in Working Capital,122.0,-56083000000.0,14709000000.0,-7506557377.04918,11425676769.328657
Change in Fixed Assets & Intangibles,122.0,-64551000000.0,-160000000.0,-5179737704.918033,9064962795.074631
Net Change in Long Term Investment,122.0,-17802000000.0,23591000000.0,-469745901.639344,6891541234.571043
Net Cash from Operating Activities,122.0,1658000000.0,136162000000.0,18224524590.163933,21623479172.132656
Cash from (Repurchase of) Equity,122.0,-30855000000.0,1296000000.0,-5099663934.426229,5397417009.43422
Net Cash from Financing Activities,122.0,-60838000000.0,14329000000.0,-9094508196.721312,12182504522.216133
Net Change in Cash,122.0,-63147000000.0,45748000000.0,449868852.459016,8395274370.218833
Net Cash Before FX,122.0,-63219000000.0,45847000000.0,466122950.819672,8404583098.964684
Net Cash Before Disc. Operations and FX,122.0,-63219000000.0,45847000000.0,466122950.819672,8404583098.964684
Net Cash from Investing Activities,122.0,-96981000000.0,23414000000.0,-8663893442.622952,15187548065.050562
Decrease in Capital Stock,121.0,-32696000000.0,0.0,-5870157024.793388,5881613504.541454
Increase in Capital Stock,121.0,96000000.0,6782000000.0,771454545.454545,942830269.277915
Effect of Foreign Exchange Rates,121.0,-294000000.0,183000000.0,-16388429.752066,75055243.199129
Dividends Paid,114.0,-36112000000.0,0.0,-4763868421.052631,6003238066.528656
Net Cash from Acquisitions & Divestitures,113.0,-69132000000.0,0.0,-3094389380.530973,9746846159.723398
Other Non-Cash Adjustments,109.0,-9931000000.0,65638000000.0,9289733944.954128,12603816831.980495
Deferred Income Taxes,109.0,-6463000000.0,4446000000.0,-304577981.651376,1490779396.537373
Acquisition of Fixed Assets & Intangibles,109.0,-30876000000.0,-160000000.0,-3483247706.422019,5594040248.262834
Change in Other,108.0,-55289000000.0,17724000000.0,-8060000000.0,11545749518.499229
Change in Accounts Receivable,108.0,-12634000000.0,16490000000.0,-650203703.703704,4629168835.509211
Purchase of Fixed Assets,108.0,-30876000000.0,-160000000.0,-3451037037.037037,5609965575.262007
Decrease in Long Term Investment,107.0,1492000000.0,164394000000.0,27807943925.233646,28665371266.822109
Increase in Long Term Investment,106.0,-176905000000.0,2572000000.0,-28963500000.0,29971731784.736607
Other Financing Activities,103.0,-3751000000.0,2642000000.0,-248815533.980583,880192289.013419
Stock-Based Compensation,102.0,321000000.0,7502000000.0,1389058823.529412,1335008019.581574
Other Investing Activities,98.0,-6878000000.0,6627000000.0,-184612244.897959,1298967366.499236
Cash from (Repayment of) Debt,87.0,-14010000000.0,31459000000.0,934919540.229885,6709561894.71655
Change in Accounts Payable,65.0,-2521000000.0,3026000000.0,290861538.461538,1054544064.349066
Change in Inventories,65.0,-1123000000.0,1654000000.0,-39200000.0,663523671.39387

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
70,MSFT,59265,simfin,us,A,False,USD,2001,FY,2001-06-30,2001-09-06,2002-09-06,10810000000,10899000000,7346000000,<NA>,<NA>,<NA>,1536000000,11212000000,<NA>,-420000000,11632000000,-6672000000,-418000000,<NA>,<NA>,-6254000000,<NA>,13422000000,-1103000000,<NA>,<NA>,<NA>,-1103000000,-1103000000,<NA>,<NA>,-7631000000,58715000000,-66346000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-8734000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4454000000,1620000000,-6074000000,-1132000000,<NA>,-5586000000,-898000000,<NA>,-898000000,-26000000,-924000000
150,MSFT,59265,simfin,us,A,False,USD,2002,FY,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,7829000000,<NA>,<NA>,<NA>,1084000000,14756000000,<NA>,-416000000,15172000000,-9160000000,-1623000000,<NA>,<NA>,-7537000000,<NA>,14509000000,-770000000,<NA>,<NA>,<NA>,-770000000,-770000000,<NA>,<NA>,-10075000000,79311000000,-89386000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-10845000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4572000000,1497000000,-6069000000,<NA>,<NA>,-4572000000,-908000000,<NA>,-908000000,2000000,-906000000
16,MSFT,59265,simfin,us,Q,False,USD,2002,Q3,2002-03-31,2002-05-01,2002-04-30,10810000000,10899000000,2738000000,<NA>,<NA>,<NA>,148000000,2801000000,<NA>,144000000,2657000000,-1566000000,654000000,<NA>,<NA>,-2220000000,<NA>,4121000000,-166000000,<NA>,<NA>,<NA>,-166000000,-166000000,<NA>,<NA>,-3830000000,23979000000,-27809000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3996000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-251000000,425000000,-676000000,<NA>,<NA>,-251000000,-126000000,<NA>,-126000000,-14000000,-140000000
35,MSFT,59265,simfin,us,Q,False,USD,2002,Q4,2002-06-30,2002-09-06,2002-09-06,10810000000,10899000000,1525000000,<NA>,<NA>,<NA>,359000000,5813000000,<NA>,301000000,5512000000,-4263000000,-878000000,<NA>,<NA>,-3385000000,<NA>,3434000000,-282000000,<NA>,<NA>,<NA>,-282000000,-282000000,<NA>,<NA>,-1418000000,27720000000,-29138000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1700000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3841000000,286000000,-4127000000,<NA>,<NA>,-3841000000,-2107000000,<NA>,-2107000000,7000000,-2100000000
141,MSFT,59265,simfin,us,A,False,USD,2003,FY,2003-06-30,2003-09-05,2003-09-05,10810000000,10899000000,9993000000,<NA>,<NA>,<NA>,1439000000,14611000000,<NA>,336000000,14275000000,-10246000000,187000000,<NA>,<NA>,-10433000000,<NA>,15797000000,-891000000,<NA>,<NA>,<NA>,-891000000,-891000000,<NA>,<NA>,-5259000000,84362000000,-89621000000,-1063000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7213000000,-857000000,<NA>,<NA>,<NA>,<NA>,<NA>,-4366000000,2120000000,-6486000000,<NA>,<NA>,-5223000000,3361000000,<NA>,3361000000,61000000,3422000000
224,MSFT,59265,simfin,us,Q,False,USD,2025,Q3,2025-03-31,2025-04-30,2025-04-30,7434000000,7461000000,25824000000,<NA>,<NA>,<NA>,8740000000,438000000,<NA>,<NA>,<NA>,2042000000,<NA>,<NA>,<NA>,<NA>,<NA>,37044000000,-16745000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4408000000,<NA>,<NA>,-981000000,<NA>,<NA>,<NA>,<NA>,-382000000,<NA>,-13700000000,-6169000000,-2250000000,<NA>,<NA>,<NA>,<NA>,-4235000000,546000000,-4781000000,604000000,<NA>,-12050000000,11294000000,<NA>,11294000000,52000000,11346000000
145,MSFT,59265,simfin,us,Q,False,USD,2025,Q4,2025-06-30,2025-07-30,2025-04-30,7430000000,7461000000,27233000000,<NA>,<NA>,<NA>,11203000000,908000000,<NA>,<NA>,<NA>,3303000000,<NA>,<NA>,<NA>,<NA>,<NA>,42647000000,-17079000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-14392000000,<NA>,<NA>,-1743000000,<NA>,<NA>,<NA>,<NA>,-677000000,<NA>,-33891000000,-6169000000,0,<NA>,<NA>,<NA>,<NA>,-3998000000,548000000,-4546000000,2642000000,<NA>,-7525000000,1231000000,<NA>,1231000000,183000000,1414000000
112,MSFT,59265,simfin,us,Q,False,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,27747000000,<NA>,<NA>,<NA>,13061000000,4467000000,2983000000,2491000000,-1007000000,-218000000,16490000000,-192000000,-614000000,-15902000000,<NA>,45057000000,-19394000000,<NA>,<NA>,<NA>,-19394000000,-19394000000,<NA>,<NA>,-8378000000,3262000000,-11640000000,-578000000,<NA>,<NA>,<NA>,<NA>,-6878000000,<NA>,-35228000000,-6169000000,0,<NA>,<NA>,<NA>,<NA>,-4961000000,689000000,-5650000000,<NA>,<NA>,-11130000000,-1301000000,<NA>,-1301000000,-92000000,-1393000000
225,MSFT,59265,simfin,us,Q,False,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,38458000000,<NA>,<NA>,<NA>,9198000000,-2266000000,3219000000,4446000000,-9931000000,-9632000000,-3436000000,70000000,1197000000,-7463000000,<NA>,35758000000,-29876000000,<NA>,<NA>,<NA>,-29876000000,-29876000000,<NA>,<NA>,8263000000,5691000000,2572000000,-455000000,<NA>,<NA>,<NA>,<NA>,-1336000000,<NA>,-23404000000,-6762000000,-3000000000,<NA>,<NA>,<NA>,<NA>,-7156000000,259000000,-7415000000,<NA>,<NA>,-16918000000,-4564000000,<NA>,-4564000000,11000000,-4553000000
146,MSFT,59265,simfin,us,Q,False,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,31778000000,<NA>,<NA>,<NA>,10167000000,4403000000,3081000000,2602000000,-1280000000,331000000,-4707000000,-161000000,2320000000,2879000000,<NA>,46679000000,-30876000000,<NA>,<NA>,<NA>,-30876000000,-30876000000,<NA>,<NA>,6328000000,6358000000,-30000000,-258000000,<NA>,<NA>,<NA>,<NA>,-3108000000,<NA>,-27914000000,-6756000000,0,<NA>,<NA>,<NA>,<NA>,-4086000000,541000000,-4627000000,<NA>,<NA>,-10842000000,7923000000,<NA>,7923000000,-114000000,7809000000

### cashflow (restated)

*Fiscal Year 2001 .. 2026  |  A=25 Q=97  |  USD  |  122 rows*

,count,min,max,mean,std
Shares (Basic),122.0,7426000000.0,10810000000.0,8603409836.065575,1191258246.901797
Shares (Diluted),122.0,7445000000.0,10899000000.0,8686459016.393442,1206160263.377587
Net Income/Starting Line,122.0,-6302000000.0,101832000000.0,13124254098.360655,16645690723.492765
Depreciation & Amortization,122.0,108000000.0,34153000000.0,3250418032.786885,4712939159.168007
Non-Cash Items,122.0,-30344000000.0,54925000000.0,7437196721.311476,10803072146.950634
Change in Working Capital,122.0,-43407000000.0,30035000000.0,-5659852459.016394,10263088027.604034
Change in Fixed Assets & Intangibles,122.0,-64551000000.0,-160000000.0,-5181139344.262295,9064935515.823736
Net Change in Long Term Investment,122.0,-17802000000.0,24272000000.0,-464188524.590164,6867409231.959755
Net Cash from Operating Activities,122.0,1658000000.0,136162000000.0,18152016393.442623,21532260343.199745
Cash from (Repurchase of) Equity,122.0,-30855000000.0,1296000000.0,-5099663934.426229,5397417009.43422
Net Cash from Financing Activities,122.0,-60838000000.0,14329000000.0,-9023065573.770493,12059328512.02561
Net Change in Cash,122.0,-63147000000.0,45748000000.0,441696721.311475,8382686712.927819
Net Cash Before FX,122.0,-63219000000.0,45847000000.0,457950819.672131,8392029673.871994
Net Cash Before Disc. Operations and FX,122.0,-63219000000.0,45847000000.0,457950819.672131,8392029673.871994
Net Cash from Investing Activities,122.0,-96981000000.0,24095000000.0,-8671000000.0,15245554253.482155
Decrease in Capital Stock,121.0,-32696000000.0,0.0,-5853842975.206612,5879979916.360634
Increase in Capital Stock,121.0,96000000.0,6782000000.0,771057851.239669,943044177.981787
Effect of Foreign Exchange Rates,121.0,-294000000.0,183000000.0,-16388429.752066,75055243.199129
Dividends Paid,114.0,-36112000000.0,0.0,-4763868421.052631,6003238066.528656
Net Cash from Acquisitions & Divestitures,114.0,-69132000000.0,0.0,-3065745614.035088,9708308485.141977
Other Non-Cash Adjustments,105.0,-33310000000.0,52127000000.0,7258009523.809524,11150074988.964146
Deferred Income Taxes,105.0,-6463000000.0,4446000000.0,-179685714.285714,1329725002.760734
Acquisition of Fixed Assets & Intangibles,105.0,-30876000000.0,-160000000.0,-3315504761.904762,5419971939.900061
Change in Other,104.0,-43537000000.0,34844000000.0,-6618461538.461538,10532344104.168049
Change in Accounts Receivable,104.0,-10070000000.0,16490000000.0,-325567307.692308,4466809312.285324
Purchase of Fixed Assets,104.0,-30876000000.0,-160000000.0,-3283346153.846154,5436060166.282321
Stock-Based Compensation,103.0,321000000.0,5734000000.0,1353708737.864078,1178245527.119795
Decrease in Long Term Investment,103.0,104000000.0,164394000000.0,27396339805.825241,29092162454.94598
Increase in Long Term Investment,102.0,-176905000000.0,2572000000.0,-28865705882.35294,30537138544.514874
Other Investing Activities,99.0,-6878000000.0,5164000000.0,-198353535.353535,1204563078.660502
Other Financing Activities,99.0,-3116000000.0,2317000000.0,-170828282.828283,745407463.431148
Cash from (Repayment of) Debt,89.0,-14010000000.0,31459000000.0,913910112.359551,6634342345.362104
Change in Accounts Payable,68.0,-2058000000.0,3026000000.0,190117647.058824,833410714.34702
Change in Inventories,68.0,-1023000000.0,1654000000.0,8161764.705882,605822633.279621

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
140,MSFT,59265,simfin,us,A,True,USD,2001,FY,2001-06-30,2001-09-06,2002-09-06,10810000000,10899000000,7346000000,<NA>,<NA>,<NA>,1536000000,11212000000,<NA>,-420000000,11632000000,-6672000000,-418000000,<NA>,<NA>,-6254000000,<NA>,13422000000,-1103000000,<NA>,<NA>,<NA>,-1103000000,-1103000000,<NA>,<NA>,-7631000000,58715000000,-66346000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-8734000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4454000000,1620000000,-6074000000,-1132000000,<NA>,-5586000000,-898000000,<NA>,-898000000,-26000000,-924000000
189,MSFT,59265,simfin,us,A,True,USD,2002,FY,2002-06-30,2002-09-06,2004-09-01,10810000000,10899000000,5355000000,<NA>,<NA>,<NA>,938000000,17376000000,3784000000,-1580000000,15172000000,-9160000000,-1623000000,<NA>,<NA>,-7537000000,<NA>,14509000000,-770000000,<NA>,<NA>,<NA>,-770000000,-770000000,<NA>,<NA>,-10075000000,79311000000,-89386000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-10845000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-4572000000,1497000000,-6069000000,<NA>,<NA>,-4572000000,-908000000,<NA>,-908000000,2000000,-906000000
156,MSFT,59265,simfin,us,Q,True,USD,2002,Q3,2002-03-31,2002-05-01,2003-05-12,10810000000,10899000000,2738000000,<NA>,<NA>,<NA>,148000000,2801000000,<NA>,144000000,2657000000,-1566000000,654000000,<NA>,<NA>,-2220000000,<NA>,4121000000,-166000000,<NA>,<NA>,<NA>,-166000000,-166000000,<NA>,<NA>,-3830000000,23979000000,-27809000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3996000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-251000000,425000000,-676000000,<NA>,<NA>,-251000000,-126000000,<NA>,-126000000,-14000000,-140000000
54,MSFT,59265,simfin,us,Q,True,USD,2002,Q4,2002-06-30,2002-09-06,2004-09-01,10810000000,10899000000,-949000000,<NA>,<NA>,<NA>,213000000,8433000000,3784000000,-863000000,5512000000,-4263000000,-878000000,<NA>,<NA>,-3385000000,<NA>,3434000000,-282000000,<NA>,<NA>,<NA>,-282000000,-282000000,<NA>,<NA>,-1418000000,27720000000,-29138000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1700000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-3841000000,286000000,-4127000000,<NA>,<NA>,-3841000000,-2107000000,<NA>,-2107000000,7000000,-2100000000
73,MSFT,59265,simfin,us,A,True,USD,2003,FY,2003-06-30,2003-09-05,2005-08-26,10810000000,10899000000,7531000000,<NA>,<NA>,<NA>,1393000000,16665000000,3749000000,-1348000000,14264000000,-9792000000,187000000,<NA>,<NA>,-9979000000,<NA>,15797000000,-891000000,<NA>,<NA>,<NA>,-891000000,-891000000,<NA>,<NA>,-5541000000,86328000000,-91869000000,-1063000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7495000000,-857000000,<NA>,<NA>,<NA>,<NA>,<NA>,-4366000000,2120000000,-6486000000,<NA>,<NA>,-5223000000,3079000000,<NA>,3079000000,61000000,3140000000
120,MSFT,59265,simfin,us,Q,True,USD,2025,Q3,2025-03-31,2025-04-30,2026-04-29,7434000000,7461000000,25824000000,<NA>,<NA>,<NA>,7734000000,1444000000,2980000000,-2244000000,708000000,2042000000,-2461000000,52000000,1179000000,3272000000,<NA>,37044000000,-16745000000,<NA>,<NA>,<NA>,-16745000000,-16745000000,<NA>,<NA>,4408000000,2161000000,2247000000,-981000000,<NA>,<NA>,<NA>,<NA>,222000000,<NA>,-13096000000,-6169000000,-2250000000,<NA>,<NA>,<NA>,<NA>,-4235000000,546000000,-4781000000,<NA>,<NA>,-12654000000,11294000000,<NA>,11294000000,52000000,11346000000
69,MSFT,59265,simfin,us,Q,True,USD,2025,Q4,2025-06-30,2025-07-30,2026-04-29,7430000000,7461000000,27233000000,<NA>,<NA>,<NA>,14037000000,-1926000000,<NA>,<NA>,<NA>,3303000000,<NA>,<NA>,<NA>,<NA>,<NA>,42647000000,-17079000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-14392000000,<NA>,<NA>,-1743000000,<NA>,<NA>,<NA>,<NA>,-352000000,<NA>,-33566000000,-6169000000,0,<NA>,<NA>,<NA>,<NA>,-3998000000,548000000,-4546000000,2317000000,<NA>,-7850000000,1231000000,<NA>,1231000000,183000000,1414000000
33,MSFT,59265,simfin,us,Q,True,USD,2026,Q1,2025-09-30,2025-10-29,2025-10-29,7433000000,7466000000,27747000000,<NA>,<NA>,<NA>,13061000000,4467000000,2983000000,2491000000,-1007000000,-218000000,16490000000,-192000000,-614000000,-15902000000,<NA>,45057000000,-19394000000,<NA>,<NA>,<NA>,-19394000000,-19394000000,<NA>,<NA>,-8378000000,3262000000,-11640000000,-578000000,<NA>,<NA>,<NA>,<NA>,-6878000000,<NA>,-35228000000,-6169000000,0,<NA>,<NA>,<NA>,<NA>,-4961000000,689000000,-5650000000,<NA>,<NA>,-11130000000,-1301000000,<NA>,-1301000000,-92000000,-1393000000
159,MSFT,59265,simfin,us,Q,True,USD,2026,Q2,2025-12-31,2026-01-28,2026-01-28,7431000000,7460000000,38458000000,<NA>,<NA>,<NA>,9198000000,-2266000000,3219000000,4446000000,-9931000000,-9632000000,-3436000000,70000000,1197000000,-7463000000,<NA>,35758000000,-29876000000,<NA>,<NA>,<NA>,-29876000000,-29876000000,<NA>,<NA>,8263000000,5691000000,2572000000,-455000000,<NA>,<NA>,<NA>,<NA>,-1336000000,<NA>,-23404000000,-6762000000,-3000000000,<NA>,<NA>,<NA>,<NA>,-7156000000,259000000,-7415000000,<NA>,<NA>,-16918000000,-4564000000,<NA>,-4564000000,11000000,-4553000000
58,MSFT,59265,simfin,us,Q,True,USD,2026,Q3,2026-03-31,2026-04-29,2026-04-29,7426000000,7445000000,31778000000,<NA>,<NA>,<NA>,10167000000,4403000000,3081000000,2602000000,-1280000000,331000000,-4707000000,-161000000,2320000000,2879000000,<NA>,46679000000,-30876000000,<NA>,<NA>,<NA>,-30876000000,-30876000000,<NA>,<NA>,6328000000,6358000000,-30000000,-258000000,<NA>,<NA>,<NA>,<NA>,-3108000000,<NA>,-27914000000,-6756000000,0,<NA>,<NA>,<NA>,<NA>,-4086000000,541000000,-4627000000,<NA>,<NA>,-10842000000,7923000000,<NA>,7923000000,-114000000,7809000000

## market_data

*no rows*