# investalyze — ticker profile

Everything we hold for one ticker, table by table: a metadata summary plus a head/tail
preview of the rows. Set `TICKER` (and optionally `MIN_FILL`) and run all. Helpers live
in `helpers.py`.

Probes every table, so it works for both stocks (prices + dividends/splits +
income/balance/cashflow + companies) and non-equity tickers (market_data).

In [10]:
%load_ext autoreload
%autoreload 2
from helpers import connect_readonly, show_ticker_profile

con = connect_readonly()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
TICKER = 'NVDA'    # the ticker to profile
MIN_FILL = 0.5     # fundamentals: keep stat columns filled in >= this fraction of rows

show_ticker_profile(con, TICKER, MIN_FILL)

# NVDA

## companies

                                                                               0
Ticker                                                                      NVDA
SrcId                                                                     172199
Src                                                                       simfin
Market                                                                        us
Industry                                                          Semiconductors
Sector                                                                Technology
Company Name                                                         NVIDIA CORP
IndustryId                                                                101004
ISIN                                                                US67066G1040
End of financial year (month)                                                  1
Number Employees                                                           18975
Business Summary               NVIDIA Corp is a developer of semiconductor eq...
CIK                                                                      1045810
Main Currency                                                                USD

## prices

*1999-01-22 00:00:00 .. 2026-06-18 00:00:00  |  6894 rows*

     count           min           max          mean           std
O   6894.0  3.489600e-02  2.298700e+02  1.664133e+01  4.237677e+01
H   6894.0  3.554700e-02  2.365400e+02  1.691453e+01  4.301643e+01
L   6894.0  3.333300e-02  2.293000e+02  1.633904e+01  4.164538e+01
C   6894.0  3.411500e-02  2.357400e+02  1.663753e+01  4.234832e+01
V   6894.0  1.968000e+07  9.230856e+09  5.795932e+08  4.291615e+08
AC  6894.0  3.123971e-02  2.354656e+02  1.658937e+01  4.230020e+01

,Ticker,Date,O,H,L,C,V,AC
3917,NVDA,1999-01-22,0.043750,0.048828,0.038802,0.041016,2714688000,0.037559
6020,NVDA,1999-01-25,0.044271,0.045833,0.041016,0.045313,510480000,0.041494
2385,NVDA,1999-01-26,0.045833,0.046745,0.041146,0.041797,343200000,0.038274
6269,NVDA,1999-01-27,0.041927,0.042969,0.039583,0.041667,244368000,0.038155
444,NVDA,1999-01-28,0.041667,0.041927,0.041276,0.041536,227520000,0.038035
3259,NVDA,2026-06-12,204.860001,207.070007,203.440002,205.190002,112001800,205.190002
2384,NVDA,2026-06-15,208.919998,212.710007,208.339996,212.449997,149936700,212.449997
3704,NVDA,2026-06-16,211.179993,211.490005,207.289993,207.410004,125694100,207.410004
654,NVDA,2026-06-17,208.529999,209.210007,203.080002,204.649994,128363500,204.649994
1495,NVDA,2026-06-18,207.330002,211.389999,206.500000,210.690002,241272000,210.690002

## dividends

*2012-11-20 00:00:00 .. 2026-06-04 00:00:00  |  55 rows*

          count       min   max      mean       std
Dividend   55.0  0.001875  0.25  0.008794  0.033219

   Ticker       Date  Dividend
5    NVDA 2012-11-20  0.001875
0    NVDA 2013-02-26  0.001875
32   NVDA 2013-05-21  0.001875
20   NVDA 2013-08-20  0.001875
10   NVDA 2013-11-19  0.002125
29   NVDA 2025-06-11  0.010000
50   NVDA 2025-09-11  0.010000
51   NVDA 2025-12-04  0.010000
25   NVDA 2026-03-11  0.010000
9    NVDA 2026-06-04  0.250000

## splits

*2000-06-27 00:00:00 .. 2024-06-10 00:00:00  |  6 rows*

       count  min   max      mean       std
Ratio    6.0  1.5  10.0  3.583333  3.262157

  Ticker       Date  Ratio
3   NVDA 2000-06-27    2.0
5   NVDA 2001-09-10    2.0
2   NVDA 2006-04-07    2.0
1   NVDA 2007-09-11    1.5
4   NVDA 2021-07-20    4.0
0   NVDA 2024-06-10   10.0

## income

### income (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865829
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
Revenue,124.0,173641000.0,215938000000.0,9784074750.0,25895354443.248482
Cost of Revenue,124.0,-62475000000.0,-192875000.0,-3083681491.935484,7154212889.104553
Gross Profit,124.0,-19234000.0,153463000000.0,6700393258.064516,18815563051.464138
Operating Expenses,124.0,-23076000000.0,-81849000.0,-1703508919.354839,3083987530.806155
"Selling, General & Administrative",124.0,-4579000000.0,-32888000.0,-424379104.83871,663398200.074016
Research & Development,124.0,-18497000000.0,-43125000.0,-1278980459.677419,2433050808.594533
Operating Income (Loss),124.0,-230965000.0,130387000000.0,4996884338.709678,15955101892.635363
Non-Operating Income (Loss),124.0,-123000000.0,16367000000.0,368294854.83871,1873819542.271376
"Pretax Income (Loss), Adj.",124.0,-224821000.0,141450000000.0,5365179193.548388,17431170781.404858
Net Income,124.0,-201338000.0,120067000000.0,4635731975.806452,14848900893.685795
Pretax Income (Loss),124.0,-224821000.0,141450000000.0,5340821379.032258,17434022303.936527
Income (Loss) Incl. Minority Interest,124.0,-201338000.0,120067000000.0,4635731975.806452,14848900893.685795
Income (Loss) from Continuing Operations,124.0,-201338000.0,120067000000.0,4635714943.548388,14848905944.056255
Net Income (Common),124.0,-201338000.0,120067000000.0,4635731975.806452,14848900893.685795
"Income Tax (Expense) Benefit, Net",123.0,-21383000000.0,245000000.0,-710839008.130081,2611372647.520782
Other Non-Operating Income (Loss),123.0,-180000000.0,15929000000.0,322756536.585366,1740233915.569696
"Interest Expense, Net",112.0,-207000000.0,2041000000.0,53299178.571429,226312613.928634

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
210,NVDA,172199,simfin,us,A,False,USD,2000,FY,2001-01-31,2001-05-14,2002-05-14,205838680800,246223448160,735264000,<NA>,<NA>,<NA>,-462385000,<NA>,<NA>,<NA>,272879000,<NA>,-144744000,-58697000,<NA>,<NA>,-86047000,<NA>,<NA>,<NA>,128135000,16673000,16679000,<NA>,<NA>,<NA>,<NA>,<NA>,-6000,144808000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,144808000,-46339000,<NA>,<NA>,None,<NA>,98469000,<NA>,<NA>,<NA>,98469000,<NA>,98469000,<NA>,<NA>,98469000
229,NVDA,172199,simfin,us,A,False,USD,2001,FY,2002-01-31,2002-05-14,2002-05-14,205838680800,246223448160,1369471000,<NA>,<NA>,<NA>,-850233000,<NA>,<NA>,<NA>,519238000,<NA>,-263789000,-97185000,<NA>,<NA>,-153920000,-12684000,<NA>,<NA>,255449000,11017000,11708000,<NA>,<NA>,<NA>,<NA>,<NA>,-691000,266466000,-13717000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,252749000,-75825000,<NA>,<NA>,None,<NA>,176924000,<NA>,<NA>,<NA>,176924000,<NA>,176924000,<NA>,<NA>,176924000
78,NVDA,172199,simfin,us,Q,False,USD,2001,Q4,2002-01-31,2002-03-12,2002-05-14,205838680800,246223448160,503688000,<NA>,<NA>,<NA>,-314377000,<NA>,<NA>,<NA>,189311000,<NA>,-81849000,-32888000,<NA>,<NA>,-43125000,-5836000,<NA>,<NA>,107462000,1157000,11708000,<NA>,<NA>,<NA>,<NA>,<NA>,-10551000,108619000,0,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,108619000,-32586000,<NA>,<NA>,None,<NA>,76033000,<NA>,<NA>,<NA>,76033000,<NA>,76033000,<NA>,<NA>,76033000
169,NVDA,172199,simfin,us,A,False,USD,2002,FY,2003-01-31,2003-04-25,2003-04-25,220948246080,242364737760,1909447000,<NA>,<NA>,<NA>,-1333435000,<NA>,<NA>,<NA>,576012000,<NA>,-376358000,-151485000,<NA>,<NA>,-224873000,<NA>,<NA>,<NA>,199654000,6571000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6571000,206225000,-55668000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,150557000,-59758000,<NA>,<NA>,None,<NA>,90799000,<NA>,<NA>,<NA>,90799000,<NA>,90799000,<NA>,<NA>,90799000
30,NVDA,172199,simfin,us,Q,False,USD,2002,Q1,2002-04-30,2002-06-10,2002-06-10,216984960000,262893600000,582905000,<NA>,<NA>,<NA>,-375740000,<NA>,<NA>,<NA>,207165000,<NA>,-89974000,-37482000,<NA>,<NA>,-52492000,<NA>,<NA>,<NA>,117191000,1731000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1731000,118922000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,118922000,-35677000,<NA>,<NA>,None,<NA>,83245000,<NA>,<NA>,<NA>,83245000,<NA>,83245000,<NA>,<NA>,83245000
61,NVDA,172199,simfin,us,Q,False,USD,2025,Q1,2025-04-30,2025-05-28,2025-05-28,24441000000,24611000000,44062000000,<NA>,<NA>,<NA>,-17394000000,<NA>,<NA>,<NA>,26668000000,<NA>,-5030000000,-1041000000,<NA>,<NA>,-3989000000,<NA>,<NA>,<NA>,21638000000,272000000,452000000,<NA>,<NA>,<NA>,<NA>,<NA>,-180000000,21910000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,21910000000,-3135000000,<NA>,<NA>,None,<NA>,18775000000,<NA>,<NA>,<NA>,18775000000,<NA>,18775000000,<NA>,<NA>,18775000000
227,NVDA,172199,simfin,us,Q,False,USD,2025,Q2,2025-07-31,2025-08-27,2025-08-27,24366000000,24532000000,46743000000,<NA>,<NA>,<NA>,-12890000000,<NA>,<NA>,<NA>,33853000000,<NA>,-5413000000,-1122000000,<NA>,<NA>,-4291000000,<NA>,<NA>,<NA>,28440000000,2766000000,530000000,<NA>,<NA>,<NA>,<NA>,<NA>,2236000000,31206000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,31206000000,-4784000000,<NA>,<NA>,None,<NA>,26422000000,<NA>,<NA>,<NA>,26422000000,<NA>,26422000000,<NA>,<NA>,26422000000
19,NVDA,172199,simfin,us,Q,False,USD,2025,Q3,2025-10-31,2025-11-19,2025-11-19,24327000000,24483000000,57006000000,<NA>,<NA>,<NA>,-15157000000,<NA>,<NA>,<NA>,41849000000,<NA>,-5839000000,-1134000000,<NA>,<NA>,-4705000000,<NA>,<NA>,<NA>,36010000000,1926000000,563000000,<NA>,<NA>,<NA>,<NA>,<NA>,1363000000,37936000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,37936000000,-6026000000,<NA>,<NA>,None,<NA>,31910000000,<NA>,<NA>,<NA>,31910000000,<NA>,31910000000,<NA>,<NA>,31910000000
228,NVDA,172199,simfin,us,Q,False,USD,2025,Q4,2026-01-31,2026-02-25,2025-11-19,24302000000,24430000000,68127000000,<NA>,<NA>,<NA>,-17034000000,<NA>,<NA>,<NA>,51093000000,<NA>,-6794000000,-1282000000,<NA>,<NA>,-5512000000,<NA>,<NA>,<NA>,44299000000,6099000000,495000000,<NA>,<NA>,<NA>,<NA>,<NA>,5604000000,50398000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,50398000000,-7438000000,<NA>,<NA>,None,<NA>,42960000000,<NA>,<NA>,<NA>,42960000000,<NA>,42960000000,<NA>,<NA>,42960000000
62,NVDA,172199,simfin,us,Q,False,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,81615000000,<NA>,<NA>,<NA>,-20458000000,<NA>,<NA>,<NA>,61157000000,<NA>,-7621000000,-1300000000,<NA>,<NA>,-6321000000,<NA>,<NA>,<NA>,53536000000,16367000000,438000000,<NA>,<NA>,<NA>,<NA>,<NA>,15929000000,69903000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,69903000000,-11582000000,<NA>,<NA>,None,<NA>,58321000000,<NA>,<NA>,<NA>,58321000000,<NA>,58321000000,<NA>,<NA>,58321000000

### income (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865829
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
Revenue,124.0,404983000.0,215938000000.0,9789433258.064516,25893708072.12265
Cost of Revenue,124.0,-62475000000.0,-278415000.0,-3088868967.741935,7153116680.913343
Gross Profit,124.0,99302000.0,153463000000.0,6700564290.32258,18815435834.201485
Operating Expenses,124.0,-23076000000.0,-81849000.0,-1708986354.83871,3082136997.354363
"Selling, General & Administrative",124.0,-4579000000.0,-34647000.0,-425537532.258065,663001021.735266
Research & Development,124.0,-18497000000.0,-43957000.0,-1283341258.064516,2431574031.6153
Operating Income (Loss),124.0,-230965000.0,130387000000.0,4991577935.483871,15956723066.870707
Non-Operating Income (Loss),124.0,-123000000.0,16367000000.0,368485008.064516,1873779786.153513
"Pretax Income (Loss), Adj.",124.0,-224821000.0,141450000000.0,5360062943.548388,17432698505.578518
Net Income,124.0,-201338000.0,120067000000.0,4630905967.741936,14850366642.077253
Pretax Income (Loss),124.0,-224821000.0,141450000000.0,5335128241.935484,17435721951.210003
Income (Loss) Incl. Minority Interest,124.0,-201338000.0,120067000000.0,4630905967.741936,14850366642.077253
Income (Loss) from Continuing Operations,124.0,-201338000.0,120067000000.0,4630894612.903226,14850370003.528486
Net Income (Common),124.0,-201338000.0,120067000000.0,4630905967.741936,14850366642.077253
"Income Tax (Expense) Benefit, Net",123.0,-21383000000.0,245000000.0,-709959105.691057,2611606932.186947
Other Non-Operating Income (Loss),123.0,-180000000.0,15929000000.0,297714349.593496,1728091493.265767
"Interest Expense, Net",115.0,-207000000.0,2041000000.0,78898052.173913,273486773.878406

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
212,NVDA,172199,simfin,us,A,True,USD,2000,FY,2001-01-31,2001-05-14,2002-05-14,205838680800,246223448160,735264000,<NA>,<NA>,<NA>,-462385000,<NA>,<NA>,<NA>,272879000,<NA>,-144744000,-58697000,<NA>,<NA>,-86047000,<NA>,<NA>,<NA>,128135000,16673000,16679000,<NA>,<NA>,<NA>,<NA>,<NA>,-6000,144808000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,144808000,-46339000,<NA>,<NA>,None,<NA>,98469000,<NA>,<NA>,<NA>,98469000,<NA>,98469000,<NA>,<NA>,98469000
34,NVDA,172199,simfin,us,A,True,USD,2001,FY,2002-01-31,2002-05-14,2003-04-25,205838680800,246223448160,1369471000,<NA>,<NA>,<NA>,-850233000,<NA>,<NA>,<NA>,519238000,<NA>,-263789000,-98944000,<NA>,<NA>,-154752000,-10093000,<NA>,<NA>,255449000,11017000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,11017000,266466000,-13717000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,252749000,-75825000,<NA>,<NA>,None,<NA>,176924000,<NA>,<NA>,<NA>,176924000,<NA>,176924000,<NA>,<NA>,176924000
122,NVDA,172199,simfin,us,Q,True,USD,2001,Q4,2002-01-31,2002-03-12,2003-04-25,205838680800,246223448160,503688000,<NA>,<NA>,<NA>,-314377000,<NA>,<NA>,<NA>,189311000,<NA>,-81849000,-34647000,<NA>,<NA>,-43957000,-3245000,<NA>,<NA>,107462000,1157000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1157000,108619000,0,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,108619000,-32586000,<NA>,<NA>,None,<NA>,76033000,<NA>,<NA>,<NA>,76033000,<NA>,76033000,<NA>,<NA>,76033000
185,NVDA,172199,simfin,us,A,True,USD,2002,FY,2003-01-31,2003-04-25,2004-03-29,220948246080,242364737760,1909447000,<NA>,<NA>,<NA>,-1333435000,<NA>,<NA>,<NA>,576012000,<NA>,-376358000,-151485000,<NA>,<NA>,-224873000,<NA>,<NA>,<NA>,199654000,6571000,6779000,<NA>,<NA>,<NA>,<NA>,<NA>,-208000,206225000,-55668000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,150557000,-59758000,<NA>,<NA>,None,<NA>,90799000,<NA>,<NA>,<NA>,90799000,<NA>,90799000,<NA>,<NA>,90799000
144,NVDA,172199,simfin,us,Q,True,USD,2002,Q1,2002-04-30,2002-06-10,2003-05-22,216984960000,262893600000,582905000,<NA>,<NA>,<NA>,-375740000,<NA>,<NA>,<NA>,207165000,<NA>,-89974000,-37482000,<NA>,<NA>,-52492000,<NA>,<NA>,<NA>,117191000,1731000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1731000,118922000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,118922000,-35677000,<NA>,<NA>,None,<NA>,83245000,<NA>,<NA>,<NA>,83245000,<NA>,83245000,<NA>,<NA>,83245000
178,NVDA,172199,simfin,us,Q,True,USD,2025,Q1,2025-04-30,2025-05-28,2026-05-20,24441000000,24611000000,44062000000,<NA>,<NA>,<NA>,-17394000000,<NA>,<NA>,<NA>,26668000000,<NA>,-5030000000,-1041000000,<NA>,<NA>,-3989000000,<NA>,<NA>,<NA>,21638000000,272000000,452000000,<NA>,<NA>,<NA>,<NA>,<NA>,-180000000,21910000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,21910000000,-3135000000,<NA>,<NA>,None,<NA>,18775000000,<NA>,<NA>,<NA>,18775000000,<NA>,18775000000,<NA>,<NA>,18775000000
135,NVDA,172199,simfin,us,Q,True,USD,2025,Q2,2025-07-31,2025-08-27,2025-08-27,24366000000,24532000000,46743000000,<NA>,<NA>,<NA>,-12890000000,<NA>,<NA>,<NA>,33853000000,<NA>,-5413000000,-1122000000,<NA>,<NA>,-4291000000,<NA>,<NA>,<NA>,28440000000,2766000000,530000000,<NA>,<NA>,<NA>,<NA>,<NA>,2236000000,31206000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,31206000000,-4784000000,<NA>,<NA>,None,<NA>,26422000000,<NA>,<NA>,<NA>,26422000000,<NA>,26422000000,<NA>,<NA>,26422000000
29,NVDA,172199,simfin,us,Q,True,USD,2025,Q3,2025-10-31,2025-11-19,2025-11-19,24327000000,24483000000,57006000000,<NA>,<NA>,<NA>,-15157000000,<NA>,<NA>,<NA>,41849000000,<NA>,-5839000000,-1134000000,<NA>,<NA>,-4705000000,<NA>,<NA>,<NA>,36010000000,1926000000,563000000,<NA>,<NA>,<NA>,<NA>,<NA>,1363000000,37936000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,37936000000,-6026000000,<NA>,<NA>,None,<NA>,31910000000,<NA>,<NA>,<NA>,31910000000,<NA>,31910000000,<NA>,<NA>,31910000000
136,NVDA,172199,simfin,us,Q,True,USD,2025,Q4,2026-01-31,2026-02-25,2025-11-19,24302000000,24430000000,68127000000,<NA>,<NA>,<NA>,-17034000000,<NA>,<NA>,<NA>,51093000000,<NA>,-6794000000,-1282000000,<NA>,<NA>,-5512000000,<NA>,<NA>,<NA>,44299000000,6099000000,495000000,<NA>,<NA>,<NA>,<NA>,<NA>,5604000000,50398000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,50398000000,-7438000000,<NA>,<NA>,None,<NA>,42960000000,<NA>,<NA>,<NA>,42960000000,<NA>,42960000000,<NA>,<NA>,42960000000
87,NVDA,172199,simfin,us,Q,True,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,81615000000,<NA>,<NA>,<NA>,-20458000000,<NA>,<NA>,<NA>,61157000000,<NA>,-7621000000,-1300000000,<NA>,<NA>,-6321000000,<NA>,<NA>,<NA>,53536000000,16367000000,438000000,<NA>,<NA>,<NA>,<NA>,<NA>,15929000000,69903000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,69903000000,-11582000000,<NA>,<NA>,None,<NA>,58321000000,<NA>,<NA>,<NA>,58321000000,<NA>,58321000000,<NA>,<NA>,58321000000

## balance

### balance (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865814
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
"Cash, Cash Equivalents & Short Term Investments",124.0,587850000.0,80572000000.0,9704038387.096775,14935904834.494446
Cash & Cash Equivalents,124.0,156687000.0,15494000000.0,2423351451.612903,3557774599.41385
Accounts & Notes Receivable,124.0,104988000.0,40710000000.0,3531780967.741935,7952045887.412111
"Accounts Receivable, Net",124.0,104988000.0,40710000000.0,3531780967.741935,7952045887.412111
Inventories,124.0,90380000.0,25797000000.0,2133293935.483871,4405760302.837381
Other Short Term Assets,124.0,17800000.0,4062000000.0,504367217.741935,1030287249.939223
Total Current Assets,124.0,930884000.0,150995000000.0,15873480508.064516,27964198299.143543
Prepaid Expenses,124.0,8078000.0,4062000000.0,487328241.935484,1037072450.053275
"Property, Plant & Equipment, Net",124.0,47280000.0,12403000000.0,1570520153.225806,2331451660.926714
Other Long Term Assets,124.0,38738000.0,52712000000.0,5427617524.193548,10223303196.588755
Payables & Accruals,124.0,108829000.0,42884000000.0,3313767943.548387,7154663592.843657
Intangible Assets,124.0,15421000.0,3306000000.0,549490169.354839,857402968.263581
Misc. Long Term Assets,124.0,7255000.0,16991000000.0,1598988088.709677,3138205873.722743
Total Noncurrent Assets,124.0,86018000.0,108479000000.0,7706734451.612904,16070483819.309696
Accounts Payable,124.0,72301000.0,13097000000.0,1177289725.806452,2213864323.591792
Total Assets,124.0,1016902000.0,259474000000.0,23580214959.677418,43584017910.757248
Share Capital & Additional Paid-In Capital,124.0,277097000.0,13134000000.0,4769779854.83871,3949088232.628757
Total Current Liabilities,124.0,309417000.0,43884000000.0,3791321395.16129,7250078381.091741
Total Liabilities & Equity,124.0,1016902000.0,259474000000.0,23580214959.677418,43584017910.757248
Equity Before Minority Interest,124.0,407107000.0,195474000000.0,15947623201.612904,31868029667.727375
Total Liabilities,124.0,348159000.0,64000000000.0,7632591758.064516,12126806702.933542
Total Noncurrent Liabilities,124.0,7221000.0,20116000000.0,3841270362.903226,5436734012.139429
Other Equity,124.0,-123000000.0,339000000.0,7466330.645161,52168981.933046
Retained Earnings,124.0,130016000.0,185038000000.0,13785014080.645161,29033497548.515442
Total Equity,124.0,407107000.0,195474000000.0,15947623201.612904,31868029667.727375
Short Term Investments,123.0,1000000.0,67335000000.0,7339879512.195122,12178619724.51124
Goodwill,118.0,54227000.0,20894000000.0,1907036533.898305,3546460659.628401
Other Long Term Liabilities,116.0,4500000.0,12646000000.0,1366469956.896552,2282197466.34103
Misc. Long Term Liabilities,116.0,-1465000.0,12646000000.0,1365023818.965517,2283061443.221157
Long Term Debt,103.0,340000.0,10947000000.0,3085504951.456311,3747491175.182191
Treasury Stock,86.0,-12038000000.0,-24644000.0,-3769941813.953488,3579772786.909466
Other Payables & Accruals,83.0,32233000.0,29787000000.0,3191475048.192771,5810630761.932009
Common Stock,65.0,638000.0,3000000.0,1021430.769231,593694.996643
Additional Paid in Capital,65.0,2043840000.0,10623000000.0,4912832400.0,2396825606.984624

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
155,NVDA,172199,simfin,us,A,False,USD,2000,Q4,2001-01-31,2001-05-14,2002-05-14,205838680800,246223448160,674275000,674275000,<NA>,104988000,104988000,<NA>,None,90380000,<NA>,<NA>,<NA>,<NA>,61241000,8355000,<NA>,<NA>,<NA>,28386000,<NA>,24500000,930884000,47280000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,38738000,23795000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14943000,86018000,1016902000,108829000,72301000,<NA>,4295000,32233000,588000,<NA>,<NA>,<NA>,200000000,200000000,<NA>,<NA>,<NA>,<NA>,309417000,300378000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,300378000,609795000,<NA>,277097000,<NA>,<NA>,<NA>,<NA>,130016000,-6000,407107000,<NA>,407107000,1016902000
86,NVDA,172199,simfin,us,A,False,USD,2001,Q4,2002-01-31,2002-05-14,2002-05-14,205838680800,246223448160,791377000,333000000,458377000,147348000,147348000,<NA>,None,213877000,<NA>,<NA>,<NA>,<NA>,81507000,8078000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1234109000,120128000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,148937000,81119000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67818000,269065000,1503174000,359405000,214019000,<NA>,4176000,141210000,3896000,<NA>,<NA>,<NA>,70193000,70193000,<NA>,<NA>,<NA>,<NA>,433494000,305861000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,305861000,739355000,<NA>,456771000,<NA>,<NA>,<NA>,<NA>,306940000,108000,763819000,<NA>,763819000,1503174000
208,NVDA,172199,simfin,us,Q,False,USD,2001,Q4,2002-01-31,2002-05-14,2002-05-14,205838680800,246223448160,791377000,333000000,458377000,147348000,147348000,<NA>,None,213877000,<NA>,<NA>,<NA>,<NA>,81507000,8078000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1234109000,120128000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,148937000,81119000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67818000,269065000,1503174000,359405000,214019000,<NA>,4176000,141210000,3896000,<NA>,<NA>,<NA>,70193000,70193000,<NA>,<NA>,<NA>,<NA>,433494000,305861000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,305861000,739355000,<NA>,456771000,<NA>,<NA>,<NA>,<NA>,306940000,108000,763819000,<NA>,763819000,1503174000
1,NVDA,172199,simfin,us,Q,False,USD,2002,Q1,2002-04-30,2002-06-10,2002-06-10,216984960000,262893600000,828397000,307151000,521246000,151429000,151429000,<NA>,None,253927000,<NA>,<NA>,<NA>,<NA>,85311000,11882000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1319064000,131267000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,149386000,82857000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,66529000,280653000,1599717000,372816000,190360000,<NA>,528000,181928000,3944000,<NA>,<NA>,<NA>,49369000,49369000,<NA>,<NA>,<NA>,<NA>,426129000,304937000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,304937000,731066000,<NA>,478632000,<NA>,<NA>,<NA>,<NA>,390185000,-166000,868651000,<NA>,868651000,1599717000
126,NVDA,172199,simfin,us,Q,False,USD,2002,Q2,2002-07-31,2002-09-10,2002-09-10,219306240000,243028800000,826411000,246816000,579595000,133038000,133038000,<NA>,None,285350000,<NA>,<NA>,<NA>,<NA>,79681000,13252000,<NA>,<NA>,<NA>,66429000,<NA>,<NA>,1324480000,143578000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147096000,80462000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,66634000,290674000,1615154000,355669000,165395000,<NA>,4117000,186157000,5607000,<NA>,<NA>,<NA>,62420000,62420000,<NA>,<NA>,<NA>,<NA>,423696000,307926000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,307926000,731622000,<NA>,485915000,<NA>,<NA>,<NA>,<NA>,395438000,2179000,883532000,<NA>,883532000,1615154000
77,NVDA,172199,simfin,us,Q,False,USD,2025,Q2,2025-07-31,2025-08-27,2025-08-27,24366000000,24532000000,56791000000,11639000000,45152000000,27808000000,27808000000,<NA>,None,14962000000,<NA>,<NA>,<NA>,<NA>,2658000000,2658000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,102219000000,9141000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,29380000000,755000000,5755000000,<NA>,<NA>,13570000000,<NA>,<NA>,<NA>,<NA>,9300000000,38521000000,140740000000,24257000000,9064000000,<NA>,<NA>,15193000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,24257000000,8466000000,<NA>,<NA>,7886000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7886000000,16352000000,40609000000,<NA>,11224000000,<NA>,<NA>,<NA>,<NA>,88737000000,170000000,100131000000,<NA>,100131000000,140740000000
57,NVDA,172199,simfin,us,Q,False,USD,2025,Q3,2025-10-31,2025-11-19,2025-11-19,24327000000,24483000000,60608000000,11486000000,49122000000,33391000000,33391000000,<NA>,None,19784000000,<NA>,<NA>,<NA>,<NA>,2709000000,2709000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,116492000000,9780000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,34876000000,936000000,6261000000,<NA>,<NA>,13674000000,<NA>,<NA>,<NA>,<NA>,14005000000,44656000000,161148000000,25076000000,8624000000,<NA>,<NA>,16452000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26075000000,7468000000,<NA>,<NA>,8708000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8708000000,16176000000,42251000000,<NA>,10650000000,<NA>,<NA>,<NA>,<NA>,107908000000,339000000,118897000000,<NA>,118897000000,161148000000
78,NVDA,172199,simfin,us,Q,False,USD,2025,Q4,2026-01-31,2026-02-25,2026-02-25,24302000000,24430000000,62556000000,10605000000,51951000000,38466000000,38466000000,<NA>,None,21403000000,<NA>,<NA>,<NA>,<NA>,3180000000,3180000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,125605000000,10383000000,<NA>,<NA>,22251000000,<NA>,<NA>,<NA>,48564000000,3306000000,20832000000,<NA>,<NA>,13258000000,<NA>,<NA>,<NA>,<NA>,11168000000,81198000000,206803000000,31164000000,9812000000,<NA>,<NA>,21352000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32163000000,7469000000,<NA>,<NA>,9878000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9878000000,17347000000,49510000000,<NA>,10142000000,<NA>,<NA>,<NA>,<NA>,146973000000,178000000,157293000000,<NA>,157293000000,206803000000
140,NVDA,172199,simfin,us,A,False,USD,2025,Q4,2026-01-31,2026-02-25,2026-02-25,24359000000,24514000000,62556000000,10605000000,51951000000,38466000000,38466000000,<NA>,None,21403000000,<NA>,<NA>,<NA>,<NA>,3180000000,3180000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,125605000000,10383000000,<NA>,<NA>,22251000000,<NA>,<NA>,<NA>,48564000000,3306000000,20832000000,<NA>,<NA>,13258000000,<NA>,<NA>,<NA>,<NA>,11168000000,81198000000,206803000000,31164000000,9812000000,<NA>,<NA>,21352000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32163000000,7469000000,<NA>,<NA>,9878000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9878000000,17347000000,49510000000,<NA>,10142000000,<NA>,<NA>,<NA>,<NA>,146973000000,178000000,157293000000,<NA>,157293000000,206803000000
10,NVDA,172199,simfin,us,Q,False,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,80572000000,13237000000,67335000000,40710000000,40710000000,<NA>,None,25797000000,<NA>,<NA>,<NA>,<NA>,3916000000,3916000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,150995000000,12403000000,<NA>,<NA>,43364000000,<NA>,<NA>,<NA>,52712000000,3120000000,20894000000,<NA>,<NA>,11707000000,<NA>,<NA>,<NA>,<NA>,16991000000,108479000000,259474000000,42884000000,13097000000,<NA>,<NA>,29787000000,1000000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,43884000000,7470000000,<NA>,<NA>,12646000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,12646000000,20116000000,64000000000,<NA>,10299000000,<NA>,<NA>,<NA>,<NA>,185038000000,137000000,195474000000,<NA>,195474000000,259474000000

### balance (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865814
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
"Cash, Cash Equivalents & Short Term Investments",124.0,587850000.0,80572000000.0,9704032919.354839,14935906709.621809
Cash & Cash Equivalents,124.0,156687000.0,15494000000.0,2423357032.258065,3557771552.936923
Accounts & Notes Receivable,124.0,104988000.0,40710000000.0,3531786822.580645,7952043617.624298
"Accounts Receivable, Net",124.0,104988000.0,40710000000.0,3531786822.580645,7952043617.624298
Inventories,124.0,90380000.0,25797000000.0,2133185330.645161,4405802848.254435
Other Short Term Assets,124.0,17800000.0,4062000000.0,504620016.129032,1030187073.977856
Total Current Assets,124.0,930884000.0,150995000000.0,15873625088.709677,27964119825.570763
Prepaid Expenses,124.0,8078000.0,4062000000.0,487593790.322581,1036960012.883675
"Property, Plant & Equipment, Net",124.0,47280000.0,12403000000.0,1570515604.83871,2331453653.977581
Other Long Term Assets,124.0,38738000.0,52712000000.0,5374360112.903226,10124628678.38246
Payables & Accruals,124.0,108829000.0,42884000000.0,3246882975.806452,7181238465.331341
Intangible Assets,124.0,15421000.0,3306000000.0,548683072.580645,857871711.201728
Misc. Long Term Assets,124.0,7255000.0,16991000000.0,1534748846.774194,3053772840.496551
Total Noncurrent Assets,124.0,86018000.0,108479000000.0,7708101524.193548,16069847686.742271
Accounts Payable,124.0,72301000.0,13097000000.0,1176447419.354839,2213866484.720826
Total Assets,124.0,1016902000.0,259474000000.0,23581726612.903225,43583258348.975327
Share Capital & Additional Paid-In Capital,124.0,277097000.0,13134000000.0,4776716870.967742,3942115279.386399
Total Current Liabilities,124.0,309417000.0,43884000000.0,3790189895.16129,7250612089.787755
Total Liabilities & Equity,124.0,1016902000.0,259474000000.0,23581726612.903225,43583258348.975327
Equity Before Minority Interest,124.0,407107000.0,195474000000.0,15949226193.548388,31867291341.867798
Total Liabilities,124.0,348159000.0,64000000000.0,7632500419.354838,12126860058.617477
Total Noncurrent Liabilities,124.0,7221000.0,20116000000.0,3842310524.193548,5436062097.688982
Other Equity,124.0,-123000000.0,339000000.0,7238927.419355,52244734.097763
Retained Earnings,124.0,130016000.0,185038000000.0,13779914153.225807,29035812719.808971
Total Equity,124.0,407107000.0,195474000000.0,15949226193.548388,31867291341.867798
Short Term Investments,123.0,1000000.0,67335000000.0,7339868373.98374,12178622687.603453
Goodwill,120.0,50326000.0,20894000000.0,1876088375.0,3524624745.362411
Other Long Term Liabilities,118.0,4500000.0,12646000000.0,1344511449.152542,2268844302.194366
Misc. Long Term Liabilities,116.0,-1465000.0,12646000000.0,1365578870.689655,2282743775.359021
Long Term Debt,103.0,340000.0,10947000000.0,3085380135.92233,3747529468.784045
Treasury Stock,86.0,-12038000000.0,-24644000.0,-3769951465.116279,3579771763.584642
Other Payables & Accruals,67.0,32233000.0,29787000000.0,3831390134.328358,6309026272.07148
Common Stock,65.0,629000.0,3000000.0,1017584.615385,595849.23356
Additional Paid in Capital,65.0,1889257000.0,10623000000.0,4651360553.846154,2241603409.134875

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
135,NVDA,172199,simfin,us,A,True,USD,2000,Q4,2001-01-31,2001-05-14,2002-05-14,205838680800,246223448160,674275000,674275000,<NA>,104988000,104988000,<NA>,None,90380000,<NA>,<NA>,<NA>,<NA>,61241000,8355000,<NA>,<NA>,<NA>,28386000,<NA>,24500000,930884000,47280000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,38738000,23795000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14943000,86018000,1016902000,108829000,72301000,<NA>,4295000,32233000,588000,<NA>,<NA>,<NA>,200000000,200000000,<NA>,<NA>,<NA>,<NA>,309417000,300378000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,300378000,609795000,<NA>,277097000,<NA>,<NA>,<NA>,<NA>,130016000,-6000,407107000,<NA>,407107000,1016902000
79,NVDA,172199,simfin,us,Q,True,USD,2001,Q4,2002-01-31,2002-05-14,2003-04-25,205838680800,246223448160,791377000,333000000,458377000,147348000,147348000,<NA>,None,213877000,<NA>,<NA>,<NA>,<NA>,81507000,8078000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1234109000,120128000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,148937000,30793000,50326000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67818000,269065000,1503174000,359405000,214019000,<NA>,4176000,141210000,3896000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,363301000,305861000,<NA>,<NA>,70193000,<NA>,<NA>,<NA>,<NA>,<NA>,70193000,<NA>,<NA>,<NA>,<NA>,376054000,739355000,<NA>,456771000,<NA>,<NA>,<NA>,<NA>,306940000,108000,763819000,<NA>,763819000,1503174000
104,NVDA,172199,simfin,us,A,True,USD,2001,Q4,2002-01-31,2002-05-14,2003-04-25,205838680800,246223448160,791377000,333000000,458377000,147348000,147348000,<NA>,None,213877000,<NA>,<NA>,<NA>,<NA>,81507000,8078000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1234109000,120128000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,148937000,30793000,50326000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67818000,269065000,1503174000,359405000,214019000,<NA>,4176000,141210000,3896000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,363301000,305861000,<NA>,<NA>,70193000,<NA>,<NA>,<NA>,<NA>,<NA>,70193000,<NA>,<NA>,<NA>,<NA>,376054000,739355000,<NA>,456771000,<NA>,<NA>,<NA>,<NA>,306940000,108000,763819000,<NA>,763819000,1503174000
160,NVDA,172199,simfin,us,Q,True,USD,2002,Q1,2002-04-30,2002-06-10,2002-07-03,216984960000,262893600000,828397000,307151000,521246000,151429000,151429000,<NA>,None,253927000,<NA>,<NA>,<NA>,<NA>,85311000,11882000,<NA>,<NA>,<NA>,66429000,<NA>,7000000,1319064000,131267000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,149386000,82857000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,66529000,280653000,1599717000,372816000,190360000,<NA>,528000,181928000,3944000,<NA>,<NA>,<NA>,49369000,49369000,<NA>,<NA>,<NA>,<NA>,426129000,304937000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,304937000,731066000,<NA>,478632000,<NA>,<NA>,<NA>,<NA>,390185000,-166000,868651000,<NA>,868651000,1599717000
232,NVDA,172199,simfin,us,Q,True,USD,2002,Q2,2002-07-31,2002-09-10,2002-09-10,219306240000,243028800000,826411000,246816000,579595000,133038000,133038000,<NA>,None,285350000,<NA>,<NA>,<NA>,<NA>,79681000,13252000,<NA>,<NA>,<NA>,66429000,<NA>,<NA>,1324480000,143578000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,147096000,80462000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,66634000,290674000,1615154000,355669000,165395000,<NA>,4117000,186157000,5607000,<NA>,<NA>,<NA>,62420000,62420000,<NA>,<NA>,<NA>,<NA>,423696000,307926000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,307926000,731622000,<NA>,485915000,<NA>,<NA>,<NA>,<NA>,395438000,2179000,883532000,<NA>,883532000,1615154000
243,NVDA,172199,simfin,us,Q,True,USD,2025,Q2,2025-07-31,2025-08-27,2025-08-27,24366000000,24532000000,56791000000,11639000000,45152000000,27808000000,27808000000,<NA>,None,14962000000,<NA>,<NA>,<NA>,<NA>,2658000000,2658000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,102219000000,9141000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,29380000000,755000000,5755000000,<NA>,<NA>,13570000000,<NA>,<NA>,<NA>,<NA>,9300000000,38521000000,140740000000,24257000000,9064000000,<NA>,<NA>,15193000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,24257000000,8466000000,<NA>,<NA>,7886000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7886000000,16352000000,40609000000,<NA>,11224000000,<NA>,<NA>,<NA>,<NA>,88737000000,170000000,100131000000,<NA>,100131000000,140740000000
8,NVDA,172199,simfin,us,Q,True,USD,2025,Q3,2025-10-31,2025-11-19,2025-11-19,24327000000,24483000000,60608000000,11486000000,49122000000,33391000000,33391000000,<NA>,None,19784000000,<NA>,<NA>,<NA>,<NA>,2709000000,2709000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,116492000000,9780000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,34876000000,936000000,6261000000,<NA>,<NA>,13674000000,<NA>,<NA>,<NA>,<NA>,14005000000,44656000000,161148000000,25076000000,8624000000,<NA>,<NA>,16452000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26075000000,7468000000,<NA>,<NA>,8708000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8708000000,16176000000,42251000000,<NA>,10650000000,<NA>,<NA>,<NA>,<NA>,107908000000,339000000,118897000000,<NA>,118897000000,161148000000
225,NVDA,172199,simfin,us,A,True,USD,2025,Q4,2026-01-31,2026-02-25,2026-05-20,24359000000,24514000000,62556000000,10605000000,51951000000,38466000000,38466000000,<NA>,None,21403000000,<NA>,<NA>,<NA>,<NA>,3180000000,3180000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,125605000000,10383000000,<NA>,<NA>,22251000000,<NA>,<NA>,<NA>,48564000000,3306000000,20832000000,<NA>,<NA>,13258000000,<NA>,<NA>,<NA>,<NA>,11168000000,81198000000,206803000000,31164000000,9812000000,<NA>,<NA>,21352000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32163000000,7469000000,<NA>,<NA>,9878000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9878000000,17347000000,49510000000,<NA>,10142000000,<NA>,<NA>,<NA>,<NA>,146973000000,178000000,157293000000,<NA>,157293000000,206803000000
244,NVDA,172199,simfin,us,Q,True,USD,2025,Q4,2026-01-31,2026-02-25,2026-05-20,24302000000,24430000000,62556000000,10605000000,51951000000,38466000000,38466000000,<NA>,None,21403000000,<NA>,<NA>,<NA>,<NA>,3180000000,3180000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,125605000000,10383000000,<NA>,<NA>,22251000000,<NA>,<NA>,<NA>,48564000000,3306000000,20832000000,<NA>,<NA>,13258000000,<NA>,<NA>,<NA>,<NA>,11168000000,81198000000,206803000000,31164000000,9812000000,<NA>,<NA>,21352000000,999000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,32163000000,7469000000,<NA>,<NA>,9878000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9878000000,17347000000,49510000000,<NA>,10142000000,<NA>,<NA>,<NA>,<NA>,146973000000,178000000,157293000000,<NA>,157293000000,206803000000
206,NVDA,172199,simfin,us,Q,True,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,80572000000,13237000000,67335000000,40710000000,40710000000,<NA>,None,25797000000,<NA>,<NA>,<NA>,<NA>,3916000000,3916000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,150995000000,12403000000,<NA>,<NA>,43364000000,<NA>,<NA>,<NA>,52712000000,3120000000,20894000000,<NA>,<NA>,11707000000,<NA>,<NA>,<NA>,<NA>,16991000000,108479000000,259474000000,42884000000,13097000000,<NA>,<NA>,29787000000,1000000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,43884000000,7470000000,<NA>,<NA>,12646000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,12646000000,20116000000,64000000000,<NA>,10299000000,<NA>,<NA>,<NA>,<NA>,185038000000,137000000,195474000000,<NA>,195474000000,259474000000

## cashflow

### cashflow (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865829
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
Net Income/Starting Line,124.0,-201338000.0,120067000000.0,4635839483.870968,14848873463.639324
Depreciation & Amortization,124.0,-3776000.0,2843000000.0,221854435.483871,396308501.30349
Non-Cash Items,124.0,-12518000000.0,1936000000.0,-46922830.645161,1284583267.592793
Change in Fixed Assets & Intangibles,124.0,-6143000000.0,176950000.0,-307278064.516129,714092371.574964
Net Cash from Operating Activities,124.0,-445044000.0,102718000000.0,4253099548.387097,12794621507.666262
Change in Working Capital,124.0,-15949000000.0,8654000000.0,-557671540.322581,2414778884.432549
Net Change in Cash,124.0,-12220000000.0,10114000000.0,193428508.064516,2174003166.944569
Net Cash Before FX,124.0,-12220000000.0,10114000000.0,193428508.064516,2174003166.944569
Net Cash Before Disc. Operations and FX,124.0,-12220000000.0,10114000000.0,193428508.064516,2174003166.944569
Net Cash from Financing Activities,124.0,-48373000000.0,4744000000.0,-2062407290.322581,6782835314.273945
Net Cash from Investing Activities,124.0,-52329000000.0,7375000000.0,-1997263750.0,6765813835.623116
Net Change in Long Term Investment,123.0,-31651000000.0,9334000000.0,-1265216991.869919,4677639140.591669
Cash from (Repurchase of) Equity,119.0,-40086000000.0,195857000.0,-1799566411.764706,5616403063.344325
Cash from (Repayment of) Debt,105.0,-1250000000.0,5092000000.0,197550428.571429,987858193.560655
Increase in Capital Stock,105.0,-489000000.0,515000000.0,54777761.904762,110902311.211569
Other Financing Activities,97.0,-7957000000.0,4754000000.0,-529057608.247423,1407305549.522721
Other Investing Activities,92.0,-985000000.0,859000000.0,-23895804.347826,159763769.37582
Decrease in Capital Stock,80.0,-40086000000.0,99449000.0,-2748750850.0,6682898621.411066
Acquisition of Fixed Assets & Intangibles,80.0,-6143000000.0,-15000000.0,-412984637.5,854373053.758938
Dividends Paid,68.0,-974000000.0,-43343000.0,-161975117.647059,167170105.83365
Other Non-Cash Adjustments,67.0,-16030000000.0,1393000000.0,-220567656.716418,1968483667.086147
Stock-Based Compensation,67.0,22982000.0,2004000000.0,267230417.910448,421583472.154511
Change in Other,67.0,-1482000000.0,8038000000.0,279549537.313433,1470466645.212723
Change in Accounts Receivable,67.0,-2366000000.0,933000000.0,-188020805.970149,529514060.72464
Change in Inventories,67.0,-4420000000.0,597000000.0,-157064238.80597,589000947.565969
Change in Accounts Payable,67.0,-359000000.0,2210000000.0,88526955.223881,310098375.834745
Deferred Income Taxes,67.0,-2177000000.0,1584000000.0,-66563059.701493,405009564.655816
Decrease in Long Term Investment,66.0,1000000.0,16220000000.0,1932819984.848485,2779537760.805205
Increase in Long Term Investment,66.0,-24787000000.0,0.0,-2852701484.848485,5020396683.644172
"Cash from (Repayment of) Long Term Debt, Net",63.0,-2214000000.0,5092000000.0,239274238.095238,1248437821.211318

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
136,NVDA,172199,simfin,us,A,False,USD,2000,FY,2001-01-31,2001-05-14,2002-05-14,205838680800,246223448160,98469000,<NA>,<NA>,<NA>,15724000,37024000,<NA>,<NA>,<NA>,116692000,<NA>,<NA>,<NA>,<NA>,<NA>,267909000,-36329000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-24500000,<NA>,-60829000,<NA>,289056000,<NA>,<NA>,<NA>,<NA>,116579000,116579000,<NA>,<NA>,<NA>,405635000,612715000,<NA>,612715000,<NA>,612715000
105,NVDA,172199,simfin,us,A,False,USD,2001,FY,2002-01-31,2002-05-14,2002-05-14,205838680800,246223448160,176924000,<NA>,<NA>,<NA>,43491000,38834000,<NA>,<NA>,<NA>,-98443000,<NA>,<NA>,<NA>,<NA>,<NA>,160806000,-96966000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-457597000,<NA>,<NA>,-64109000,<NA>,<NA>,<NA>,<NA>,17500000,<NA>,-601172000,<NA>,8716000,<NA>,<NA>,<NA>,<NA>,90375000,90375000,<NA>,<NA>,<NA>,99091000,-341275000,<NA>,-341275000,<NA>,-341275000
86,NVDA,172199,simfin,us,Q,False,USD,2001,Q4,2002-01-31,2002-03-12,2002-05-14,205838680800,246223448160,76033000,<NA>,<NA>,<NA>,14759000,-10691000,<NA>,<NA>,<NA>,-32552000,<NA>,<NA>,<NA>,<NA>,<NA>,47549000,-20151000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-140785000,<NA>,<NA>,0,<NA>,<NA>,<NA>,<NA>,50000,<NA>,-160886000,<NA>,-1273000,<NA>,<NA>,<NA>,<NA>,48969000,48969000,<NA>,150000,<NA>,47846000,-65491000,<NA>,-65491000,<NA>,-65491000
21,NVDA,172199,simfin,us,A,False,USD,2002,FY,2003-01-31,2003-04-25,2003-04-25,220948246080,242364737760,90799000,<NA>,<NA>,<NA>,58216000,80615000,<NA>,<NA>,<NA>,35402000,<NA>,<NA>,<NA>,<NA>,<NA>,265032000,-63123000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-217300000,<NA>,<NA>,-3901000,<NA>,<NA>,<NA>,<NA>,7000000,<NA>,-277324000,<NA>,799000,<NA>,<NA>,<NA>,<NA>,25487000,25487000,<NA>,<NA>,<NA>,26286000,13994000,<NA>,13994000,<NA>,13994000
189,NVDA,172199,simfin,us,Q,False,USD,2002,Q1,2002-04-30,2002-04-02,2002-07-03,216984960000,262893600000,83245000,<NA>,<NA>,<NA>,12830000,6990000,<NA>,<NA>,<NA>,-54290000,<NA>,<NA>,<NA>,<NA>,<NA>,48775000,-21192000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-63563000,<NA>,<NA>,-3980000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-88735000,<NA>,-870000,<NA>,<NA>,<NA>,<NA>,14981000,14981000,<NA>,<NA>,<NA>,14111000,-25849000,<NA>,-25849000,<NA>,-25849000
126,NVDA,172199,simfin,us,Q,False,USD,2025,Q1,2025-04-30,2025-05-28,2025-05-28,24441000000,24611000000,18775000000,<NA>,<NA>,<NA>,611000000,-626000000,1474000000,-2177000000,77000000,8654000000,933000000,-1258000000,941000000,8038000000,<NA>,27414000000,-1279000000,-52000000,<NA>,<NA>,-1227000000,-1227000000,<NA>,<NA>,-3606000000,3589000000,-7195000000,-383000000,<NA>,<NA>,<NA>,-383000000,<NA>,<NA>,-5268000000,-244000000,<NA>,<NA>,<NA>,<NA>,<NA>,-13725000000,370000000,-14095000000,-1532000000,<NA>,-15501000000,6645000000,<NA>,6645000000,<NA>,6645000000
112,NVDA,172199,simfin,us,Q,False,USD,2025,Q2,2025-07-31,2025-08-27,2025-05-28,24366000000,24532000000,26422000000,<NA>,<NA>,<NA>,669000000,-704000000,<NA>,<NA>,<NA>,-11022000000,<NA>,<NA>,<NA>,<NA>,<NA>,15365000000,-1916000000,52000000,<NA>,<NA>,-1968000000,<NA>,<NA>,<NA>,-4938000000,<NA>,<NA>,-294000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7148000000,-244000000,370000000,<NA>,<NA>,<NA>,<NA>,-10090000000,-370000000,-9720000000,-1848000000,<NA>,-11812000000,-3595000000,<NA>,-3595000000,<NA>,-3595000000
44,NVDA,172199,simfin,us,Q,False,USD,2025,Q3,2025-10-31,2025-11-19,2025-08-27,24327000000,24483000000,31910000000,<NA>,<NA>,<NA>,751000000,346000000,<NA>,<NA>,<NA>,-9256000000,<NA>,<NA>,<NA>,<NA>,<NA>,23751000000,-1660000000,<NA>,<NA>,<NA>,-1660000000,<NA>,<NA>,<NA>,-6695000000,<NA>,<NA>,-693000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-9048000000,-244000000,273000000,<NA>,<NA>,<NA>,<NA>,-12456000000,<NA>,-12456000000,-2429000000,<NA>,-14856000000,-153000000,<NA>,-153000000,<NA>,-153000000
113,NVDA,172199,simfin,us,Q,False,USD,2025,Q4,2026-01-31,2026-02-25,2025-11-19,24302000000,24430000000,42960000000,<NA>,<NA>,<NA>,812000000,-3259000000,<NA>,<NA>,<NA>,-4325000000,<NA>,<NA>,<NA>,<NA>,<NA>,36188000000,-1288000000,<NA>,<NA>,<NA>,-1288000000,<NA>,<NA>,<NA>,-16412000000,<NA>,<NA>,-13165000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-30865000000,-242000000,1000000,<NA>,<NA>,<NA>,<NA>,-3815000000,<NA>,-3815000000,-2148000000,<NA>,-6204000000,-881000000,<NA>,-881000000,<NA>,-881000000
127,NVDA,172199,simfin,us,Q,False,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,58321000000,<NA>,<NA>,<NA>,997000000,-12518000000,1928000000,1584000000,-16030000000,3544000000,-2243000000,-4420000000,2210000000,7997000000,<NA>,50344000000,-1790000000,-33000000,<NA>,<NA>,-1757000000,-1757000000,<NA>,<NA>,-24585000000,26000000,-24611000000,-87000000,<NA>,<NA>,<NA>,-87000000,<NA>,<NA>,-26462000000,-243000000,<NA>,<NA>,<NA>,<NA>,<NA>,-18797000000,515000000,-19312000000,-2210000000,<NA>,-21250000000,2632000000,<NA>,2632000000,<NA>,2632000000

### cashflow (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=98  |  USD  |  124 rows*

,count,min,max,mean,std
Shares (Basic),124.0,21360000000.0,245935886880.0,72601991990.322586,82014812211.865829
Shares (Diluted),124.0,21865560000.0,268892631360.0,77902641258.709671,89748557932.571045
Net Income/Starting Line,124.0,-201338000.0,120067000000.0,4627494451.612904,14851435075.583496
Depreciation & Amortization,124.0,-3776000.0,2843000000.0,223098241.935484,395897390.593659
Non-Cash Items,124.0,-12518000000.0,1936000000.0,-46830911.290323,1284560849.15256
Change in Working Capital,124.0,-15949000000.0,8654000000.0,-556106637.096774,2414956031.787003
Change in Fixed Assets & Intangibles,124.0,-6143000000.0,176950000.0,-314920758.064516,719730094.06959
Net Cash from Operating Activities,124.0,-347672000.0,102718000000.0,4247655145.16129,12796275240.000683
Net Cash from Investing Activities,124.0,-52329000000.0,7375000000.0,-2000175991.935484,6770100218.924363
Net Change in Cash,124.0,-12220000000.0,10114000000.0,188560653.225806,2174849552.213801
Net Cash Before FX,124.0,-12220000000.0,10114000000.0,188560653.225806,2174849552.213801
Net Cash Before Disc. Operations and FX,124.0,-12220000000.0,10114000000.0,188560653.225806,2174849552.213801
Net Cash from Financing Activities,124.0,-48373000000.0,4744000000.0,-2058918500.0,6775998934.175532
Net Change in Long Term Investment,123.0,-31651000000.0,9257000000.0,-1276892991.869919,4691441521.75861
Cash from (Repurchase of) Equity,114.0,-40086000000.0,246000000.0,-1886521061.403509,5724906579.411995
Other Financing Activities,111.0,-7957000000.0,300000000.0,-459190360.36036,1137547963.691048
Cash from (Repayment of) Debt,104.0,-1250000000.0,5145000000.0,209042009.615385,1004296798.388933
Increase in Capital Stock,101.0,-403000000.0,515000000.0,50843138.613861,110752946.094452
Other Investing Activities,92.0,-437000000.0,748000000.0,-9742565.217391,112214273.173678
Acquisition of Fixed Assets & Intangibles,87.0,-6143000000.0,-15000000.0,-419210275.862069,836405694.55107
Decrease in Capital Stock,85.0,-40086000000.0,0.0,-2590571270.588235,6512212933.342013
Dividends Paid,75.0,-974000000.0,0.0,-146836426.666667,165993345.185328
Net Cash from Acquisitions & Divestitures,74.0,-14535000000.0,221000000.0,-689425608.108108,2558303587.883312
Other Non-Cash Adjustments,66.0,-16030000000.0,77000000.0,-245171378.787879,1973231987.030242
Stock-Based Compensation,66.0,22982000.0,1928000000.0,198611803.030303,332909557.690383
Change in Accounts Receivable,66.0,-2366000000.0,933000000.0,-107819530.30303,457605493.51484
Change in Inventories,66.0,-4420000000.0,597000000.0,-108704924.242424,591076827.566572
Change in Accounts Payable,66.0,-359000000.0,2210000000.0,56494878.787879,307700814.033948
Change in Other,66.0,-360000000.0,8038000000.0,327120318.181818,1455417208.165582
Deferred Income Taxes,66.0,-2177000000.0,1584000000.0,-58331136.363636,421317513.957599
Increase in Long Term Investment,65.0,-24611000000.0,0.0,-1864972061.538461,3561769746.48309
Decrease in Long Term Investment,64.0,1000000.0,8109000000.0,1271361062.5,1641367842.472063
"Cash from (Repayment of) Long Term Debt, Net",62.0,-2217000000.0,4979000000.0,35736870.967742,742493208.987645

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
135,NVDA,172199,simfin,us,A,True,USD,2000,FY,2001-01-31,2001-05-14,2003-04-25,205838680800,246223448160,98469000,<NA>,<NA>,<NA>,15724000,37024000,<NA>,<NA>,<NA>,116692000,<NA>,<NA>,<NA>,<NA>,<NA>,267909000,-36329000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-24500000,<NA>,-60829000,<NA>,289056000,<NA>,<NA>,<NA>,<NA>,116579000,116579000,<NA>,<NA>,<NA>,405635000,612715000,<NA>,612715000,<NA>,612715000
186,NVDA,172199,simfin,us,A,True,USD,2001,FY,2002-01-31,2002-05-14,2004-03-29,205838680800,246223448160,176924000,<NA>,<NA>,<NA>,43491000,38834000,<NA>,<NA>,<NA>,-98443000,<NA>,<NA>,<NA>,<NA>,<NA>,160806000,-96966000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-457597000,<NA>,<NA>,-64109000,<NA>,<NA>,<NA>,<NA>,17500000,<NA>,-601172000,<NA>,8791000,<NA>,<NA>,<NA>,<NA>,90476000,90476000,<NA>,-176000,<NA>,99091000,-341275000,<NA>,-341275000,<NA>,-341275000
61,NVDA,172199,simfin,us,Q,True,USD,2001,Q4,2002-01-31,2002-03-12,2004-03-29,205838680800,246223448160,76033000,<NA>,<NA>,<NA>,14759000,-10691000,<NA>,<NA>,<NA>,-32552000,<NA>,<NA>,<NA>,<NA>,<NA>,47549000,-20151000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-140785000,<NA>,<NA>,0,<NA>,<NA>,<NA>,<NA>,50000,<NA>,-160886000,<NA>,-1198000,<NA>,<NA>,<NA>,<NA>,49070000,49070000,<NA>,-26000,<NA>,47846000,-65491000,<NA>,-65491000,<NA>,-65491000
167,NVDA,172199,simfin,us,A,True,USD,2002,FY,2003-01-31,2003-04-25,2005-03-22,220948246080,242364737760,90799000,<NA>,<NA>,<NA>,58216000,80615000,<NA>,<NA>,<NA>,35402000,<NA>,<NA>,<NA>,<NA>,<NA>,265032000,-63123000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-217300000,<NA>,<NA>,-3901000,<NA>,<NA>,<NA>,<NA>,7000000,<NA>,-277324000,<NA>,-4935000,<NA>,<NA>,<NA>,<NA>,25487000,25487000,<NA>,5734000,<NA>,26286000,13994000,<NA>,13994000,<NA>,13994000
7,NVDA,172199,simfin,us,Q,True,USD,2002,Q1,2002-04-30,2002-04-02,2003-05-22,216984960000,262893600000,83245000,<NA>,<NA>,<NA>,12830000,6990000,<NA>,<NA>,<NA>,-54290000,<NA>,<NA>,<NA>,<NA>,<NA>,48775000,-21192000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-63563000,<NA>,<NA>,-3980000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-88735000,<NA>,-870000,<NA>,<NA>,<NA>,<NA>,14981000,14981000,<NA>,<NA>,<NA>,14111000,-25849000,<NA>,-25849000,<NA>,-25849000
232,NVDA,172199,simfin,us,Q,True,USD,2025,Q1,2025-04-30,2025-05-28,2026-05-20,24441000000,24611000000,18775000000,<NA>,<NA>,<NA>,611000000,-626000000,1474000000,-2177000000,77000000,8654000000,933000000,-1258000000,941000000,8038000000,<NA>,27414000000,-1279000000,-52000000,<NA>,<NA>,-1227000000,-1227000000,<NA>,<NA>,-3606000000,<NA>,-3606000000,-383000000,<NA>,<NA>,<NA>,-383000000,<NA>,<NA>,-5268000000,-244000000,<NA>,<NA>,<NA>,<NA>,<NA>,-13725000000,370000000,-14095000000,-1532000000,<NA>,-15501000000,6645000000,<NA>,6645000000,<NA>,6645000000
96,NVDA,172199,simfin,us,Q,True,USD,2025,Q2,2025-07-31,2025-08-27,2026-05-20,24366000000,24532000000,26422000000,<NA>,<NA>,<NA>,669000000,-704000000,<NA>,<NA>,<NA>,-11022000000,<NA>,<NA>,<NA>,<NA>,<NA>,15365000000,-1916000000,52000000,<NA>,<NA>,-1968000000,<NA>,<NA>,<NA>,-4938000000,<NA>,<NA>,-294000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7148000000,-244000000,370000000,<NA>,<NA>,<NA>,<NA>,-10090000000,-370000000,-9720000000,-1848000000,<NA>,-11812000000,-3595000000,<NA>,-3595000000,<NA>,-3595000000
217,NVDA,172199,simfin,us,Q,True,USD,2025,Q3,2025-10-31,2025-11-19,2025-08-27,24327000000,24483000000,31910000000,<NA>,<NA>,<NA>,751000000,346000000,<NA>,<NA>,<NA>,-9256000000,<NA>,<NA>,<NA>,<NA>,<NA>,23751000000,-1660000000,<NA>,<NA>,<NA>,-1660000000,<NA>,<NA>,<NA>,-6695000000,<NA>,<NA>,-693000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-9048000000,-244000000,273000000,<NA>,<NA>,<NA>,<NA>,-12456000000,<NA>,-12456000000,-2429000000,<NA>,-14856000000,-153000000,<NA>,-153000000,<NA>,-153000000
97,NVDA,172199,simfin,us,Q,True,USD,2025,Q4,2026-01-31,2026-02-25,2025-11-19,24302000000,24430000000,42960000000,<NA>,<NA>,<NA>,812000000,-3259000000,<NA>,<NA>,<NA>,-4325000000,<NA>,<NA>,<NA>,<NA>,<NA>,36188000000,-1288000000,<NA>,<NA>,<NA>,-1288000000,<NA>,<NA>,<NA>,-16412000000,<NA>,<NA>,-13165000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-30865000000,-242000000,1000000,<NA>,<NA>,<NA>,<NA>,-3815000000,<NA>,-3815000000,-2148000000,<NA>,-6204000000,-881000000,<NA>,-881000000,<NA>,-881000000
85,NVDA,172199,simfin,us,Q,True,USD,2026,Q1,2026-04-30,2026-05-20,2026-05-20,24286000000,24391000000,58321000000,<NA>,<NA>,<NA>,997000000,-12518000000,1928000000,1584000000,-16030000000,3544000000,-2243000000,-4420000000,2210000000,7997000000,<NA>,50344000000,-1790000000,-33000000,<NA>,<NA>,-1757000000,-1757000000,<NA>,<NA>,-24585000000,26000000,-24611000000,-87000000,<NA>,<NA>,<NA>,-87000000,<NA>,<NA>,-26462000000,-243000000,<NA>,<NA>,<NA>,<NA>,<NA>,-18797000000,515000000,-19312000000,-2210000000,<NA>,-21250000000,2632000000,<NA>,2632000000,<NA>,2632000000

## market_data

*no rows*