# investalyze — ticker profile

Everything we hold for one ticker, table by table: a metadata summary plus a head/tail
preview of the rows. Set `TICKER` and run all.

The notebook probes every table, so it works for both stocks (prices + dividends/splits +
income/balance/cashflow + companies) and non-equity tickers (market_data). Run from the
repo root (so `ingest.toml` resolves).

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import HTML, Markdown, display

from investalyze.ingest import config, storage

display(HTML('<style>table.dataframe td {white-space: nowrap;}</style>'))
pd.set_option('display.max_columns', None)

# resolve the repo root (walk up to ingest.toml) so paths work regardless of CWD
root = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'ingest.toml').exists())
cfg = config.load(root / 'ingest.toml')
con = storage.connect(root / cfg.data_root, read_only=True)  # explore only, never mutate
existing = {name for (name,) in con.execute('SHOW TABLES').fetchall()}

TICKER = 'AAPL'    # the one knob — set the ticker to profile
MIN_FILL = 0.5     # fundamentals: only stat columns filled in >= this fraction of rows
                   # (drops NaN-heavy breakdown columns like 'Other Revenue')

In [2]:
def load(table, ticker):
    """All rows for `ticker` in `table` as a DataFrame (empty if the table is absent)."""
    if table not in existing:
        return pd.DataFrame()
    return con.execute(f'SELECT * FROM {table} WHERE Ticker = ?', [ticker]).df()


def head_tail(df, n=5):
    """First `n` + last `n` rows; the whole frame if it has <= 2n rows."""
    if len(df) <= 2 * n:
        return df
    return pd.concat([df.head(n), df.tail(n)])


def ts_meta(df):
    """count/min/max/mean/std per numeric column of a time series (Date span shown separately)."""
    return df.select_dtypes('number').describe().T[['count', 'min', 'max', 'mean', 'std']]


def fund_meta(df):
    """One-line coverage summary for a fundamentals slice."""
    fy = f"{int(df['Fiscal Year'].min())} .. {int(df['Fiscal Year'].max())}"
    periods = ' '.join(f'{p}={n}' for p, n in df['Period'].value_counts().sort_index().items())
    currency = ', '.join(sorted(df['Currency'].dropna().unique()))
    return f'Fiscal Year {fy}  |  {periods}  |  {currency}  |  {len(df)} rows'


def fund_stats(df):
    """count/min/max/mean/std for the well-populated numeric columns of a fundamentals slice.

    Importance heuristic: a column's NaN fraction. Columns filled in fewer than MIN_FILL of
    the rows (e.g. 'Sales & Services Revenue', 'Other Revenue') are dropped; the core line
    items (Revenue, Cost of Revenue, ...) survive. Ordered most-populated first.
    """
    num = df.select_dtypes('number').drop(columns=['SrcId', 'Fiscal Year'], errors='ignore')
    fill = num.notna().mean()
    keep = fill[fill >= MIN_FILL].sort_values(ascending=False).index
    return num[keep].describe().T[['count', 'min', 'max', 'mean', 'std']]


def section(title):
    display(Markdown(f'## {title}'))


def note(text):
    display(Markdown(f'*{text}*'))


def ts_section(table, ticker):
    """A time-series table: date span + per-column stats + head/tail preview."""
    section(table)
    df = load(table, ticker).sort_values('Date')
    if df.empty:
        note('no rows')
        return
    note(f'{df.Date.min()} .. {df.Date.max()}  |  {len(df)} rows')
    display(ts_meta(df))
    display(head_tail(df))


def profile(ticker):
    """Everything we hold for `ticker`: metadata + a head/tail preview, table by table."""
    display(Markdown(f'# {ticker}'))

    # identity card — one row, transposed
    section('companies')
    companies = load('companies', ticker)
    note('no rows') if companies.empty else display(companies.T)

    ts_section('prices', ticker)
    ts_section('dividends', ticker)
    ts_section('splits', ticker)

    # fundamentals — split each statement into as-reported vs restated
    for table in ('income', 'balance', 'cashflow'):
        section(table)
        df = load(table, ticker).sort_values(['Fiscal Year', 'Fiscal Period'])
        if df.empty:
            note('no rows')
            continue
        for is_restated, label in ((False, 'as-reported'), (True, 'restated')):
            display(Markdown(f'### {table} ({label})'))
            part = df[df['IsRestated'] == is_restated]
            if part.empty:
                note('no rows')
                continue
            note(fund_meta(part))
            display(fund_stats(part))
            display(head_tail(part))

    ts_section('market_data', ticker)  # populates for non-equity tickers

In [3]:
profile(TICKER)

# AAPL

## companies

                                                                               0
Ticker                                                                      AAPL
SrcId                                                                     111052
Src                                                                       simfin
Market                                                                        us
Industry                                                       Computer Hardware
Sector                                                                Technology
Company Name                                                           APPLE INC
IndustryId                                                                101001
ISIN                                                                US0378331005
End of financial year (month)                                                  9
Number Employees                                                          147000
Business Summary               Apple Inc is an American multinational technol...
CIK                                                                       320193
Main Currency                                                                USD

## prices

*1980-12-12 00:00:00 .. 2026-06-18 00:00:00  |  11471 rows*

      count       min           max          mean           std
O   11471.0  0.049665  3.141800e+02  3.133501e+01  6.293298e+01
H   11471.0  0.049665  3.174000e+02  3.167462e+01  6.361098e+01
L   11471.0  0.049107  3.096500e+02  3.101537e+01  6.231040e+01
C   11471.0  0.049107  3.152000e+02  3.135799e+01  6.298619e+01
V   11471.0  0.000000  7.421641e+09  3.070844e+08  3.327508e+08
AC  11471.0  0.037575  3.152000e+02  3.038300e+01  6.243450e+01

,Ticker,Date,O,H,L,C,V,AC
8572,AAPL,1980-12-12,0.128348,0.128906,0.128348,0.128348,469033600,0.098207
4220,AAPL,1980-12-15,0.122210,0.122210,0.121652,0.121652,175884800,0.093083
7868,AAPL,1980-12-16,0.113281,0.113281,0.112723,0.112723,105728000,0.086251
10736,AAPL,1980-12-17,0.115513,0.116071,0.115513,0.115513,86441600,0.088386
1457,AAPL,1980-12-18,0.118862,0.119420,0.118862,0.118862,73449600,0.090949
7086,AAPL,2026-06-12,296.029999,297.140015,289.619995,291.130005,38742100,291.130005
8571,AAPL,2026-06-15,294.119995,297.779999,291.700012,296.420013,45732600,296.420013
4967,AAPL,2026-06-16,295.250000,300.480011,293.970001,299.239990,39874400,299.239990
11470,AAPL,2026-06-17,300.850006,302.070007,294.359985,295.950012,42745100,295.950012
9999,AAPL,2026-06-18,298.440002,300.570007,295.619995,298.010010,85962201,298.010010

## dividends

*1987-05-11 00:00:00 .. 2026-05-11 00:00:00  |  91 rows*

          count       min   max      mean       std
Dividend   91.0  0.000536  0.27  0.113556  0.099032

   Ticker       Date  Dividend
0    AAPL 1987-05-11  0.000536
53   AAPL 1987-08-10  0.000536
54   AAPL 1987-11-17  0.000714
64   AAPL 1988-02-12  0.000714
18   AAPL 1988-05-16  0.000714
52   AAPL 2025-05-12  0.260000
11   AAPL 2025-08-11  0.260000
44   AAPL 2025-11-10  0.260000
77   AAPL 2026-02-09  0.260000
83   AAPL 2026-05-11  0.270000

## splits

*1987-06-16 00:00:00 .. 2020-08-31 00:00:00  |  5 rows*

       count  min  max  mean      std
Ratio    5.0  2.0  7.0   3.4  2.19089

  Ticker       Date  Ratio
2   AAPL 1987-06-16    2.0
4   AAPL 2000-06-21    2.0
3   AAPL 2005-02-28    2.0
1   AAPL 2014-06-09    7.0
0   AAPL 2020-08-31    4.0

## income

### income (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,1.467328e+10,2.630961e+10,2.183523e+10,3.815689e+09
Shares (Diluted),130.0,1.472587e+10,2.654106e+10,2.218118e+10,3.986294e+09
Revenue,130.0,1.007000e+09,4.161610e+11,6.766697e+10,8.765007e+10
Cost of Revenue,130.0,-2.235460e+11,-9.530000e+08,-3.958395e+10,5.000610e+10
Gross Profit,130.0,-2.100000e+07,1.952010e+11,2.808302e+10,3.795697e+10
Operating Expenses,130.0,-6.215100e+10,-3.750000e+08,-8.576531e+09,1.168205e+10
"Selling, General & Administrative",130.0,-2.760100e+10,-2.680000e+08,-4.595700e+09,5.591275e+09
Research & Development,130.0,-3.455000e+10,-9.700000e+07,-3.980831e+09,6.221088e+09
Operating Income (Loss),130.0,-4.200000e+08,1.330500e+11,1.950648e+10,2.648840e+10
Non-Operating Income (Loss),130.0,-5.650000e+08,2.745000e+09,2.350077e+08,4.309611e+08
Other Non-Operating Income (Loss),130.0,-5.650000e+08,2.745000e+09,2.350077e+08,4.309611e+08
"Pretax Income (Loss), Adj.",130.0,-3.530000e+08,1.327290e+11,1.974149e+10,2.658689e+10
Pretax Income (Loss),130.0,-2.950000e+08,1.327290e+11,1.974391e+10,2.658516e+10
"Income Tax (Expense) Benefit, Net",130.0,-2.974900e+10,8.800000e+07,-3.909869e+09,5.118466e+09
Income (Loss) from Continuing Operations,130.0,-2.070000e+08,1.120100e+11,1.583404e+10,2.184053e+10
Income (Loss) Incl. Minority Interest,130.0,-2.070000e+08,1.120100e+11,1.583404e+10,2.184053e+10
Net Income,130.0,-2.070000e+08,1.120100e+11,1.583404e+10,2.184053e+10
Net Income (Common),130.0,-1.950000e+08,1.120100e+11,1.583424e+10,2.184038e+10

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
165,AAPL,111052,simfin,us,A,False,USD,2000,FY,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,7983000000,<NA>,<NA>,<NA>,-5817000000,<NA>,<NA>,<NA>,2166000000,<NA>,-1546000000,-1166000000,<NA>,<NA>,-380000000,<NA>,<NA>,<NA>,620000000,203000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,203000000,823000000,269000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,1092000000,-306000000,<NA>,<NA>,None,<NA>,786000000,<NA>,<NA>,<NA>,786000000,<NA>,786000000,<NA>,<NA>,786000000
35,AAPL,111052,simfin,us,Q,False,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,1825000000,<NA>,<NA>,<NA>,-1282000000,<NA>,<NA>,<NA>,543000000,<NA>,-375000000,-278000000,<NA>,<NA>,-97000000,<NA>,<NA>,<NA>,168000000,52000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,52000000,220000000,50000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,270000000,-70000000,<NA>,<NA>,None,<NA>,200000000,<NA>,<NA>,<NA>,200000000,<NA>,200000000,<NA>,<NA>,200000000
140,AAPL,111052,simfin,us,Q,False,USD,2000,Q4,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,1870000000,<NA>,<NA>,<NA>,-1403000000,<NA>,<NA>,<NA>,467000000,<NA>,-383000000,-282000000,<NA>,<NA>,-101000000,<NA>,<NA>,<NA>,84000000,62000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62000000,146000000,83000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,229000000,-59000000,<NA>,<NA>,None,<NA>,170000000,<NA>,<NA>,<NA>,170000000,<NA>,170000000,<NA>,<NA>,170000000
166,AAPL,111052,simfin,us,A,False,USD,2001,FY,2001-09-30,2001-12-21,2001-12-21,24208660000,24900176000,5363000000,<NA>,<NA>,<NA>,-4128000000,<NA>,<NA>,<NA>,1235000000,<NA>,-1568000000,-1138000000,<NA>,<NA>,-430000000,<NA>,<NA>,<NA>,-333000000,217000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,217000000,-116000000,64000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-52000000,15000000,<NA>,<NA>,None,<NA>,-37000000,<NA>,<NA>,<NA>,-37000000,<NA>,-37000000,<NA>,12000000,-25000000
99,AAPL,111052,simfin,us,Q,False,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,1007000000,<NA>,<NA>,<NA>,-1028000000,<NA>,<NA>,<NA>,-21000000,<NA>,-399000000,-297000000,<NA>,<NA>,-102000000,<NA>,<NA>,<NA>,-420000000,67000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67000000,-353000000,58000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-295000000,88000000,<NA>,<NA>,None,<NA>,-207000000,<NA>,<NA>,<NA>,-207000000,<NA>,-207000000,<NA>,12000000,-195000000
130,AAPL,111052,simfin,us,Q,False,USD,2025,Q2,2025-03-31,2025-05-02,2025-05-02,14994082000,15056133000,95359000000,<NA>,<NA>,<NA>,-50492000000,<NA>,<NA>,<NA>,44867000000,<NA>,-15278000000,-6728000000,<NA>,<NA>,-8550000000,<NA>,<NA>,<NA>,29589000000,-279000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-279000000,29310000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,29310000000,-4530000000,<NA>,<NA>,None,<NA>,24780000000,<NA>,<NA>,<NA>,24780000000,<NA>,24780000000,<NA>,<NA>,24780000000
156,AAPL,111052,simfin,us,Q,False,USD,2025,Q3,2025-06-30,2025-08-01,2025-08-01,14902886000,14948179000,94036000000,<NA>,<NA>,<NA>,-50318000000,<NA>,<NA>,<NA>,43718000000,<NA>,-15516000000,-6650000000,<NA>,<NA>,-8866000000,<NA>,<NA>,<NA>,28202000000,-171000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-171000000,28031000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,28031000000,-4597000000,<NA>,<NA>,None,<NA>,23434000000,<NA>,<NA>,<NA>,23434000000,<NA>,23434000000,<NA>,<NA>,23434000000
131,AAPL,111052,simfin,us,Q,False,USD,2025,Q4,2025-09-30,2025-10-31,2025-08-01,14815308000,14863611000,102466000000,<NA>,<NA>,<NA>,-54125000000,<NA>,<NA>,<NA>,48341000000,<NA>,-15914000000,-7048000000,<NA>,<NA>,-8866000000,<NA>,<NA>,<NA>,32427000000,377000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,377000000,32804000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,32804000000,-5338000000,<NA>,<NA>,None,<NA>,27466000000,<NA>,<NA>,<NA>,27466000000,<NA>,27466000000,<NA>,<NA>,27466000000
108,AAPL,111052,simfin,us,Q,False,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,143756000000,<NA>,<NA>,<NA>,-74525000000,<NA>,<NA>,<NA>,69231000000,<NA>,-18379000000,-7492000000,<NA>,<NA>,-10887000000,<NA>,<NA>,<NA>,50852000000,150000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,150000000,51002000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,51002000000,-8905000000,<NA>,<NA>,None,<NA>,42097000000,<NA>,<NA>,<NA>,42097000000,<NA>,42097000000,<NA>,<NA>,42097000000
259,AAPL,111052,simfin,us,Q,False,USD,2026,Q2,2026-03-31,2026-05-01,2026-05-01,14673278000,14725873000,111184000000,<NA>,<NA>,<NA>,-56403000000,<NA>,<NA>,<NA>,54781000000,<NA>,-18896000000,-7477000000,<NA>,<NA>,-11419000000,<NA>,<NA>,<NA>,35885000000,-52000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-52000000,35833000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,35833000000,-6255000000,<NA>,<NA>,None,<NA>,29578000000,<NA>,<NA>,<NA>,29578000000,<NA>,29578000000,<NA>,<NA>,29578000000

### income (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,1.467328e+10,2.630961e+10,2.183523e+10,3.815689e+09
Shares (Diluted),130.0,1.472587e+10,2.654106e+10,2.218118e+10,3.986294e+09
Revenue,130.0,1.007000e+09,4.161610e+11,6.784205e+10,8.756190e+10
Cost of Revenue,130.0,-2.235460e+11,-9.530000e+08,-3.966470e+10,4.996609e+10
Gross Profit,130.0,-2.100000e+07,1.952010e+11,2.817735e+10,3.790908e+10
Operating Expenses,130.0,-6.215100e+10,-3.750000e+08,-8.576731e+09,1.168192e+10
"Selling, General & Administrative",130.0,-2.760100e+10,-2.680000e+08,-4.595862e+09,5.591174e+09
Research & Development,130.0,-3.455000e+10,-9.700000e+07,-3.980869e+09,6.221065e+09
Operating Income (Loss),130.0,-4.200000e+08,1.330500e+11,1.960062e+10,2.643879e+10
Non-Operating Income (Loss),130.0,-5.650000e+08,2.745000e+09,2.350692e+08,4.309328e+08
Other Non-Operating Income (Loss),130.0,-5.650000e+08,2.745000e+09,2.350692e+08,4.309328e+08
"Pretax Income (Loss), Adj.",130.0,-3.530000e+08,1.327290e+11,1.983568e+10,2.653752e+10
Pretax Income (Loss),130.0,-2.950000e+08,1.327290e+11,1.983804e+10,2.653582e+10
"Income Tax (Expense) Benefit, Net",130.0,-2.974900e+10,8.800000e+07,-3.945492e+09,5.103737e+09
Income (Loss) from Continuing Operations,130.0,-2.070000e+08,1.120100e+11,1.589255e+10,2.180887e+10
Income (Loss) Incl. Minority Interest,130.0,-2.070000e+08,1.120100e+11,1.589255e+10,2.180887e+10
Net Income,130.0,-2.070000e+08,1.120100e+11,1.589255e+10,2.180887e+10
Net Income (Common),130.0,-1.950000e+08,1.120100e+11,1.589275e+10,2.180872e+10

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Sales & Services Revenue,Financing Revenue,Other Revenue,Cost of Revenue,Cost of Goods & Services,Cost of Financing Revenue,Cost of Other Revenue,Gross Profit,Other Operating Income,Operating Expenses,"Selling, General & Administrative",Selling & Marketing,General & Administrative,Research & Development,Depreciation & Amortization,Provision for Doubtful Accounts,Other Operating Expenses,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net",Interest Expense,Interest Income,Other Investment Income (Loss),Foreign Exchange Gain (Loss),Income (Loss) from Affiliates,Other Non-Operating Income (Loss),"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Acquired In-Process R&D,Merger & Acquisition Expense,Abnormal Derivatives,Disposal of Assets,Early Extinguishment of Debt,Asset Write-Down,Impairment of Goodwill & Intangibles,Sale of Business,Legal Settlement,Restructuring Charges,Sale of Investments & Unrealized Investments,Insurance Settlement,Other Abnormal Items,Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Current Income Tax,Deferred Income Tax,Tax Allowance/Credit,"Income (Loss) from Affiliates, Net of Taxes",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Discontinued Operations,Accounting Charges & Other,Income (Loss) Incl. Minority Interest,Minority Interest,Net Income,Preferred Dividends,Other Adjustments,Net Income (Common)
221,AAPL,111052,simfin,us,A,True,USD,2000,FY,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,7983000000,<NA>,<NA>,<NA>,-5817000000,<NA>,<NA>,<NA>,2166000000,<NA>,-1546000000,-1166000000,<NA>,<NA>,-380000000,<NA>,<NA>,<NA>,620000000,203000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,203000000,823000000,269000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,1092000000,-306000000,<NA>,<NA>,None,<NA>,786000000,<NA>,<NA>,<NA>,786000000,<NA>,786000000,<NA>,<NA>,786000000
100,AAPL,111052,simfin,us,Q,True,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,1825000000,<NA>,<NA>,<NA>,-1282000000,<NA>,<NA>,<NA>,543000000,<NA>,-375000000,-278000000,<NA>,<NA>,-97000000,<NA>,<NA>,<NA>,168000000,52000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,52000000,220000000,50000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,270000000,-70000000,<NA>,<NA>,None,<NA>,200000000,<NA>,<NA>,<NA>,200000000,<NA>,200000000,<NA>,<NA>,200000000
65,AAPL,111052,simfin,us,Q,True,USD,2000,Q4,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,1870000000,<NA>,<NA>,<NA>,-1403000000,<NA>,<NA>,<NA>,467000000,<NA>,-383000000,-282000000,<NA>,<NA>,-101000000,<NA>,<NA>,<NA>,84000000,62000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62000000,146000000,83000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,229000000,-59000000,<NA>,<NA>,None,<NA>,170000000,<NA>,<NA>,<NA>,170000000,<NA>,170000000,<NA>,<NA>,170000000
205,AAPL,111052,simfin,us,A,True,USD,2001,FY,2001-09-30,2001-12-21,2003-12-19,24208660000,24900176000,5363000000,<NA>,<NA>,<NA>,-4128000000,<NA>,<NA>,<NA>,1235000000,<NA>,-1568000000,-1138000000,<NA>,<NA>,-430000000,<NA>,<NA>,<NA>,-333000000,217000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,217000000,-116000000,64000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-52000000,15000000,<NA>,<NA>,None,<NA>,-37000000,<NA>,<NA>,<NA>,-37000000,<NA>,-37000000,<NA>,12000000,-25000000
22,AAPL,111052,simfin,us,Q,True,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,1007000000,<NA>,<NA>,<NA>,-1028000000,<NA>,<NA>,<NA>,-21000000,<NA>,-399000000,-297000000,<NA>,<NA>,-102000000,<NA>,<NA>,<NA>,-420000000,67000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,67000000,-353000000,58000000,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,-295000000,88000000,<NA>,<NA>,None,<NA>,-207000000,<NA>,<NA>,<NA>,-207000000,<NA>,-207000000,<NA>,12000000,-195000000
96,AAPL,111052,simfin,us,Q,True,USD,2025,Q2,2025-03-31,2025-05-02,2026-05-01,14994082000,15056133000,95359000000,<NA>,<NA>,<NA>,-50492000000,<NA>,<NA>,<NA>,44867000000,<NA>,-15278000000,-6728000000,<NA>,<NA>,-8550000000,<NA>,<NA>,<NA>,29589000000,-279000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-279000000,29310000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,29310000000,-4530000000,<NA>,<NA>,None,<NA>,24780000000,<NA>,<NA>,<NA>,24780000000,<NA>,24780000000,<NA>,<NA>,24780000000
87,AAPL,111052,simfin,us,Q,True,USD,2025,Q3,2025-06-30,2025-08-01,2025-08-01,14902886000,14948179000,94036000000,<NA>,<NA>,<NA>,-50318000000,<NA>,<NA>,<NA>,43718000000,<NA>,-15516000000,-6650000000,<NA>,<NA>,-8866000000,<NA>,<NA>,<NA>,28202000000,-171000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-171000000,28031000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,28031000000,-4597000000,<NA>,<NA>,None,<NA>,23434000000,<NA>,<NA>,<NA>,23434000000,<NA>,23434000000,<NA>,<NA>,23434000000
97,AAPL,111052,simfin,us,Q,True,USD,2025,Q4,2025-09-30,2025-10-31,2025-08-01,14815308000,14863611000,102466000000,<NA>,<NA>,<NA>,-54125000000,<NA>,<NA>,<NA>,48341000000,<NA>,-15914000000,-7048000000,<NA>,<NA>,-8866000000,<NA>,<NA>,<NA>,32427000000,377000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,377000000,32804000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,32804000000,-5338000000,<NA>,<NA>,None,<NA>,27466000000,<NA>,<NA>,<NA>,27466000000,<NA>,27466000000,<NA>,<NA>,27466000000
42,AAPL,111052,simfin,us,Q,True,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,143756000000,<NA>,<NA>,<NA>,-74525000000,<NA>,<NA>,<NA>,69231000000,<NA>,-18379000000,-7492000000,<NA>,<NA>,-10887000000,<NA>,<NA>,<NA>,50852000000,150000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,150000000,51002000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,51002000000,-8905000000,<NA>,<NA>,None,<NA>,42097000000,<NA>,<NA>,<NA>,42097000000,<NA>,42097000000,<NA>,<NA>,42097000000
174,AAPL,111052,simfin,us,Q,True,USD,2026,Q2,2026-03-31,2026-05-01,2026-05-01,14673278000,14725873000,111184000000,<NA>,<NA>,<NA>,-56403000000,<NA>,<NA>,<NA>,54781000000,<NA>,-18896000000,-7477000000,<NA>,<NA>,-11419000000,<NA>,<NA>,<NA>,35885000000,-52000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-52000000,35833000000,<NA>,None,<NA>,<NA>,None,<NA>,None,<NA>,<NA>,None,<NA>,None,None,<NA>,35833000000,-6255000000,<NA>,<NA>,None,<NA>,29578000000,<NA>,<NA>,<NA>,29578000000,<NA>,29578000000,<NA>,<NA>,29578000000

## balance

### balance (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,14673278000.0,26309612000.0,21835233546.153847,3815688906.030132
Shares (Diluted),130.0,14725873000.0,26541056000.0,22181176730.76923,3986293905.81803
"Cash, Cash Equivalents & Short Term Investments",130.0,4027000000.0,146595000000.0,39191500000.0,29750350056.764038
Cash & Cash Equivalents,130.0,1159000000.0,50530000000.0,17274800000.0,13578167247.631441
Short Term Investments,130.0,1038000000.0,101023000000.0,21916700000.0,18008432762.256496
Accounts & Notes Receivable,130.0,466000000.0,39921000000.0,11527876923.076923,10632536353.949982
"Accounts Receivable, Net",130.0,466000000.0,39921000000.0,11527876923.076923,10632536353.949982
Inventories,130.0,10000000.0,7662000000.0,2414607692.307693,2435996602.943603
Other Short Term Assets,130.0,330000000.0,53971000000.0,18675776923.076923,16029122335.340879
Misc. Short Term Assets,130.0,161000000.0,53971000000.0,17770276923.076923,16233943368.35817
Total Current Assets,130.0,5143000000.0,222202000000.0,71809761538.461533,55422331707.430275
"Property, Plant & Equipment, Net",130.0,313000000.0,50159000000.0,18923146153.846153,17707843139.930847
Other Long Term Assets,130.0,253000000.0,98764000000.0,21230107692.307693,25929412053.007858
Payables & Accruals,130.0,1518000000.0,89266000000.0,31360430769.23077,24593911147.241825
Total Assets,130.0,6021000000.0,406794000000.0,183894700000.0,149573352500.098114
Total Noncurrent Assets,130.0,785000000.0,262984000000.0,112084938461.538467,97273386944.981628
Misc. Long Term Assets,130.0,144000000.0,93146000000.0,19116500000.0,26292207559.369396
Other Equity,130.0,-12912000000.0,2710000000.0,-1512184615.384615,3365691522.260662
Other Long Term Liabilities,130.0,193000000.0,56795000000.0,24455023076.923077,21761921827.704514
Total Current Liabilities,130.0,1595000000.0,254203000000.0,83442730769.230774,80353482425.105148
Accounts Payable,130.0,801000000.0,74362000000.0,25136107692.307693,22708655050.56094
Total Equity,130.0,3738000000.0,140199000000.0,61392338461.53846,46684582454.701538
Equity Before Minority Interest,130.0,3738000000.0,140199000000.0,61392338461.53846,46684582454.701538
Total Liabilities & Equity,130.0,6021000000.0,406794000000.0,183894700000.0,149573352500.098114
Total Noncurrent Liabilities,130.0,193000000.0,152734000000.0,39059630769.230766,48638394383.487793
Retained Earnings,130.0,-19154000000.0,116572000000.0,34684192307.692307,41301862257.711563
Share Capital & Additional Paid-In Capital,130.0,1502000000.0,99507000000.0,28218576923.076923,27617275742.545162
Total Liabilities,130.0,2101000000.0,309259000000.0,122502361538.461533,117547299900.933746
Misc. Long Term Liabilities,108.0,320000000.0,56795000000.0,28112000000.0,20835580796.804943
Other Payables & Accruals,91.0,717000000.0,26756000000.0,8891890109.89011,8784527735.931257
Other Short Term Liabilities,87.0,2542000000.0,86553000000.0,30285908045.977013,27653807079.522457
Deferred Revenue (Short Term),87.0,2542000000.0,10305000000.0,7205931034.482759,1816163415.920491
Long Term Investments & Receivables,86.0,2498000000.0,207944000000.0,108733941860.465118,51453451843.584892
Intangible Assets,83.0,16000000.0,21334000000.0,1820228915.662651,2791895262.053295
Short Term Debt,83.0,300000000.0,124719000000.0,49829216867.469879,49336700495.242615
Deferred Tax Assets (Short Term),78.0,161000000.0,5546000000.0,1509166666.666667,1530610517.49851
Goodwill,75.0,38000000.0,5889000000.0,1649200000.0,2108687519.300585

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
3,AAPL,111052,simfin,us,Q,False,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,313000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1063000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1063000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
167,AAPL,111052,simfin,us,Q,False,USD,2000,Q4,2000-09-30,2000-12-21,2001-12-21,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,419000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
190,AAPL,111052,simfin,us,A,False,USD,2000,Q4,2000-09-30,2000-12-21,2001-12-21,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,419000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
106,AAPL,111052,simfin,us,Q,False,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,4336000000,2310000000,2026000000,466000000,466000000,<NA>,None,11000000,<NA>,<NA>,<NA>,<NA>,330000000,<NA>,<NA>,<NA>,169000000,<NA>,<NA>,161000000,5143000000,564000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,314000000,76000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,238000000,878000000,6021000000,1518000000,801000000,<NA>,<NA>,717000000,317000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1835000000,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,266000000,2101000000,<NA>,1693000000,<NA>,<NA>,<NA>,<NA>,2260000000,-33000000,3920000000,<NA>,3920000000,6021000000
141,AAPL,111052,simfin,us,Q,False,USD,2001,Q2,2001-03-31,2001-05-14,2001-05-14,24208660000,24900176000,4144000000,2138000000,2006000000,637000000,637000000,<NA>,None,10000000,<NA>,<NA>,<NA>,<NA>,554000000,<NA>,<NA>,<NA>,183000000,<NA>,<NA>,371000000,5345000000,331000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,454000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,454000000,785000000,6130000000,1795000000,961000000,<NA>,<NA>,834000000,317000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2112000000,<NA>,<NA>,<NA>,280000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,280000000,<NA>,<NA>,<NA>,280000000,2392000000,0,1599000000,<NA>,<NA>,<NA>,<NA>,2133000000,6000000,3738000000,<NA>,3738000000,6130000000
192,AAPL,111052,simfin,us,Q,False,USD,2025,Q3,2025-06-30,2025-08-01,2025-08-01,14902886000,14948179000,55372000000,36269000000,19103000000,27557000000,27557000000,<NA>,None,5925000000,<NA>,<NA>,<NA>,<NA>,33637000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33637000000,122491000000,48508000000,<NA>,<NA>,77614000000,<NA>,<NA>,<NA>,82882000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,82882000000,209004000000,331495000000,50374000000,50374000000,<NA>,<NA>,<NA>,9923000000,<NA>,<NA>,<NA>,71478000000,8979000000,<NA>,<NA>,<NA>,62499000000,131775000000,91775000000,<NA>,<NA>,42115000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,42115000000,133890000000,265665000000,<NA>,89806000000,<NA>,<NA>,<NA>,<NA>,-17607000000,-6369000000,65830000000,<NA>,65830000000,331495000000
116,AAPL,111052,simfin,us,A,False,USD,2025,Q4,2025-09-30,2025-10-31,2025-10-31,14948500000,15004697000,54697000000,35934000000,18763000000,39777000000,39777000000,<NA>,None,5718000000,<NA>,<NA>,<NA>,<NA>,47765000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,47765000000,147957000000,49834000000,<NA>,<NA>,77723000000,<NA>,<NA>,<NA>,83727000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,83727000000,211284000000,359241000000,69860000000,69860000000,<NA>,<NA>,<NA>,7979000000,<NA>,<NA>,<NA>,75442000000,9055000000,<NA>,<NA>,<NA>,66387000000,153281000000,90678000000,<NA>,<NA>,41549000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,41549000000,132227000000,285508000000,<NA>,93568000000,<NA>,<NA>,<NA>,<NA>,-14264000000,-5571000000,73733000000,<NA>,73733000000,359241000000
221,AAPL,111052,simfin,us,Q,False,USD,2025,Q4,2025-09-30,2025-10-31,2025-10-31,14815308000,14863611000,54697000000,35934000000,18763000000,39777000000,39777000000,<NA>,None,5718000000,<NA>,<NA>,<NA>,<NA>,47765000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,47765000000,147957000000,49834000000,<NA>,<NA>,77723000000,<NA>,<NA>,<NA>,83727000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,83727000000,211284000000,359241000000,69860000000,69860000000,<NA>,<NA>,<NA>,7979000000,<NA>,<NA>,<NA>,75442000000,9055000000,<NA>,<NA>,<NA>,66387000000,153281000000,90678000000,<NA>,<NA>,41549000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,41549000000,132227000000,285508000000,<NA>,93568000000,<NA>,<NA>,<NA>,<NA>,-14264000000,-5571000000,73733000000,<NA>,73733000000,359241000000
247,AAPL,111052,simfin,us,Q,False,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,66907000000,45317000000,21590000000,39921000000,39921000000,<NA>,None,5875000000,<NA>,<NA>,<NA>,<NA>,45401000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,45401000000,158104000000,50159000000,<NA>,<NA>,77888000000,<NA>,<NA>,<NA>,93146000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,93146000000,221193000000,379297000000,70587000000,70587000000,<NA>,<NA>,<NA>,1997000000,<NA>,<NA>,<NA>,77956000000,9413000000,<NA>,<NA>,<NA>,68543000000,150540000000,88512000000,<NA>,<NA>,52055000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,52055000000,140567000000,291107000000,<NA>,95221000000,<NA>,<NA>,<NA>,<NA>,-2177000000,-4854000000,88190000000,<NA>,88190000000,379297000000
211,AAPL,111052,simfin,us,Q,False,USD,2026,Q2,2026-03-31,2026-05-01,2026-05-01,14673278000,14725873000,146595000000,45572000000,101023000000,30339000000,30339000000,<NA>,None,6747000000,<NA>,<NA>,<NA>,<NA>,38521000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,38521000000,222202000000,50116000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,98764000000,21334000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,77430000000,148880000000,371082000000,57349000000,57349000000,<NA>,<NA>,<NA>,1997000000,<NA>,<NA>,<NA>,66985000000,9331000000,<NA>,<NA>,<NA>,57654000000,126331000000,82714000000,<NA>,<NA>,55546000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,55546000000,138260000000,264591000000,<NA>,99507000000,<NA>,<NA>,<NA>,<NA>,12359000000,-5375000000,106491000000,<NA>,106491000000,371082000000

### balance (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,14673278000.0,26309612000.0,21835233546.153847,3815688906.030132
Shares (Diluted),130.0,14725873000.0,26541056000.0,22181176730.76923,3986293905.81803
"Cash, Cash Equivalents & Short Term Investments",130.0,4027000000.0,146595000000.0,40473446153.846153,31769732570.693085
Cash & Cash Equivalents,130.0,1191000000.0,50530000000.0,17368376923.076923,13505997804.171488
Short Term Investments,130.0,1038000000.0,101023000000.0,23105069230.76923,20215074168.323719
Accounts & Notes Receivable,130.0,466000000.0,39921000000.0,11549430769.23077,10612029898.053692
"Accounts Receivable, Net",130.0,466000000.0,39921000000.0,11549430769.23077,10612029898.053692
Inventories,130.0,11000000.0,7662000000.0,2418592307.692307,2432489188.918202
Other Short Term Assets,130.0,330000000.0,53971000000.0,18668861538.46154,16024982358.105078
Misc. Short Term Assets,130.0,161000000.0,53971000000.0,17853376923.076923,16272424592.316956
Total Current Assets,130.0,5143000000.0,225680000000.0,73110330769.230774,57733713051.822746
"Property, Plant & Equipment, Net",130.0,313000000.0,50159000000.0,18944953846.153847,17686108862.91927
Other Long Term Assets,130.0,256000000.0,98764000000.0,21214238461.53846,25939014775.658745
Payables & Accruals,130.0,1518000000.0,89266000000.0,30879853846.153847,24031691329.508377
Total Assets,130.0,6021000000.0,406794000000.0,184078669230.769226,149356164231.33493
Total Noncurrent Assets,130.0,850000000.0,262984000000.0,110968338461.538467,96420892858.933914
Misc. Long Term Assets,130.0,144000000.0,93146000000.0,19046807692.307693,25892992550.317417
Other Equity,130.0,-12912000000.0,2710000000.0,-1513053846.153846,3365281547.85048
Other Long Term Liabilities,130.0,218000000.0,56795000000.0,24465961538.46154,21777151470.320904
Total Current Liabilities,130.0,1835000000.0,254203000000.0,81608407692.307693,78114334704.462982
Accounts Payable,130.0,801000000.0,74362000000.0,25117723076.923077,22583685973.624352
Total Equity,130.0,3920000000.0,140199000000.0,61570030769.230766,46521049170.472565
Equity Before Minority Interest,130.0,3920000000.0,140199000000.0,61570030769.230766,46521049170.472565
Total Liabilities & Equity,130.0,6021000000.0,406794000000.0,184078669230.769226,149356164231.33493
Total Noncurrent Liabilities,130.0,218000000.0,162431000000.0,40900230769.230766,51276136254.466774
Retained Earnings,130.0,-19154000000.0,116572000000.0,34822607692.307693,41232873326.035271
Share Capital & Additional Paid-In Capital,130.0,1502000000.0,99507000000.0,28258723076.923077,27582572345.487228
Total Liabilities,130.0,2101000000.0,309259000000.0,122508638461.538467,117525697533.470291
Misc. Long Term Liabilities,112.0,323000000.0,56795000000.0,27139339285.714287,21219926279.072071
Deferred Revenue (Short Term),91.0,2053000000.0,9461000000.0,6886483516.483517,1924318392.243153
Other Short Term Liabilities,91.0,2053000000.0,86553000000.0,29637472527.472527,27520574272.650253
Other Payables & Accruals,89.0,717000000.0,26756000000.0,8416595505.617977,8519180627.372433
Long Term Investments & Receivables,88.0,2379000000.0,207944000000.0,104604420454.545456,55383239852.99424
Intangible Assets,87.0,16000000.0,21334000000.0,1940344827.586207,3091950106.503443
Short Term Debt,85.0,0.0,122798000000.0,45855317647.058823,48288179485.058578
Goodwill,78.0,38000000.0,5889000000.0,1448153846.153846,1987624243.127491
Deferred Tax Assets (Short Term),76.0,162000000.0,5141000000.0,1394907894.736842,1390416840.880284

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Cash & Cash Equivalents,Short Term Investments,Accounts & Notes Receivable,"Accounts Receivable, Net","Notes Receivable, Net",Unbilled Revenues,Inventories,Raw Materials,Work In Process,Finished Goods,Other Inventory,Other Short Term Assets,Prepaid Expenses,Derivative & Hedging Assets (Short Term),Assets Held-for-Sale,Deferred Tax Assets (Short Term),Income Taxes Receivable,Discontinued Operations (Short Term),Misc. Short Term Assets,Total Current Assets,"Property, Plant & Equipment, Net","Property, Plant & Equipment",Accumulated Depreciation,Long Term Investments & Receivables,Long Term Investments,Long Term Marketable Securities,Long Term Receivables,Other Long Term Assets,Intangible Assets,Goodwill,Other Intangible Assets,Prepaid Expense,Deferred Tax Assets (Long Term),Derivative & Hedging Assets (Long Term),Prepaid Pension Costs,Discontinued Operations (Long Term),Investments in Affiliates,Misc. Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Accounts Payable,Accrued Taxes,Interest & Dividends Payable,Other Payables & Accruals,Short Term Debt,Short Term Borrowings,Short Term Capital Leases,Current Portion of Long Term Debt,Other Short Term Liabilities,Deferred Revenue (Short Term),Liabilities from Derivatives & Hedging (Short Term),Deferred Tax Liabilities (Short Term),Liabilities from Discontinued Operations (Short Term),Misc. Short Term Liabilities,Total Current Liabilities,Long Term Debt,Long Term Borrowings,Long Term Capital Leases,Other Long Term Liabilities,Accrued Liabilities,Pension Liabilities,Pensions,Other Post-Retirement Benefits,Deferred Compensation,Deferred Revenue (Long Term),Deferred Tax Liabilities (Long Term),Liabilities from Derivatives & Hedging (Long Term),Liabilities from Discontinued Operations (Long Term),Misc. Long Term Liabilities,Total Noncurrent Liabilities,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Common Stock,Additional Paid in Capital,Other Share Capital,Treasury Stock,Retained Earnings,Other Equity,Equity Before Minority Interest,Minority Interest,Total Equity,Total Liabilities & Equity
105,AAPL,111052,simfin,us,Q,True,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,313000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1063000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1063000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
134,AAPL,111052,simfin,us,Q,True,USD,2000,Q4,2000-09-30,2000-12-21,2001-12-21,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,419000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
179,AAPL,111052,simfin,us,A,True,USD,2000,Q4,2000-09-30,2000-12-21,2001-12-21,24208660000,24900176000,4027000000,1191000000,2836000000,953000000,953000000,<NA>,None,33000000,<NA>,<NA>,<NA>,<NA>,414000000,<NA>,<NA>,<NA>,162000000,<NA>,<NA>,252000000,5427000000,419000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,957000000,1376000000,6803000000,1933000000,1157000000,<NA>,<NA>,776000000,300000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2233000000,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,463000000,<NA>,<NA>,<NA>,463000000,2696000000,76000000,1502000000,<NA>,<NA>,<NA>,<NA>,2285000000,244000000,4107000000,<NA>,4107000000,6803000000
69,AAPL,111052,simfin,us,Q,True,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,4336000000,2310000000,2026000000,466000000,466000000,<NA>,None,11000000,<NA>,<NA>,<NA>,<NA>,330000000,<NA>,<NA>,<NA>,169000000,<NA>,<NA>,161000000,5143000000,564000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,314000000,76000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,238000000,878000000,6021000000,1518000000,801000000,<NA>,<NA>,717000000,317000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1835000000,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,266000000,2101000000,<NA>,1693000000,<NA>,<NA>,<NA>,<NA>,2260000000,-33000000,3920000000,<NA>,3920000000,6021000000
98,AAPL,111052,simfin,us,Q,True,USD,2001,Q2,2001-03-31,2001-05-14,2002-05-14,24208660000,24900176000,4336000000,2310000000,2026000000,466000000,466000000,<NA>,None,11000000,<NA>,<NA>,<NA>,<NA>,330000000,<NA>,<NA>,<NA>,169000000,<NA>,<NA>,161000000,5143000000,564000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,314000000,76000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,238000000,878000000,6021000000,1518000000,801000000,<NA>,<NA>,717000000,317000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1835000000,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,266000000,<NA>,<NA>,<NA>,266000000,2101000000,<NA>,1693000000,<NA>,<NA>,<NA>,<NA>,2260000000,-33000000,3920000000,<NA>,3920000000,6021000000
127,AAPL,111052,simfin,us,Q,True,USD,2025,Q3,2025-06-30,2025-08-01,2025-08-01,14902886000,14948179000,55372000000,36269000000,19103000000,27557000000,27557000000,<NA>,None,5925000000,<NA>,<NA>,<NA>,<NA>,33637000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33637000000,122491000000,48508000000,<NA>,<NA>,77614000000,<NA>,<NA>,<NA>,82882000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,82882000000,209004000000,331495000000,50374000000,50374000000,<NA>,<NA>,<NA>,9923000000,<NA>,<NA>,<NA>,71478000000,8979000000,<NA>,<NA>,<NA>,62499000000,131775000000,91775000000,<NA>,<NA>,42115000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,42115000000,133890000000,265665000000,<NA>,89806000000,<NA>,<NA>,<NA>,<NA>,-17607000000,-6369000000,65830000000,<NA>,65830000000,331495000000
34,AAPL,111052,simfin,us,A,True,USD,2025,Q4,2025-09-30,2025-10-31,2026-05-01,14948500000,15004697000,132420000000,35934000000,96486000000,39777000000,39777000000,<NA>,None,5718000000,<NA>,<NA>,<NA>,<NA>,47765000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,47765000000,225680000000,49834000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,83727000000,11093000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72634000000,133561000000,359241000000,69860000000,69860000000,<NA>,<NA>,<NA>,7979000000,<NA>,<NA>,<NA>,75442000000,9055000000,<NA>,<NA>,<NA>,66387000000,153281000000,90678000000,<NA>,<NA>,41549000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,41549000000,132227000000,285508000000,<NA>,93568000000,<NA>,<NA>,<NA>,<NA>,-14264000000,-5571000000,73733000000,<NA>,73733000000,359241000000
194,AAPL,111052,simfin,us,Q,True,USD,2025,Q4,2025-09-30,2025-10-31,2026-05-01,14815308000,14863611000,132420000000,35934000000,96486000000,39777000000,39777000000,<NA>,None,5718000000,<NA>,<NA>,<NA>,<NA>,47765000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,47765000000,225680000000,49834000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,83727000000,11093000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,72634000000,133561000000,359241000000,69860000000,69860000000,<NA>,<NA>,<NA>,7979000000,<NA>,<NA>,<NA>,75442000000,9055000000,<NA>,<NA>,<NA>,66387000000,153281000000,90678000000,<NA>,<NA>,41549000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,41549000000,132227000000,285508000000,<NA>,93568000000,<NA>,<NA>,<NA>,<NA>,-14264000000,-5571000000,73733000000,<NA>,73733000000,359241000000
0,AAPL,111052,simfin,us,Q,True,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,66907000000,45317000000,21590000000,39921000000,39921000000,<NA>,None,5875000000,<NA>,<NA>,<NA>,<NA>,45401000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,45401000000,158104000000,50159000000,<NA>,<NA>,77888000000,<NA>,<NA>,<NA>,93146000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,93146000000,221193000000,379297000000,70587000000,70587000000,<NA>,<NA>,<NA>,1997000000,<NA>,<NA>,<NA>,77956000000,9413000000,<NA>,<NA>,<NA>,68543000000,150540000000,88512000000,<NA>,<NA>,52055000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,52055000000,140567000000,291107000000,<NA>,95221000000,<NA>,<NA>,<NA>,<NA>,-2177000000,-4854000000,88190000000,<NA>,88190000000,379297000000
137,AAPL,111052,simfin,us,Q,True,USD,2026,Q2,2026-03-31,2026-05-01,2026-05-01,14673278000,14725873000,146595000000,45572000000,101023000000,30339000000,30339000000,<NA>,None,6747000000,<NA>,<NA>,<NA>,<NA>,38521000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,38521000000,222202000000,50116000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,98764000000,21334000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,77430000000,148880000000,371082000000,57349000000,57349000000,<NA>,<NA>,<NA>,1997000000,<NA>,<NA>,<NA>,66985000000,9331000000,<NA>,<NA>,<NA>,57654000000,126331000000,82714000000,<NA>,<NA>,55546000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,55546000000,138260000000,264591000000,<NA>,99507000000,<NA>,<NA>,<NA>,<NA>,12359000000,-5375000000,106491000000,<NA>,106491000000,371082000000

## cashflow

### cashflow (as-reported)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,14673278000.0,26309612000.0,21835233546.153847,3815688906.030132
Shares (Diluted),130.0,14725873000.0,26541056000.0,22181176730.76923,3986293905.81803
Net Income/Starting Line,130.0,-195000000.0,112010000000.0,15834269230.76923,21840356767.533684
Depreciation & Amortization,130.0,18000000.0,12547000000.0,2308707692.307693,3080349711.964923
Non-Cash Items,130.0,-32441000000.0,12774000000.0,1215315384.615385,4587503849.200362
Change in Working Capital,130.0,-25000000000.0,37924000000.0,617930769.230769,5975064077.614904
Net Cash from Operating Activities,130.0,-125000000.0,122151000000.0,19976223076.923077,26228252817.021034
Change in Fixed Assets & Intangibles,130.0,-13548000000.0,-10000000.0,-2601130769.230769,3244723049.034753
Net Change in Long Term Investment,130.0,-44417000000.0,58093000000.0,-814915384.615385,12771128822.30406
Net Cash from Financing Activities,130.0,-121983000000.0,6884000000.0,-14718746153.846153,25856540960.140717
Net Cash from Investing Activities,130.0,-56274000000.0,45896000000.0,-4653492307.692307,13179771671.244608
Net Cash Before FX,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Net Change in Cash,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Cash from (Repurchase of) Equity,130.0,-94949000000.0,912000000.0,-12672561538.461538,20444121809.415024
Net Cash Before Disc. Operations and FX,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Other Investing Activities,129.0,-18536000000.0,220000000.0,-1065875968.992248,2283398433.557123
Acquisition of Fixed Assets & Intangibles,120.0,-13548000000.0,-11000000.0,-2448808333.333333,3180848671.955261
Decrease in Long Term Investment,111.0,-601000000.0,208111000000.0,26306243243.243244,35458343851.551224
Other Financing Activities,107.0,-6685000000.0,2334000000.0,-806915887.850467,1644498937.977567
Increase in Capital Stock,104.0,0.0,1105000000.0,222471153.846154,237902360.518771
Increase in Long Term Investment,87.0,-217128000000.0,0.0,-36002459770.114944,43104145782.857994
Decrease in Capital Stock,78.0,-94949000000.0,0.0,-21417564102.564102,22763559019.540356
Dividends Paid,69.0,-15421000000.0,-2488000000.0,-5258826086.956522,4063710680.981266
Net Cash from Acquisitions & Divestitures,68.0,-3765000000.0,40000000.0,-343676470.588235,630320634.853156
Cash from (Repayment of) Debt,67.0,-9901000000.0,29305000000.0,2734253731.343284,8414462175.764546

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
188,AAPL,111052,simfin,us,A,False,USD,2000,FY,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,786000000,<NA>,<NA>,<NA>,84000000,-194000000,<NA>,<NA>,<NA>,192000000,<NA>,<NA>,<NA>,<NA>,<NA>,868000000,-142000000,<NA>,<NA>,<NA>,-142000000,<NA>,<NA>,<NA>,3215000000,3447000000,-232000000,<NA>,<NA>,<NA>,<NA>,<NA>,-4045000000,<NA>,-972000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-31000000,85000000,-116000000,<NA>,<NA>,-31000000,-135000000,<NA>,-135000000,<NA>,-135000000
201,AAPL,111052,simfin,us,Q,False,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,200000000,<NA>,<NA>,<NA>,25000000,-4000000,<NA>,<NA>,<NA>,13000000,<NA>,<NA>,<NA>,<NA>,<NA>,234000000,-10000000,1000000,<NA>,<NA>,-11000000,<NA>,<NA>,<NA>,680000000,696000000,-16000000,<NA>,<NA>,<NA>,<NA>,<NA>,-1175000000,<NA>,-505000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-47000000,3000000,-50000000,<NA>,<NA>,-47000000,-318000000,<NA>,-318000000,<NA>,-318000000
78,AAPL,111052,simfin,us,Q,False,USD,2000,Q4,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,170000000,<NA>,<NA>,<NA>,18000000,-62000000,<NA>,<NA>,<NA>,74000000,<NA>,<NA>,<NA>,<NA>,<NA>,200000000,-77000000,-11000000,<NA>,<NA>,-66000000,<NA>,<NA>,<NA>,718000000,718000000,0,<NA>,<NA>,<NA>,<NA>,<NA>,-1004000000,<NA>,-363000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10000000,35000000,-25000000,<NA>,<NA>,10000000,-153000000,<NA>,-153000000,<NA>,-153000000
189,AAPL,111052,simfin,us,A,False,USD,2001,FY,2001-09-30,2001-12-21,2001-12-21,24208660000,24900176000,-25000000,<NA>,<NA>,<NA>,102000000,-103000000,<NA>,<NA>,<NA>,211000000,<NA>,<NA>,<NA>,<NA>,<NA>,185000000,-232000000,<NA>,<NA>,<NA>,-232000000,<NA>,<NA>,<NA>,5150000000,5151000000,-1000000,<NA>,<NA>,<NA>,<NA>,<NA>,-4026000000,<NA>,892000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,42000000,42000000,<NA>,<NA>,<NA>,42000000,1119000000,<NA>,1119000000,<NA>,1119000000
212,AAPL,111052,simfin,us,Q,False,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,-195000000,<NA>,<NA>,<NA>,24000000,-162000000,<NA>,<NA>,<NA>,320000000,<NA>,<NA>,<NA>,<NA>,<NA>,-13000000,-22000000,<NA>,<NA>,<NA>,-22000000,<NA>,<NA>,<NA>,1146000000,1147000000,-1000000,<NA>,<NA>,<NA>,<NA>,<NA>,-568000000,<NA>,556000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3000000,3000000,<NA>,<NA>,<NA>,3000000,546000000,<NA>,546000000,<NA>,546000000
13,AAPL,111052,simfin,us,Q,False,USD,2025,Q2,2025-03-31,2025-05-02,2025-01-31,14994082000,15056133000,24780000000,<NA>,<NA>,<NA>,2661000000,3018000000,<NA>,<NA>,<NA>,-6507000000,<NA>,<NA>,<NA>,<NA>,<NA>,23952000000,-3071000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6020000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-32000000,<NA>,2917000000,-3758000000,976000000,<NA>,<NA>,<NA>,<NA>,-25898000000,<NA>,-25898000000,-326000000,<NA>,-29006000000,-2137000000,<NA>,-2137000000,<NA>,-2137000000
219,AAPL,111052,simfin,us,Q,False,USD,2025,Q3,2025-06-30,2025-08-01,2025-05-02,14902886000,14948179000,23434000000,<NA>,<NA>,<NA>,2830000000,3637000000,<NA>,<NA>,<NA>,-2034000000,<NA>,<NA>,<NA>,<NA>,<NA>,27867000000,-3462000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8875000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-340000000,<NA>,5073000000,-3945000000,2711000000,<NA>,<NA>,<NA>,<NA>,-21075000000,<NA>,-21075000000,-2524000000,<NA>,-24833000000,8107000000,<NA>,8107000000,<NA>,8107000000
14,AAPL,111052,simfin,us,Q,False,USD,2025,Q4,2025-09-30,2025-10-31,2025-08-01,14815308000,14863611000,27466000000,<NA>,<NA>,<NA>,3127000000,4842000000,<NA>,<NA>,<NA>,-5707000000,<NA>,<NA>,<NA>,<NA>,<NA>,29728000000,-3242000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1160000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-505000000,<NA>,-2587000000,-3862000000,-3217000000,<NA>,<NA>,<NA>,<NA>,-20132000000,<NA>,-20132000000,-265000000,<NA>,-27476000000,-335000000,<NA>,-335000000,<NA>,-335000000
73,AAPL,111052,simfin,us,Q,False,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,42097000000,<NA>,<NA>,<NA>,3214000000,3066000000,<NA>,<NA>,<NA>,5548000000,<NA>,<NA>,<NA>,<NA>,<NA>,53925000000,-2373000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-2359000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-154000000,<NA>,-4886000000,-3921000000,-8074000000,<NA>,<NA>,<NA>,<NA>,-24701000000,<NA>,-24701000000,-2960000000,<NA>,-39656000000,9383000000,<NA>,9383000000,<NA>,9383000000
231,AAPL,111052,simfin,us,Q,False,USD,2026,Q2,2026-03-31,2026-05-01,2026-01-30,14673278000,14725873000,29578000000,<NA>,<NA>,<NA>,3439000000,2339000000,<NA>,<NA>,<NA>,-6654000000,<NA>,<NA>,<NA>,<NA>,<NA>,28702000000,-1971000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-2767000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1430000000,<NA>,-6168000000,-3822000000,-5751000000,<NA>,<NA>,<NA>,<NA>,-12288000000,<NA>,-12288000000,-418000000,<NA>,-22279000000,255000000,<NA>,255000000,<NA>,255000000

### cashflow (restated)

*Fiscal Year 2000 .. 2026  |  A=26 Q=104  |  USD  |  130 rows*

,count,min,max,mean,std
Shares (Basic),130.0,14673278000.0,26309612000.0,21835233546.153847,3815688906.030132
Shares (Diluted),130.0,14725873000.0,26541056000.0,22181176730.76923,3986293905.81803
Net Income/Starting Line,130.0,-195000000.0,112010000000.0,15892715384.615385,21808741646.887646
Depreciation & Amortization,130.0,18000000.0,12547000000.0,2309446153.846154,3079895948.764771
Non-Cash Items,130.0,-32441000000.0,12774000000.0,1240223076.923077,4576835109.168516
Change in Working Capital,130.0,-25000000000.0,37924000000.0,549730769.230769,5953208625.813207
Net Cash from Operating Activities,130.0,-125000000.0,122151000000.0,19992115384.615383,26240617476.733021
Change in Fixed Assets & Intangibles,130.0,-13313000000.0,-10000000.0,-2583746153.846154,3213470712.537137
Net Change in Long Term Investment,130.0,-44417000000.0,58093000000.0,-1262761538.461539,12738325059.845671
Net Cash from Financing Activities,130.0,-121983000000.0,6884000000.0,-14734607692.307692,25855029916.075916
Other Investing Activities,130.0,-10905000000.0,7182000000.0,-658830769.230769,1522427000.266002
Net Cash from Investing Activities,130.0,-56274000000.0,45896000000.0,-4653523076.923077,13179782173.574577
Net Change in Cash,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Net Cash Before FX,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Net Cash Before Disc. Operations and FX,130.0,-13088000000.0,24311000000.0,603984615.384615,5106213522.993054
Cash from (Repurchase of) Equity,130.0,-94949000000.0,912000000.0,-12703053846.153847,20498401299.474243
Acquisition of Fixed Assets & Intangibles,113.0,-13313000000.0,-11000000.0,-2283159292.035398,3036197532.53018
Other Financing Activities,109.0,-6383000000.0,2334000000.0,-774660550.458716,1569589567.844053
Decrease in Long Term Investment,104.0,-601000000.0,208111000000.0,25035836538.46154,34421098970.149498
Increase in Capital Stock,99.0,-430000000.0,912000000.0,193606060.606061,217648181.667806
Decrease in Capital Stock,83.0,-94949000000.0,0.0,-20127277108.433735,22646667275.035789
Increase in Long Term Investment,80.0,-217128000000.0,1000000.0,-35949575000.0,42526987428.46875
Dividends Paid,76.0,-15421000000.0,0.0,-4774460526.315789,4161235439.75677
Cash from (Repayment of) Debt,74.0,-9901000000.0,29305000000.0,2475608108.108108,8041163092.825118
Net Cash from Acquisitions & Divestitures,67.0,-3775000000.0,1225000000.0,-287522388.059702,638502850.144536

,Ticker,SrcId,Src,Market,Period,IsRestated,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Net Income/Starting Line,Net Income,Net Income from Discontinued Operations,Other Adjustments,Depreciation & Amortization,Non-Cash Items,Stock-Based Compensation,Deferred Income Taxes,Other Non-Cash Adjustments,Change in Working Capital,Change in Accounts Receivable,Change in Inventories,Change in Accounts Payable,Change in Other,Net Cash from Discontinued Operations (Operating),Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Disposition of Fixed Assets & Intangibles,Disposition of Fixed Assets,Disposition of Intangible Assets,Acquisition of Fixed Assets & Intangibles,Purchase of Fixed Assets,Acquisition of Intangible Assets,Other Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Decrease in Long Term Investment,Increase in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Divestitures,Cash for Acquisition of Subsidiaries,Cash for Joint Ventures,Net Cash from Other Acquisitions,Other Investing Activities,Net Cash from Discontinued Operations (Investing),Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,"Cash from (Repayment of) Short Term Debt, Net","Cash from (Repayment of) Long Term Debt, Net",Repayments of Long Term Debt,Cash from Long Term Debt,Cash from (Repurchase of) Equity,Increase in Capital Stock,Decrease in Capital Stock,Other Financing Activities,Net Cash from Discontinued Operations (Financing),Net Cash from Financing Activities,Net Cash Before Disc. Operations and FX,Change in Cash from Disc. Operations and Other,Net Cash Before FX,Effect of Foreign Exchange Rates,Net Change in Cash
19,AAPL,111052,simfin,us,A,True,USD,2000,FY,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,786000000,<NA>,<NA>,<NA>,84000000,-194000000,<NA>,<NA>,<NA>,192000000,<NA>,<NA>,<NA>,<NA>,<NA>,868000000,-142000000,<NA>,<NA>,<NA>,-142000000,<NA>,<NA>,<NA>,3215000000,3447000000,-232000000,<NA>,<NA>,<NA>,<NA>,<NA>,-4045000000,<NA>,-972000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-31000000,85000000,-116000000,<NA>,<NA>,-31000000,-135000000,<NA>,-135000000,<NA>,-135000000
206,AAPL,111052,simfin,us,Q,True,USD,2000,Q3,2000-06-30,2000-08-13,2001-08-13,24208660000,24900176000,200000000,<NA>,<NA>,<NA>,25000000,-4000000,<NA>,<NA>,<NA>,13000000,<NA>,<NA>,<NA>,<NA>,<NA>,234000000,-10000000,1000000,<NA>,<NA>,-11000000,<NA>,<NA>,<NA>,680000000,696000000,-16000000,<NA>,<NA>,<NA>,<NA>,<NA>,-1175000000,<NA>,-505000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-47000000,3000000,-50000000,<NA>,<NA>,-47000000,-318000000,<NA>,-318000000,<NA>,-318000000
241,AAPL,111052,simfin,us,Q,True,USD,2000,Q4,2000-09-30,2000-12-19,2002-12-19,24208660000,24900176000,170000000,<NA>,<NA>,<NA>,18000000,-62000000,<NA>,<NA>,<NA>,74000000,<NA>,<NA>,<NA>,<NA>,<NA>,200000000,-77000000,-11000000,<NA>,<NA>,-66000000,<NA>,<NA>,<NA>,718000000,718000000,0,<NA>,<NA>,<NA>,<NA>,<NA>,-1004000000,<NA>,-363000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10000000,35000000,-25000000,<NA>,<NA>,10000000,-153000000,<NA>,-153000000,<NA>,-153000000
177,AAPL,111052,simfin,us,A,True,USD,2001,FY,2001-09-30,2001-12-21,2003-12-19,24208660000,24900176000,-25000000,<NA>,<NA>,<NA>,100000000,-101000000,<NA>,<NA>,<NA>,211000000,<NA>,<NA>,<NA>,<NA>,<NA>,185000000,-232000000,<NA>,<NA>,<NA>,-232000000,<NA>,<NA>,<NA>,5151000000,5151000000,<NA>,-19000000,<NA>,<NA>,<NA>,<NA>,-4008000000,<NA>,892000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,42000000,42000000,<NA>,<NA>,<NA>,42000000,1119000000,<NA>,1119000000,<NA>,1119000000
51,AAPL,111052,simfin,us,Q,True,USD,2001,Q1,2000-12-31,2001-02-11,2002-02-11,24208660000,24900176000,-195000000,<NA>,<NA>,<NA>,24000000,-162000000,<NA>,<NA>,<NA>,320000000,<NA>,<NA>,<NA>,<NA>,<NA>,-13000000,-22000000,<NA>,<NA>,<NA>,-22000000,<NA>,<NA>,<NA>,1146000000,1147000000,-1000000,<NA>,<NA>,<NA>,<NA>,<NA>,-568000000,<NA>,556000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3000000,3000000,<NA>,<NA>,<NA>,3000000,546000000,<NA>,546000000,<NA>,546000000
101,AAPL,111052,simfin,us,Q,True,USD,2025,Q2,2025-03-31,2025-05-02,2026-01-30,14994082000,15056133000,24780000000,<NA>,<NA>,<NA>,2661000000,3018000000,<NA>,<NA>,<NA>,-6507000000,<NA>,<NA>,<NA>,<NA>,<NA>,23952000000,-3071000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6020000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-32000000,<NA>,2917000000,-3758000000,976000000,<NA>,<NA>,<NA>,<NA>,-25898000000,<NA>,-25898000000,-326000000,<NA>,-29006000000,-2137000000,<NA>,-2137000000,<NA>,-2137000000
170,AAPL,111052,simfin,us,Q,True,USD,2025,Q3,2025-06-30,2025-08-01,2026-05-01,14902886000,14948179000,23434000000,<NA>,<NA>,<NA>,2830000000,3637000000,<NA>,<NA>,<NA>,-2034000000,<NA>,<NA>,<NA>,<NA>,<NA>,27867000000,-3462000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8875000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-340000000,<NA>,5073000000,-3945000000,2711000000,<NA>,<NA>,<NA>,<NA>,-21075000000,<NA>,-21075000000,-2524000000,<NA>,-24833000000,8107000000,<NA>,8107000000,<NA>,8107000000
102,AAPL,111052,simfin,us,Q,True,USD,2025,Q4,2025-09-30,2025-10-31,2025-08-01,14815308000,14863611000,27466000000,<NA>,<NA>,<NA>,3127000000,4842000000,<NA>,<NA>,<NA>,-5707000000,<NA>,<NA>,<NA>,<NA>,<NA>,29728000000,-3242000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1160000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-505000000,<NA>,-2587000000,-3862000000,-3217000000,<NA>,<NA>,<NA>,<NA>,-20132000000,<NA>,-20132000000,-265000000,<NA>,-27476000000,-335000000,<NA>,-335000000,<NA>,-335000000
199,AAPL,111052,simfin,us,Q,True,USD,2026,Q1,2025-12-31,2026-01-30,2026-01-30,14748158000,14810356000,42097000000,<NA>,<NA>,<NA>,3214000000,3066000000,<NA>,<NA>,<NA>,5548000000,<NA>,<NA>,<NA>,<NA>,<NA>,53925000000,-2373000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-2359000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-154000000,<NA>,-4886000000,-3921000000,-8074000000,<NA>,<NA>,<NA>,<NA>,-24701000000,<NA>,-24701000000,-2960000000,<NA>,-39656000000,9383000000,<NA>,9383000000,<NA>,9383000000
187,AAPL,111052,simfin,us,Q,True,USD,2026,Q2,2026-03-31,2026-05-01,2026-01-30,14673278000,14725873000,29578000000,<NA>,<NA>,<NA>,3439000000,2339000000,<NA>,<NA>,<NA>,-6654000000,<NA>,<NA>,<NA>,<NA>,<NA>,28702000000,-1971000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-2767000000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1430000000,<NA>,-6168000000,-3822000000,-5751000000,<NA>,<NA>,<NA>,<NA>,-12288000000,<NA>,-12288000000,-418000000,<NA>,-22279000000,255000000,<NA>,255000000,<NA>,255000000

## market_data

*no rows*